import type { Concept } from "./types";

export const domain1Concepts: Concept[] = [
  {
    id: "c1-01",
    slug: "documentary-hypothesis",
    domainId: "d1",
    name: "Documentary Hypothesis (JEDP)",
    summary:
      "The theory that the Torah was composed from four distinct sources, not written by Moses alone.",
    lensTags: ["academic", "protestant", "catholic"],
    relatedConceptSlugs: ["torah-overview", "textual-criticism"],
    relatedTextRefs: ["Genesis 1", "Genesis 2"],
    layers: {
      accessible:
        "The first five books of the Bible (Genesis through Deuteronomy) are traditionally attributed to Moses. But scholars have noticed that these books contain duplicate stories, contradictions, different names for God, and distinct writing styles. The Documentary Hypothesis proposes that the Torah was actually assembled from four separate sources, written at different times: J (Yahwist, uses YHWH for God's name), E (Elohist, uses Elohim), D (Deuteronomist, concentrated in Deuteronomy), and P (Priestly, focused on rituals and genealogies). These were later woven together by editors into the text we have today.",
      intermediate:
        "The Documentary Hypothesis was developed primarily by Julius Wellhausen in the 19th century, building on earlier observations by Jean Astruc and others. The key evidence includes: (1) Duplicate narratives -- there are two creation accounts (Genesis 1 and Genesis 2), two flood narratives interleaved, two versions of Abraham lying about Sarah. (2) Different divine names -- some passages consistently use YHWH, others use Elohim. (3) Distinct vocabularies and theological concerns -- P is obsessed with genealogies, dates, and ritual purity; J tells vivid stories with an anthropomorphic God who walks in gardens. (4) Anachronisms -- references to kings and places that didn't exist in Moses' time.\n\nThe four sources and their approximate dates: J (Yahwist) -- 10th-9th century BCE, southern Judah; E (Elohist) -- 9th-8th century BCE, northern Israel; D (Deuteronomist) -- 7th century BCE, likely connected to Josiah's reform (2 Kings 22-23); P (Priestly) -- 6th-5th century BCE, exilic or post-exilic. A later redactor (R) combined them.\n\nModern scholarship has moved beyond simple four-source division. Some scholars (like John Van Seters) see fewer sources; others (like Erhard Blum) prefer a supplementary model where later sources expanded earlier ones rather than being independent parallel documents. The European tradition tends toward fragmentary models. American scholarship generally retains a modified form of the hypothesis. What virtually all critical scholars agree on: the Torah was not written by a single author in a single sitting.",
      advanced:
        "The Documentary Hypothesis remains the dominant paradigm in critical Torah scholarship, though it has undergone significant revision since Wellhausen. Key developments include:\n\nRendtorff's tradition-historical approach challenges the existence of continuous source documents, proposing instead that independent tradition blocks (ancestral narratives, exodus, Sinai) were compiled gradually. Erhard Blum's composition model identifies a D-composition and a P-composition as the two main literary layers, arguing that J and E cannot be reliably separated as independent documents.\n\nThe neo-Documentarian school (Joel Baden, Jeffrey Stackert) has mounted a vigorous defense of the classic four-source model, arguing that the sources can be reconstructed as coherent, continuous narratives.\n\nThe 'Persian Imperial Authorization' hypothesis (Peter Frei) suggests that the Torah was compiled in its final form under Persian sponsorship as the legal document governing the province of Yehud -- which would explain why contradictory legal traditions were preserved rather than harmonized.\n\nArchaeological evidence complicates dating: Finkelstein and Silberman's work on the historical David and Solomon suggests the J source may be later than traditionally dated, while the discovery of inscriptions like the Kuntillet Ajrud texts show that early Israelite religion was far more diverse than the biblical text presents.\n\nFor the reader: understanding that the Torah is a composite document does not diminish it. It reveals a tradition that was alive enough to be continually reinterpreted, and editors honest enough to preserve voices that disagreed with each other. The final text is a conversation, not a monologue."
    },
  },

  {
    id: "c1-02",
    slug: "septuagint",
    domainId: "d1",
    name: "The Septuagint (LXX)",
    summary:
      "The ancient Greek translation of the Hebrew Bible -- the version most NT authors actually quoted.",
    lensTags: ["academic", "orthodox", "catholic"],
    relatedConceptSlugs: ["textual-criticism", "torah-overview", "septuagint"],
    relatedTextRefs: ["Isaiah 7:14"],
    layers: {
      accessible:
        "The Septuagint (abbreviated LXX, meaning 'seventy') is the ancient Greek translation of the Hebrew Bible, produced in Alexandria, Egypt, starting around the 3rd century BCE. This is important because most New Testament authors quoted from the Septuagint, not the Hebrew text. Sometimes the Greek translation says something different from the Hebrew original -- and those differences shaped Christian theology. The most famous example: Isaiah 7:14, where the Hebrew word 'almah' (young woman) was translated into Greek as 'parthenos' (virgin). That single translation choice is the textual basis for the doctrine of the virgin birth.",
      intermediate:
        "The Septuagint's origin story (the Letter of Aristeas) claims that 72 Jewish scholars independently produced identical translations in 72 days. This is legendary -- the actual translation was produced over roughly 200 years by different translators with varying skills and approaches. The Torah was translated first and most carefully; later books show more variation in translation quality and method.\n\nKey differences between the LXX and the Hebrew Masoretic Text (MT): Jeremiah is about one-seventh shorter in the LXX and arranged in a different order. The Psalms are numbered differently (LXX Psalms 9-10 = MT Psalm 9; the numbering is off by one through most of the Psalter). The LXX includes additional books not in the Hebrew canon: Tobit, Judith, Wisdom of Solomon, Sirach, Baruch, 1-2 Maccabees, and additions to Esther and Daniel.\n\nThe Dead Sea Scrolls revealed something scholars had debated for centuries: some LXX readings that differ from the MT actually reflect an older Hebrew text. The LXX translators were not always making mistakes or 'improving' the text -- sometimes their Hebrew source was genuinely different from what became the standard Masoretic tradition.\n\nFor Christianity: the LXX was the church's Bible for the first several centuries. When Jerome produced the Latin Vulgate (4th-5th century CE), he controversially went back to the Hebrew ('Hebraica veritas'), which Protestants later followed. Catholics and Orthodox retained the LXX-based books in their canons.",
      advanced:
        "The Septuagint is not a single translation but a library of translations produced over centuries. Modern critical editions (Rahlfs-Hanhart, Gottingen Septuagint) attempt to reconstruct the 'Old Greek' -- the earliest recoverable form of the translation -- from a complex manuscript tradition that includes: Codex Vaticanus (4th century), Codex Sinaiticus (4th century), Codex Alexandrinus (5th century), papyri, and patristic quotations.\n\nOrigin and recension history: Origen's Hexapla (3rd century CE) presented six columns -- Hebrew, Hebrew in Greek letters, Aquila, Symmachus, the LXX, and Theodotion. His corrections to the LXX (marked with asterisks and obeli) became mixed with the unrevised text, creating the 'Hexaplaric' recension. Lucian of Antioch and Hesychius of Egypt also produced recensions. Untangling these layers is the central task of LXX textual criticism.\n\nTheological load of translation choices beyond Isaiah 7:14: the LXX translators consistently replace the divine name YHWH with Kyrios (Lord) -- this directly shapes NT Christology when early Christians apply 'Kyrios' passages to Jesus. The LXX rendering of Exodus 3:14 as 'ego eimi ho on' (I am the one who is) influenced the Greek philosophical reading of God as Being Itself, which shaped patristic and medieval theology.\n\nThe relationship between the LXX and the NT is deeper than quotation. The theological vocabulary of the NT -- dikaiosyne, charis, agape, ekklesia, hamartia -- was shaped by how the LXX translators rendered Hebrew concepts into Greek. Understanding the LXX's translation choices is essential for understanding what NT authors meant when they used these words."
    },
  },

  {
    id: "c1-03",
    slug: "wisdom-literature",
    domainId: "d1",
    name: "Wisdom Literature",
    summary:
      "Job, Psalms, Proverbs, Ecclesiastes, Song of Songs -- Israel's philosophical tradition questioning everything.",
    lensTags: ["academic", "protestant", "catholic", "jewish"],
    relatedConceptSlugs: ["theodicy", "grief-lament"],
    relatedTextRefs: ["Job 38", "Ecclesiastes 1:2", "Psalm 22"],
    layers: {
      accessible:
        "The wisdom books of the Bible -- Job, Proverbs, Ecclesiastes, Song of Songs, and the Psalms -- represent a tradition of questioning, doubt, and hard-won insight that many people don't expect to find in scripture. Proverbs offers practical guidance. Job demands to know why innocent people suffer and never gets a satisfying answer. Ecclesiastes declares that everything is 'hevel' (vapor, breath, fleeting) and questions whether any human effort matters. Song of Songs is unapologetically erotic love poetry. The Psalms contain worship, rage, grief, and protests against God. This is Israel's philosophical tradition -- and it's far more honest about the difficulty of life than most churches admit.",
      intermediate:
        "The wisdom tradition (hokhmah) was not uniquely Israelite. Egyptian Instruction literature (Instruction of Amenemope has striking parallels with Proverbs 22-24), Mesopotamian wisdom texts (Ludlul Bel Nemeqi, the 'Babylonian Job'), and Sumerian proverb collections all share the same genre. Israel participated in an international wisdom movement.\n\nKey features of each book: Job is a masterpiece of theodicy (the problem of suffering). The prose frame (chapters 1-2, 42) tells a simple story; the poetic core (3-41) is a profound philosophical argument. Job's friends offer orthodox theology ('you must have sinned'), Job refuses to accept it, and God's answer from the whirlwind (chapters 38-41) is not an explanation but an overwhelming display of creation's complexity. The question 'why do the innocent suffer?' is never directly answered.\n\nEcclesiastes (Qohelet, 'the Teacher') is the Bible's most radical voice. 'Hevel havalim, hevel havalim, hakol hevel' -- variously translated as 'vanity of vanities,' 'meaninglessness,' 'absurdity,' or 'vapor.' The Hebrew word hevel literally means breath or vapor -- something that exists but cannot be grasped. Qohelet's conclusion is not nihilism but a recommendation to enjoy the present: eat, drink, find satisfaction in your work, because this fleeting moment is all you can hold.\n\nThe Psalms contain genres most worshippers never encounter: lament psalms (over 60 of them), imprecatory psalms (asking God to destroy enemies), and psalms of disorientation (Brueggemann's category) where the worshipper accuses God of abandonment (Psalm 88 ends in darkness with no resolution).",
      advanced:
        "The personification of Wisdom (Hokhmah) in Proverbs 8 is one of the most theologically significant passages in the Hebrew Bible. Wisdom speaks as a co-creator present with God 'before the beginning of the earth' (8:23), 'rejoicing in the inhabited world' (8:31). This figure -- feminine in Hebrew -- directly influenced the development of Logos theology in Hellenistic Judaism (Philo's Logos as divine mediator) and from there, the Prologue of John's Gospel ('In the beginning was the Logos'). The Wisdom tradition is a direct ancestor of Christology.\n\nThe book of Job raises interpretive problems that scholarship has never fully resolved. The Elihu speeches (chapters 32-37) appear to be a later insertion -- they break the literary structure, Elihu is never mentioned before or after, and the Hebrew style differs. The prose epilogue (42:7-17) where Job gets everything back sits uneasily with the poetic core's refusal of easy answers. Some scholars see the epilogue as the editor's way of domesticating a profoundly unsettling text.\n\nSong of Songs has been read allegorically for most of its interpretive history -- as a picture of God's love for Israel (Jewish midrash) or Christ's love for the Church (Christian tradition from Origen onward). But the text itself is unambiguously erotic poetry with no explicit theological content. Rabbi Akiva's famous declaration that 'all of Scripture is holy, but the Song of Songs is the Holy of Holies' (Mishnah Yadayim 3:5) suggests it was controversial even in antiquity. The literal, erotic reading has become mainstream in modern scholarship, though the question of why it's in the canon remains a genuinely open discussion."
    },
  },

  {
    id: "c1-04",
    slug: "torah-overview",
    domainId: "d1",
    name: "Torah / Pentateuch: The Five Books",
    summary:
      "Genesis, Exodus, Leviticus, Numbers, Deuteronomy -- the foundational narrative of creation, covenant, law, and exodus that anchors the entire biblical tradition.",
    lensTags: ["academic", "jewish", "protestant", "catholic"],
    relatedConceptSlugs: ["documentary-hypothesis", "biblical-hebrew"],
    relatedTextRefs: ["Genesis 12:1-3", "Exodus 20:1-17", "Deuteronomy 6:4-9"],
    layers: {
      accessible:
        "The Torah (Hebrew: 'instruction' or 'teaching') consists of five books: Genesis (creation, patriarchs, Joseph), Exodus (slavery, liberation, Sinai covenant), Leviticus (priestly regulations and holiness), Numbers (wilderness wandering), and Deuteronomy (Moses' farewell speeches). Together they tell the story of how God created the world, chose a particular family (Abraham's descendants), liberated them from slavery in Egypt, gave them the Law at Mount Sinai, and brought them to the edge of the promised land. For Judaism, the Torah is the most sacred part of Scripture -- the first five books carry more authority than the Prophets or Writings. For Christianity, the Torah is 'Old Testament' foundation that Jesus fulfilled, reinterpreted, or (depending on your tradition) superseded.",
      intermediate:
        "The Torah contains at least four major literary types woven together: narrative (stories of creation, patriarchs, exodus), law (casuistic case law and apodictic command law), poetry (blessings, songs), and genealogy. These are not separable -- the laws are embedded within narrative, making them inseparable from the story of God's relationship with Israel.\n\nThe Shema (Deuteronomy 6:4-9, 'Hear, O Israel, the LORD our God, the LORD is one') is the foundational confession of Jewish faith, recited twice daily. Its theological claim is not primarily about God's internal nature (Trinity vs. unity) but about exclusive loyalty: Israel must worship YHWH alone. The Hebrew word 'echad' (one) can mean 'one' or 'united' -- this ambiguity matters for later trinitarian debates.\n\nThe covenant structure of the Torah reflects Ancient Near Eastern treaty forms. The Sinai covenant follows the pattern of a suzerainty treaty: the great king (God) recounts his past actions for the vassal (Israel), stipulates obligations (the commandments), and lists blessings and curses for obedience and disobedience. This means the Ten Commandments are not abstract moral principles but covenant stipulations within a specific relationship. 'I am the LORD your God who brought you out of Egypt' (the historical prologue) precedes 'You shall have no other gods' (the first stipulation).",
      advanced:
        "The relationship between the Torah's narrative and legal sections raises fundamental hermeneutical questions. Jon Levenson argues that the Torah's narrative creates a 'canonical context' for the laws -- they cannot be understood apart from the exodus story. This means interpreting biblical law requires understanding the narrative theology in which it is embedded.\n\nThe composition of the Pentateuch remains the most debated question in Hebrew Bible scholarship. The Documentary Hypothesis (JEDP) has been modified, challenged, and partially rehabilitated over the past century. The European 'supplementary' model (the Pentateuch grew by successive additions to an original core) and the 'fragmentary' model (multiple independent traditions were assembled) compete with the classical documentary approach. What is no longer disputed: the Pentateuch is not a single composition by a single author. What remains disputed: how many sources, when they were written, and how they were combined.\n\nThe Torah's ongoing authority is the key question dividing Judaism and Christianity, and dividing Christian traditions from each other. For Orthodox Judaism, the Torah (both written and oral) is eternally binding. For Christianity, the relationship between Torah and gospel is the central theological question -- Paul, Matthew, James, and Hebrews each answer it differently, and two millennia of Christian theology have not produced consensus."
    },
  },

  {
    id: "c1-05",
    slug: "creation-accounts",
    domainId: "d1",
    name: "Two Creation Accounts: Genesis 1 vs Genesis 2",
    summary:
      "The Bible begins with two creation stories that contradict each other. This is not a problem -- it is a feature.",
    lensTags: ["academic", "protestant", "catholic"],
    relatedConceptSlugs: ["documentary-hypothesis", "torah-overview"],
    relatedTextRefs: ["Genesis 1:1-2:3", "Genesis 2:4-25"],
    layers: {
      accessible:
        "Genesis 1 and Genesis 2 tell creation differently. In Genesis 1, God (Elohim) creates in a structured seven-day sequence: light, sky, land, vegetation, stars, animals, then humans (male and female together, last). In Genesis 2, God (YHWH Elohim) forms a man first from dust, plants a garden, creates animals as potential companions, and only then creates a woman from the man's side. Different order. Different names for God. Different literary styles. Genesis 1 reads like liturgy -- rhythmic, ceremonial, cosmic. Genesis 2 reads like a story -- intimate, earthy, relational. For most of history, readers harmonized the two. Modern scholarship asks: what if they are two independent traditions, preserved side by side?",
      intermediate:
        "The two accounts reflect different sources (J and P in the Documentary Hypothesis) with different theological agendas. The Priestly account (Genesis 1:1-2:3) presents creation as cosmic ordering: God speaks and chaos becomes cosmos, darkness becomes light, waters become bounded. Humanity is the climax, created in God's 'image' (tselem) -- a royal term meaning humanity represents God's authority on earth. The Yahwist account (Genesis 2:4-25) is older, more anthropomorphic: God gets hands dirty forming adam (human) from adamah (ground), breathes into nostrils, plants a garden. The concern is not cosmic order but relationship -- between human and ground, human and animals, human and human.\n\nThe word 'rib' (tsela) in Genesis 2:21 actually means 'side' everywhere else it appears in the Hebrew Bible (it describes the side of the Ark of the Covenant, the side of a building). The image is not of woman as an afterthought made from a spare part, but of one being split into two complementary halves.\n\nThe Priestly account has clear parallels to Mesopotamian creation myths (Enuma Elish) -- but deliberately subverts them. In Enuma Elish, humans are created from the blood of a murdered god to be slaves. In Genesis 1, humans are the crown of creation, made in God's image. It is a theological manifesto disguised as cosmology.",
      advanced:
        "The canonical placement of these two accounts side by side represents a sophisticated editorial choice. Rather than harmonizing contradictory traditions into a single narrative (which would have been easy), the final editors preserved the tension. This editorial philosophy -- preserving multiple voices rather than imposing a single authoritative version -- characterizes the entire Torah and represents a fundamentally different approach to sacred text than, say, the Quran (understood as a single divine dictation) or the Book of Mormon (presented as a unified narrative).\n\nJon Levenson's 'Creation and the Persistence of Evil' argues that the Priestly creation account is not creation ex nihilo (from nothing) but creation as the ordering of pre-existing chaos. The tehom (deep) of Genesis 1:2 cognates with Tiamat, the chaos goddess of Enuma Elish. God does not eliminate chaos but contains and structures it -- and the threat of chaos returning (flood, exile) drives the entire biblical narrative.\n\nPhyllis Trible's feminist reading of Genesis 2-3 ('God and the Rhetoric of Sexuality') argues that ha-adam in Genesis 2 is not 'the man' but 'the earth creature' -- an undifferentiated human who only becomes gendered when split into ish (man) and ishshah (woman). Gender, in this reading, is not a creation ordinance but emerges from differentiation within an original unity."
    },
  },

  {
    id: "c1-06",
    slug: "prophetic-tradition",
    domainId: "d1",
    name: "The Prophetic Tradition: Speaking Truth to Power",
    summary:
      "Biblical prophets were not fortune-tellers. They were social critics who confronted kings, priests, and wealthy elites on behalf of the marginalized.",
    lensTags: ["academic", "protestant", "liberation"],
    relatedConceptSlugs: ["wisdom-literature", "torah-overview"],
    relatedTextRefs: ["Amos 5:21-24", "Isaiah 1:11-17", "Micah 6:8"],
    layers: {
      accessible:
        "When modern people hear 'prophet,' they think 'predicting the future.' The Hebrew word navi means something closer to 'spokesperson' or 'one who is called.' Prophets were people who claimed to speak for God -- and what God had to say was usually uncomfortable. Amos was a shepherd who walked into the royal sanctuary and told the king his worship was disgusting because he was exploiting the poor. Isaiah told the temple establishment that God was sick of their sacrifices because they ignored justice. Micah summarized the entire prophetic message: 'What does the LORD require? To do justice, love mercy, and walk humbly with your God.' The prophets were not mystic seers. They were social activists who believed God cared more about how you treated the vulnerable than how many animals you burned on an altar.",
      intermediate:
        "The prophetic books fall into three major periods: Pre-exilic prophets (Amos, Hosea, Isaiah 1-39, Micah, Zephaniah, Jeremiah) warned Israel and Judah that injustice would lead to national catastrophe. Exilic prophets (Ezekiel, Isaiah 40-55 / 'Second Isaiah') spoke to the community in Babylonian exile, offering both judgment and hope. Post-exilic prophets (Haggai, Zechariah, Malachi, Isaiah 56-66 / 'Third Isaiah') addressed the community rebuilding in the land.\n\nThe prophets introduced a revolutionary ethical monotheism. Prior to the prophetic movement, Israelite religion was largely ritual-focused (like other Ancient Near Eastern religions). The prophets reframed religion as fundamentally ethical. Amos 5:21-24: 'I hate, I despise your festivals... But let justice roll down like waters.' This is a radical claim: the God of Israel would rather have no worship at all than worship from people who exploit the poor.\n\nThe 'Servant Songs' of Isaiah 40-55 (Isaiah 42:1-4, 49:1-6, 50:4-9, 52:13-53:12) describe a mysterious 'Servant of the LORD' who suffers on behalf of others. Christians read these as predictions of Jesus. Jews read them as referring to Israel itself, or to the prophet. The text supports both readings and resists being reduced to either one.\n\nKey insight: prophetic 'prediction' (Hebrew: nevi'ah) is not crystal-ball fortune-telling. It is pattern recognition -- 'if you continue this trajectory of injustice, this is where it leads.' Much of what looks like 'fulfilled prophecy' is actually retrospective application: communities experiencing catastrophe looked back at prophetic warnings and recognized their situation.",
      advanced:
        "Abraham Heschel's 'The Prophets' remains the defining study. Heschel argues that the prophets experienced 'the pathos of God' -- the divine emotional response to human suffering and injustice. This is theologically radical: God is not the unmoved mover of Greek philosophy but a God who grieves, rages, and loves with fierce intensity. The prophet's emotional extremity (Jeremiah's tears, Hosea's broken marriage, Ezekiel's bizarre enacted parables) reflects not mental illness but participation in divine pathos.\n\nWalter Brueggemann's work on the 'prophetic imagination' identifies two prophetic modes: criticizing (naming what is wrong with the dominant order) and energizing (articulating an alternative vision). This framework has been enormously influential in liberation theology, which reads the prophets as paradigms for confronting systemic injustice today.\n\nThe question of how 'the prophets' became 'the prophetic books' involves complex redaction history. Many prophetic books show clear evidence of multiple editorial layers added over centuries. Isaiah, for example, spans at least 200 years of composition (chapters 1-39, 40-55, 56-66 from different periods). The books as we have them are not transcripts of prophetic speeches but theological anthologies curated by communities of disciples."
    },
  },

  {
    id: "c1-07",
    slug: "psalms-as-practice",
    domainId: "d1",
    name: "The Psalms: Ancient Prayer as Raw Honesty",
    summary:
      "The Psalms are not polite prayers. They contain rage, doubt, despair, and demands that God explain Himself.",
    lensTags: ["academic", "contemplative", "pastoral"],
    relatedConceptSlugs: ["wisdom-literature", "grief-lament-psalms", "lectio-divina"],
    relatedTextRefs: ["Psalm 22", "Psalm 88", "Psalm 137"],
    layers: {
      accessible:
        "The Psalms are the prayer book of ancient Israel, and they include prayers that most modern congregations would never say out loud. Psalm 88 ends in darkness with no resolution: 'You have taken my companions from me; darkness is my closest friend.' No hope. No praise. Just despair. Psalm 137 includes a wish for the babies of Babylon to be dashed against rocks. Psalm 22 opens with the words Jesus screamed from the cross: 'My God, my God, why have you forsaken me?' These are not neat, reverent prayers. They are the full range of human emotion -- rage, grief, doubt, terror, ecstasy, boredom, gratitude -- directed at God without filter. The Psalms assume that honest relationship with God includes anger and confusion, not just gratitude and praise.",
      intermediate:
        "The Psalms are categorized by scholars into several genres (Gattungen, following Hermann Gunkel): Hymns of praise (e.g., Psalms 8, 19, 104), Laments (individual: 3, 22, 88; communal: 44, 74, 137), Royal psalms (2, 72, 110), Thanksgiving psalms (30, 34, 116), Wisdom psalms (1, 37, 73), and Pilgrimage songs (120-134). The single largest category is lament -- roughly one-third of all Psalms.\n\nThe lament structure follows a pattern: (1) address to God, (2) complaint about the situation, (3) confession of trust, (4) petition for help, (5) vow of praise. Most laments move from despair to hope. But Psalm 88 is unique -- it is the only psalm that does not resolve. It ends in darkness. Its inclusion in the canon is theologically significant: the tradition says that sometimes there is no resolution, and that this experience is still valid prayer.\n\nThe superscriptions ('A psalm of David,' 'For the director of music, according to...') are later editorial additions, not original. When a psalm says 'of David' (le-David), the Hebrew preposition le can mean 'by David,' 'for David,' 'about David,' or simply 'in the Davidic tradition.' The historical David may have composed some psalms, but the Psalter as a whole was compiled over centuries.\n\nWalter Brueggemann's three-category framework is helpful: Psalms of Orientation (life is good, God is in control), Psalms of Disorientation (everything has fallen apart), and Psalms of New Orientation (a new, more mature wholeness after suffering). Most churches only sing Orientation psalms, which is why people feel guilty when they are in Disorientation -- the church has trained them to think that doubt and anger are not legitimate prayers.",
      advanced:
        "The Psalter as a book has an intentional editorial structure. Books I-III (Psalms 1-89) trend toward lament, with Book III ending at Psalm 89 -- a devastating psalm about the apparent failure of God's covenant with David. Books IV-V (90-150) respond with psalms of trust in God's kingship regardless of political circumstances. The overall movement from lament to praise mirrors Israel's journey from monarchy to exile to restoration.\n\nGerald Wilson's 'The Editing of the Hebrew Psalter' was groundbreaking in demonstrating this editorial intentionality. The 'seams' between the five books of the Psalter (marked by doxologies at Psalms 41, 72, 89, 106) create a theological narrative about the failure of human kingship and the enduring kingship of God.\n\nThe imprecatory psalms (those calling for violence against enemies, like 109 and 137) remain the most difficult for modern readers. Historical approaches include: allegorizing (the 'enemies' are spiritual, not physical), contextualizing (these are the prayers of colonized peoples under imperial oppression), and psychological (expressing rage in prayer prevents acting it out). Erich Zenger argues that the imprecatory psalms are acts of faith: rather than taking revenge, the psalmist leaves vengeance to God. The most honest approach may be: these prayers are ugly, they are human, and the tradition preserved them rather than censoring them."
    },
  },

  {
    id: "c1-08",
    slug: "exile-and-identity",
    domainId: "d1",
    name: "The Babylonian Exile: How Catastrophe Created Judaism",
    summary:
      "The destruction of Jerusalem in 586 BCE transformed a local temple cult into a portable, text-based religion that could survive anywhere.",
    lensTags: ["academic", "protestant"],
    relatedConceptSlugs: ["documentary-hypothesis", "second-temple-judaism"],
    relatedTextRefs: ["Psalm 137", "Isaiah 40:1-11", "Ezekiel 37"],
    layers: {
      accessible:
        "In 586 BCE, the Babylonian Empire destroyed Jerusalem, burned Solomon's Temple to the ground, and deported the Judean elite to Babylon. This was supposed to be the end. Everything Israelite religion depended on -- the Temple, the holy city, the Davidic king, the land promised to Abraham -- was gone. Instead, it was a beginning. In exile, the Judean community was forced to ask: can we worship God without a temple? Can we be God's people without a land? The answer was yes, but it required reinvention. The Torah was likely compiled in its final form during this period. Synagogue worship (study and prayer rather than sacrifice) emerged. Sabbath observance, dietary laws, and circumcision became identity markers that could be practiced anywhere. The Babylonian Exile did not destroy Israelite religion -- it forged Judaism.",
      intermediate:
        "The exile was the crucible that produced many of the biblical texts we have. Second Isaiah (chapters 40-55) was written during the exile as a message of hope. The Priestly source (P) of the Torah likely took shape in exile, with its emphasis on holiness, purity, and ritual order -- maintaining identity in a foreign land. Ezekiel's vision of dry bones coming to life (Ezekiel 37) directly addresses the exilic question: can these dead bones live? The answer: God can restore even from total destruction.\n\nThe theological crisis was acute. Deuteronomistic theology (which shaped Joshua through 2 Kings) had taught that faithfulness to God meant national prosperity. The exile shattered this equation. Either God had failed, or the theology was wrong, or Israel had sinned so deeply that punishment was justified. The Deuteronomistic History (Joshua-2 Kings) was edited during the exile to make the third argument: the exile was the consequence of centuries of unfaithfulness. But this left a problem -- is there hope beyond punishment?\n\nThe concept of monotheism crystallized during the exile. Earlier Israelite religion was henotheistic (worshiping YHWH while acknowledging other gods existed). Second Isaiah makes the strongest monotheistic claims in the Bible: 'I am the LORD, and there is no other; apart from me there is no God' (Isaiah 45:5). This was likely influenced by contact with Zoroastrianism and the need to assert YHWH's universal sovereignty even in a land where Marduk's temples were everywhere.",
      advanced:
        "The exile as historiographic event has been significantly nuanced by archaeology. Oded Lipschits and others have shown that the deportation affected primarily the elite of Jerusalem -- the majority of the population remained in Judah. The 'myth of the empty land' (the idea that Judah was completely depopulated) was a later ideological construction by the returning exiles to justify their claims to the land over against those who had remained.\n\nDaniel Smith-Christopher's work on trauma theory and the exile ('A Biblical Theology of Exile') applies modern understandings of collective trauma, diaspora psychology, and resistance literature to the exilic texts. The repetitive assurances of Second Isaiah ('Do not fear,' 'I am with you') read differently when understood as addressing a traumatized, displaced community.\n\nThe return from exile (538 BCE, under Persian sponsorship) did not restore the pre-exilic order. The Second Temple was a disappointment compared to Solomon's (Haggai 2:3). There was no restored Davidic king. The community was a Persian province, not a sovereign nation. This gap between promise and reality generated the apocalyptic imagination that would shape both late Second Temple Judaism and early Christianity: if God's kingdom has not come in history, perhaps it will come at the end of history."
    },
  },

  {
    id: "c1-09",
    slug: "sophia-divine-wisdom",
    domainId: "d1",
    name: "Sophia / Divine Wisdom: The Feminine Face of God",
    summary:
      "Hokhmah in Hebrew, Sophia in Greek. The feminine personification of divine wisdom in Proverbs, Sirach, and the Wisdom of Solomon -- present at creation, co-creator with God, and the direct ancestor of the Logos theology in John 1.",
    lensTags: ["academic", "feminist", "catholic", "jewish"],
    relatedConceptSlugs: ["wisdom-literature", "documentary-hypothesis", "septuagint"],
    relatedTextRefs: ["Proverbs 8:22-31", "Sirach 24", "Wisdom of Solomon 7:22-8:1", "John 1:1-14"],
    honestAnalysis:
      "The suppression of Sophia in mainstream Christianity is not a conspiracy -- it is the result of theological decisions made under patriarchal cultural assumptions. The Logos theology of John 1 almost certainly draws on the Sophia tradition, yet the masculine Greek word Logos replaced the feminine Sophia without comment. Feminist theologians (Elisabeth Schussler Fiorenza, Elizabeth Johnson) have argued this substitution was theologically motivated, not simply linguistic. The resistance to recovering Sophia language in contemporary Christianity reveals how deeply male God-language has been naturalized. The tradition insists that God is beyond gender. But the complete erasure of feminine divine imagery is itself a gendered theological choice.",
    layers: {
      accessible:
        "In Proverbs 8, something remarkable happens. A figure called Wisdom speaks in the first person. She describes herself as present with God before the creation of the world: 'The LORD possessed me at the beginning of his work... When he established the heavens, I was there.' She is not a creation -- she is with the Creator. She is at God's side, 'like a master workman,' delighting in the inhabited world.\n\nIn Hebrew, the word for Wisdom is Hokhmah -- feminine. In Greek (the language of the Septuagint and most of the New Testament), it is Sophia -- also feminine. These are not metaphors for an abstract quality. They are a personification: Wisdom as a divine figure, feminine, present at creation, the one through whom God made the world.\n\nThis figure had enormous influence on early Christianity. The Prologue of John's Gospel ('In the beginning was the Logos... all things were made through him') is almost certainly built on the Sophia tradition of Proverbs 8 and the later Wisdom of Solomon. The structure is identical. The content is the same. The only difference: John uses the masculine Greek word Logos (Word) where the tradition had used the feminine Sophia (Wisdom).\n\nWhat happened to Sophia? She was absorbed into Christology -- and in the absorption, her feminine gender was erased. She became a him.",
      intermediate:
        "The Sophia tradition develops across several centuries and texts:\n\nProverbs 8 (possibly 10th-6th century BCE): The foundational text. Wisdom speaks as a personified divine figure present at creation. She is described with language that will later be applied to the Torah (in Rabbinic Judaism) and to Christ (in Christianity). Her 'delight' in the world suggests a joyful, relational divine presence.\n\nSirach 24 (c. 180 BCE): Wisdom speaks again, now identifying herself with the Torah: 'In the holy tabernacle I ministered before him, and so I was established in Zion.' Ben Sirach domesticates Sophia into the Jewish legal tradition -- she is not a separate divine being but the expression of Torah.\n\nWisdom of Solomon (c. 1st century BCE, Alexandria): The most developed Sophia Christology before Christianity. Wisdom is described as 'a breath of the power of God, and a pure emanation of the glory of the Almighty' (7:25). She is the divine agent through whom God interacts with the world: 'She pervades and penetrates all things' (7:24). She guided Israel in the wilderness (10:17). She is, functionally, what Christians would later call the Logos.\n\nThe transition to Logos theology: Philo of Alexandria (c. 20 BCE-50 CE) harmonized Jewish Wisdom theology with Greek philosophy. He used the masculine Greek term Logos (reason, word) as equivalent to Sophia. When John wrote his Prologue, he appears to draw on this Philonic tradition -- but the choice of masculine Logos over feminine Sophia was not inevitable. The Odes of Solomon (early 2nd century Christian hymns) use Sophia language about Christ. Some early Christians clearly preserved the feminine tradition.",
      advanced:
        "The scholarly debate on the relationship between Sophia and Logos has been one of the most productive in recent biblical studies. Elisabeth Schussler Fiorenza's 'Jesus: Miriam's Child, Sophia's Prophet' argues that the earliest Christologies were Sophia Christologies -- Jesus was understood as the prophet and child of Sophia, sent to call the people back to Wisdom's table. The masculine Logos Christology of John represents a second-generation development that overwrites this earlier tradition.\n\nElizabeth Johnson ('She Who Is') develops a systematic theology based on the Sophia tradition, arguing that the Trinity can be articulated through the categories of Spirit-Sophia, Jesus-Sophia, and Mother-Sophia without theological distortion. Her work drew official criticism from the United States Conference of Catholic Bishops in 2011, illustrating how live this issue remains.\n\nThe gendered language of the Hebrew text is directly relevant. Hebrew is a grammatically gendered language, and Hokhmah is grammatically and culturally feminine. The parallel figure Folly (kesil, or the 'strange woman' of Proverbs 5-7) is also feminine. The two feminine figures -- Wisdom and Folly -- form a pair in the literary structure of Proverbs, inviting humanity to choose between them. This is not incidental to the text's meaning; it is the rhetorical structure.\n\nThe ruach (Spirit/wind) of Genesis 1:2 is also grammatically feminine in Hebrew. This creates a pattern: several of the most significant divine figures or attributes in the Hebrew Bible are grammatically feminine -- Hokhmah (Wisdom), Ruach (Spirit), Shekinah (God's dwelling presence, in Rabbinic literature). The Christian tradition's translation into Greek and then Latin erased most of this gender complexity. Understanding the Hebrew origins recovers a dimension of the tradition that mainstream Christianity has largely suppressed."
    },
  },
];
