import type { Concept } from "./types";

export const domain10Concepts: Concept[] = [
  {
    id: "c10-01",
    slug: "dead-sea-scrolls",
    domainId: "d10",
    name: "The Dead Sea Scrolls",
    summary:
      "Discovered in 1947 in caves near Qumran, these 2,000-year-old manuscripts revolutionized our understanding of Second Temple Judaism and the text of the Hebrew Bible.",
    lensTags: ["academic", "jewish", "protestant", "catholic"],
    relatedConceptSlugs: ["textual-criticism", "second-temple-judaism", "biblical-hebrew"],
    relatedTextRefs: ["Isaiah 53", "Daniel 7", "Habakkuk 2:4"],
    layers: {
      accessible:
        "In 1947, a Bedouin shepherd threw a rock into a cave near the Dead Sea and heard something shatter. Inside were clay jars containing ancient scrolls. Over the next decade, eleven caves near Qumran yielded roughly 900 manuscripts dating from 250 BCE to 70 CE -- the greatest archaeological discovery of the 20th century. The scrolls include the oldest known copies of almost every book of the Hebrew Bible (a thousand years older than previously known manuscripts), alongside previously unknown texts: community rules, hymns, apocalyptic visions, and biblical commentaries. They reveal a Jewish sect (likely the Essenes) that had withdrawn from mainstream Temple worship, practiced communal living, and expected an imminent cosmic battle between the 'Sons of Light' and the 'Sons of Darkness.'",
      intermediate:
        "The scrolls' impact on biblical studies is threefold. First, textual: the Great Isaiah Scroll (1QIsa-a) is remarkably close to the Masoretic Text written a thousand years later, confirming careful transmission -- but also reveals variants, showing the text was not frozen. Some scrolls are closer to the Septuagint (Greek translation) than to the MT, proving multiple Hebrew text traditions co-existed.\n\nSecond, contextual: the scrolls reveal the diversity of Second Temple Judaism. The 'Community Rule' (1QS) describes a sect with strict initiation, communal meals, ritual purity obsession, and a 'Teacher of Righteousness' in conflict with a 'Wicked Priest.' The 'War Scroll' (1QM) envisions a final apocalyptic battle. The 'Temple Scroll' (11QT) imagines an ideal Temple that the sect believed the current one failed to be.\n\nThird, interpretive: the scrolls' use of 'pesher' (interpretation that applies ancient texts to the community's current situation) parallels how the New Testament authors read the Hebrew Bible. When Matthew says a particular event 'fulfilled' a prophecy, he is using the same interpretive method the Qumran community used -- reading Scripture as speaking directly to the present.\n\nThe scrolls also contain texts that illuminate New Testament concepts: the 'Son of God' text (4Q246), the 'Messianic Apocalypse' (4Q521) describing the messiah healing the blind and raising the dead, and the 'Melchizedek Scroll' (11Q13) portraying Melchizedek as a heavenly deliverer (compare Hebrews 7).",
      advanced:
        "The publication history of the scrolls is itself a story of academic politics and institutional failure. From 1953 to 1991, a small team controlled by Roland de Vaux and later John Strugnell monopolized access, publishing fragments at glacial pace. The 1991 'liberation' of the scrolls (through unauthorized photographs and a computer-reconstructed concordance) opened the texts to all scholars and dramatically accelerated research.\n\nThe 'Qumran-Essene hypothesis' (that the scrolls were produced by an Essene community at Qumran) was long treated as established fact but has been challenged. Norman Golb argued the scrolls were a Jerusalem library hidden during the First Jewish Revolt. Jodi Magness's archaeological work supports the Essene connection but with a more nuanced understanding of the site. Recent DNA analysis of scroll parchments has shown that some scrolls were made from animal skins not available locally, confirming that at least some scrolls were brought from elsewhere.\n\nFor biblical studies, the scrolls' most significant contribution may be methodological: they demonstrate that 'the Bible' was not a fixed collection in the Second Temple period. The number and order of Psalms varies. Jeremiah exists in two different lengths. Some texts (Jubilees, 1 Enoch, Temple Scroll) seem to have had scriptural authority for the Qumran community but were not included in the later Jewish canon. The concept of a closed, fixed canon is a post-destruction development -- before 70 CE, 'Scripture' was more fluid than any later tradition acknowledges."
    },
    honestAnalysis:
      "Early sensationalist claims (the scrolls prove/disprove Christianity, the scrolls contain secret gospels, the Vatican suppressed the scrolls) are all false. The scrolls are Jewish, not Christian, texts. They illuminate the world Christianity emerged from without directly mentioning Jesus, John the Baptist, or any New Testament figure.",
  },

  {
    id: "c10-02",
    slug: "ancient-near-east",
    domainId: "d10",
    name: "Ancient Near Eastern Context",
    summary:
      "The Mesopotamian, Egyptian, Canaanite, and Hittite worlds that surrounded ancient Israel and profoundly shaped the biblical text -- from creation myths to law codes to covenant forms.",
    lensTags: ["academic"],
    relatedConceptSlugs: ["documentary-hypothesis", "dead-sea-scrolls"],
    relatedTextRefs: ["Genesis 1-2", "Psalm 29", "Proverbs 22:17-24:22"],
    layers: {
      accessible:
        "The biblical authors did not write in a vacuum. They lived surrounded by powerful civilizations with their own creation stories, flood narratives, law codes, and temple rituals. When you place the Bible alongside these texts, the similarities are striking -- and the differences are theologically revolutionary. The Babylonian creation epic (Enuma Elish) tells of the god Marduk creating the world by killing the chaos monster Tiamat and fashioning humans from the blood of a slain god. Genesis 1 uses similar imagery (chaos waters, divine speech) but radically demythologizes it: there is one God, creation is orderly and good, and humans are made in God's image rather than as slaves. The biblical authors were not copying; they were responding -- telling a counter-story that subverted the dominant narratives of their world.",
      intermediate:
        "Key parallels and differences:\n\n1. Flood narratives: The Gilgamesh Epic (Tablet XI) contains a flood story with a boat, animals, birds sent out, and a sacrifice afterward -- remarkably similar to Genesis 6-9. The Atrahasis Epic adds a reason (human noise disturbing the gods) absent from Genesis. The biblical version transforms the story: one God (not many), a moral reason for the flood (human wickedness, not divine annoyance), and a covenantal promise never to flood again.\n\n2. Law codes: The Code of Hammurabi (c. 1750 BCE) predates Mosaic law by centuries and shares many specific laws (eye for an eye, ox goring regulations). But the biblical law codes differ in crucial ways: biblical law applies the same standards to rich and poor (Hammurabi's penalties vary by social class), and biblical law grounds justice in God's character rather than royal authority.\n\n3. Covenant forms: George Mendenhall demonstrated that the structure of Deuteronomy follows the pattern of Hittite suzerainty treaties (preamble, historical prologue, stipulations, blessings/curses, witnesses). Israel understood its relationship with God through a political metaphor borrowed from international diplomacy.\n\n4. Psalms: Psalm 29 appears to be a Canaanite hymn to Baal, repurposed for Yahweh. Psalm 104 closely parallels the Egyptian Hymn to Aten. This is not plagiarism but theological appropriation -- claiming that what the nations attribute to their gods actually belongs to Yahweh.",
      advanced:
        "The comparative method in biblical studies has moved through three phases. The 'pan-Babylonianism' of the early 20th century (Friedrich Delitzsch's 'Babel und Bibel' lectures) claimed the Bible was derivative of Mesopotamian sources, provoking a defensive reaction. The 'Albright school' (mid-20th century) used archaeology to defend biblical historicity. Current scholarship avoids both extremes: the biblical texts participate in a shared cultural world while making distinctive theological claims within it.\n\nThe most significant recent development is the recognition that Israelite religion was originally polytheistic or at minimum henotheistic (worshiping one god while acknowledging others' existence). Archaeological evidence (Kuntillet Ajrud inscriptions mentioning 'Yahweh and his Asherah,' goddess figurines found throughout Judean sites) and biblical evidence (Psalm 82: 'God stands in the divine council; among the gods he renders judgment') both support this. Strict monotheism -- the claim that only one God exists -- is a development of the exilic and post-exilic period (Isaiah 40-55).\n\nMark Smith ('The Early History of God,' 'The Origins of Biblical Monotheism') traces how Yahweh absorbed the attributes of El (the chief Canaanite deity) and Baal (the storm god), and how the worship of Asherah (consort goddess) was gradually suppressed. This process is visible within the biblical text itself -- the Deuteronomistic historians condemn what earlier texts accept. The Bible preserves the evidence of its own theological evolution."
    },
    honestAnalysis:
      "Ancient Near Eastern parallels do not prove the Bible is 'copied from pagans.' They demonstrate that the biblical authors were embedded in their cultural world and made their theological claims in dialogue with it. The parallels make the differences more, not less, significant.",
  },

  {
    id: "c10-03",
    slug: "archaeology-and-exodus",
    domainId: "d10",
    name: "Archaeology and the Exodus: Did It Happen?",
    summary:
      "The foundational story of the Hebrew Bible -- escape from Egypt, wandering in the desert, conquest of Canaan -- has almost no archaeological evidence. What does that mean?",
    lensTags: ["academic", "jewish"],
    relatedConceptSlugs: ["documentary-hypothesis", "ancient-near-east"],
    relatedTextRefs: ["Exodus 12-14", "Joshua 6"],
    layers: {
      accessible:
        "The Exodus -- Israelites enslaved in Egypt, ten plagues, parting of the Red Sea, forty years in the desert, conquest of Canaan -- is the defining story of the Hebrew Bible. Everything in Jewish identity and theology depends on it. But here is the uncomfortable archaeological reality: there is no Egyptian record of a mass Israelite enslavement or departure. There is no evidence of two million people wandering the Sinai desert for forty years (that many people would leave massive archaeological traces). The cities supposedly conquered by Joshua (Jericho, Ai) either did not exist at the traditional date of the conquest or show no evidence of destruction. This does not mean the Exodus did not happen. It means it almost certainly did not happen in the way the Bible describes it.",
      intermediate:
        "The archaeological evidence breaks down as follows: Egyptian records from the 13th century BCE (the most commonly proposed date for the Exodus) mention 'Apiru' -- possibly a cognate of 'Hebrew' -- as troublesome laborers and semi-nomads, but not as a nation held in slavery. The Merneptah Stele (ca. 1208 BCE) is the earliest reference to 'Israel' outside the Bible, mentioning it as a people in Canaan -- but not as recent arrivals from Egypt. The Sinai desert has been extensively surveyed and shows no signs of a large population during the relevant period.\n\nThe conquest model (Joshua's military campaign) has largely been abandoned by archaeologists. Israel Finkelstein and Neil Asher Silberman ('The Bible Unearthed') argue that the Israelites emerged gradually from the indigenous Canaanite population -- they did not invade from outside. Settlement patterns in the central highlands of Canaan show a proliferation of small villages around 1200 BCE, but these villages show cultural continuity with Canaan, not a break from it.\n\nSeveral alternative models exist: (1) a small group of escaped slaves from Egypt whose story was later expanded to represent all Israel; (2) a series of migrations and revolts over centuries, compressed into a single narrative; (3) a foundation myth that encoded real experiences of oppression and liberation but not a single historical event. Each has strengths and weaknesses.\n\nFor the faithful reader: the question is not whether the Exodus happened exactly as described but whether the theological truth it carries -- that God liberates the oppressed -- depends on historical literalism. Most critical scholars (including many who are devout) argue that it does not.",
      advanced:
        "The scholarly debate has shifted from 'did the Exodus happen?' to 'what kind of event might lie behind the narrative?' William Dever ('Who Were the Early Israelites and Where Did They Come From?') argues for a 'mixed multitude' model: some ancestors of Israel may have come from Egypt, while others were indigenous Canaanites, Midianites, or displaced peoples from the Late Bronze Age collapse. The narrative was composed centuries later to give a unified origin story to what was originally a diverse confederation.\n\nThe 'minimalist' school (Thomas Thompson, Philip Davies, Niels Peter Lemche) argues that the biblical narrative is a literary creation of the Persian or Hellenistic period with minimal historical content. The 'maximalist' school (Kenneth Kitchen, James Hoffmeier) defends a substantially historical Exodus, pointing to Egyptian elements in the narrative (names, customs, geography) that would be unlikely inventions. Most scholars fall between these positions.\n\nThe theological stakes: liberation theology (Gustavo Gutierrez, James Cone) reads the Exodus as God's definitive identification with the oppressed. If the Exodus is 'just a story,' does it lose its liberating power? The mature theological answer is no: the Exodus functions as scripture not because it is a newspaper report but because it embodies a truth about reality -- that oppression is not God's will and that liberation is possible. The story creates the community that reads it, and the community that reads it continues to experience liberation. This is what 'inspired' means: not dictated by God but bearing God's truth through human literary craft."
    },
  },

  {
    id: "c10-04",
    slug: "crucifixion-archaeology",
    domainId: "d10",
    name: "Crucifixion: What Archaeology Tells Us",
    summary:
      "Only one crucified body has ever been found by archaeologists. What we know about how crucifixion actually worked changes how we read the Gospels.",
    lensTags: ["academic"],
    relatedConceptSlugs: ["dead-sea-scrolls", "ancient-near-east", "historical-jesus"],
    relatedTextRefs: ["Mark 15:21-41", "John 19:31-37", "Psalm 22"],
    layers: {
      accessible:
        "In 1968, archaeologists in Jerusalem found the bones of a man named Yehohanan ben Hagkol who had been crucified in the first century. A large iron nail was still driven through his heel bone. This is the only archaeological evidence of crucifixion ever recovered -- remarkable given that Rome crucified thousands. The reason we have so little physical evidence: crucified victims were usually thrown into mass graves, and the nails (iron, valuable) were typically pulled out and reused. Yehohanan's family was wealthy enough to reclaim his body for burial, and the nail was bent during extraction, so it stayed.\n\nWhat Yehohanan's remains tell us: his arms were probably tied (not nailed) to the crossbeam; the nail through his heel was driven sideways through both heels together; his legs were broken (matching John 19:31-33). This picture differs from traditional Christian art, which typically shows nails through the palms.",
      intermediate:
        "Roman crucifixion was designed to maximize suffering and public humiliation. The victim typically carried the horizontal crossbeam (patibulum) to the site of execution, not the entire cross. They were stripped naked (the Gospels' mention of soldiers casting lots for Jesus' clothing reflects standard practice). The cause of death was not blood loss but a combination of exposure, exhaustion, dehydration, and asphyxiation -- the victim's body weight made breathing increasingly difficult, forcing them to push up on the nails to inhale. This is why the legs were sometimes broken (crurifragium): it prevented pushing up, accelerating death.\n\nThe Shroud of Turin, claimed by some to be Jesus' burial cloth, has been carbon-dated to 1260-1390 CE (a medieval origin). However, the debate continues because the image formation mechanism has never been reproduced. Whether or not the Shroud is authentic, its detailed depiction of crucifixion wounds is consistent with what we know archaeologically: wounds on the wrists (not palms), scourging marks, puncture wounds on the scalp, and a side wound.\n\nJoe Zias and others have reconstructed the mechanics of crucifixion based on skeletal evidence, Roman texts (Seneca, Josephus), and experimental archaeology. The conventional Christian image (arms stretched wide, nails through palms) may be partially artistic convention. Wrist nailing is more likely (the palms cannot support body weight), and various positions were used. Josephus reports that during the siege of Jerusalem (70 CE), Roman soldiers crucified so many people that 'there was not enough room for the crosses, and not enough crosses for the bodies.'",
      advanced:
        "John Dominic Crossan's work on the archaeology of Jesus' burial raises uncomfortable questions. In 'Who Killed Jesus?' and 'Jesus: A Revolutionary Biography,' Crossan argues that crucified criminals were typically left on the cross for scavengers or thrown into common graves -- not given honorable burial. The Gospel accounts of Joseph of Arimathea requesting and receiving Jesus' body may reflect later apologetic theology rather than historical fact. This is contested by scholars like Jodi Magness ('Stone and Dung, Oil and Spit'), who argues that Jewish burial practices, even for criminals, differed from standard Roman practice in Palestine.\n\nThe discovery of the Caiaphas ossuary (1990) provides indirect archaeological evidence for the passion narrative. An ornate limestone ossuary inscribed 'Joseph son of Caiaphas' was found in a first-century tomb south of Jerusalem, likely belonging to the high priest who according to the Gospels played a central role in Jesus' trial. This does not confirm the Gospel narrative but confirms the historical existence of a key figure in it."
    },
  },

  {
    id: "c10-05",
    slug: "temple-mount",
    domainId: "d10",
    name: "The Temple Mount: The Most Contested Site on Earth",
    summary:
      "A 37-acre platform in Jerusalem that three religions claim. What actually stood there, and why it still matters.",
    lensTags: ["academic", "interfaith"],
    relatedConceptSlugs: ["second-temple-judaism", "dead-sea-scrolls", "exile-and-identity"],
    relatedTextRefs: ["1 Kings 6-8", "Mark 13:1-2", "Revelation 21:22"],
    layers: {
      accessible:
        "The Temple Mount (Hebrew: Har HaBayit; Arabic: Haram al-Sharif) is a flat platform in the Old City of Jerusalem that is sacred to Judaism, Christianity, and Islam. For Jews, it is the site of Solomon's Temple (10th century BCE) and the Second Temple (rebuilt 516 BCE, expanded by Herod the Great, destroyed by Rome in 70 CE). For Muslims, it is where Muhammad ascended to heaven on his Night Journey (Isra and Mi'raj), marked by the Dome of the Rock (built 691 CE) and the Al-Aqsa Mosque. For Christians, it is where Jesus taught, overturned tables, and predicted the Temple's destruction. Today, the site is administered by the Islamic Waqf (trust) under Jordanian custodianship, while Israeli police control access. Jews can visit but (by agreement with the Chief Rabbinate) traditionally do not pray there. It is the geopolitical and spiritual center of the Israeli-Palestinian conflict.",
      intermediate:
        "The archaeological significance of the Temple Mount is immense but largely inaccessible -- no systematic excavation has ever been conducted on the platform itself due to religious and political sensitivities. What we know comes from: literary sources (the Bible, Josephus, Mishnah), excavations around the periphery (Benjamin Mazar's excavations south of the Mount, 1968-1978), the Temple Mount Sifting Project (examining earth illegally removed by the Waqf in 1999), and comparative architectural analysis.\n\nHerod's expansion of the Temple Mount (20-19 BCE) was one of the largest construction projects in the ancient world. He doubled the size of the platform using massive retaining walls (the Western Wall is part of this retaining wall, not the Temple itself). The stones in the lower courses weigh hundreds of tons. Josephus described the Temple as so magnificent that 'the outward face of it was a just spectacle, being covered all over with plates of gold, reflecting the sun's rays in a blinding blaze.'\n\nThe destruction of the Temple in 70 CE was the defining catastrophe of Jewish history. It eliminated the sacrificial system, the priesthood, and the geographical center of Jewish worship. Rabbinic Judaism emerged from this crisis, replacing sacrifice with prayer, priesthood with rabbinic authority, and the Temple with the synagogue and Torah study. Christianity interpreted the destruction theologically: the Temple was no longer needed because Christ was the new temple, the final sacrifice.",
      advanced:
        "The Temple Mount's archaeological inaccessibility means many fundamental questions remain unanswered. The exact location of the Holy of Holies is debated (Leen Ritmeyer's reconstruction places it near the Dome of the Rock; Asher Kaufman proposed a location further north). The extent of Herodian construction versus earlier building is unclear. The relationship between the current Haram platform and the original pre-Herodian Temple Mount is disputed.\n\nGabriel Barkay's Temple Mount Sifting Project, which examines earth dumped by the Waqf during construction of an underground mosque, has yielded thousands of artifacts from all periods -- First Temple, Second Temple, Roman, Byzantine, Crusader, and Ottoman. This is the closest thing to systematic archaeological study the site has received, though the material is out of context (secondary deposition), limiting what can be concluded.\n\nThe political theology of the Temple Mount remains explosive. Jewish messianic movements (Temple Institute, Temple Mount Faithful) seek to rebuild a Third Temple -- which would require removing or displacing the Islamic structures. Israeli government policy prohibits this. For Christian eschatology, the Temple's fate is connected to end-times scenarios (some evangelicals support Jewish claims to the Mount as a step toward the Second Coming). For Palestinians, the Mount represents not just religious heritage but national identity and resistance to occupation. No archaeological or historical question about this site is purely academic."
    },
  },
];
