import type { Concept } from "./types";

export const domain11Concepts: Concept[] = [
  {
    id: "c11-01",
    slug: "hermeneutical-frameworks",
    domainId: "d11",
    name: "Hermeneutical Frameworks: How You Read Changes What You Find",
    summary:
      "The major approaches to biblical interpretation -- allegorical, historical-critical, literary, liberation, feminist -- and why choosing a method is never neutral.",
    lensTags: ["academic", "protestant", "catholic", "orthodox"],
    relatedConceptSlugs: ["reformation", "textual-criticism"],
    relatedTextRefs: ["Galatians 4:21-31", "2 Timothy 3:16", "John 20:31"],
    layers: {
      accessible:
        "Everyone interprets the Bible. The question is not whether you use a method but whether you are aware of the one you are using. The major approaches include: Literal/Historical (what did the author intend for the original audience?), Allegorical (the text has hidden spiritual meanings beyond the surface -- favored by the early church), Moral (what does this text teach us about how to live?), and Anagogical (what does this text tell us about ultimate things?). These four were codified in the medieval 'Quadriga' -- four senses of Scripture. Modern approaches add Historical-Critical (using archaeology, linguistics, and source analysis to reconstruct what actually happened), Literary (reading the Bible as literature with attention to narrative, poetry, and genre), Liberation (reading from the perspective of the poor and marginalized), and Feminist (attending to women's voices, suppression, and agency in the text).",
      intermediate:
        "The Reformation produced a hermeneutical revolution. Luther rejected the allegorical method that had dominated for over a thousand years, insisting on the 'plain sense' (sensus literalis) of Scripture. But Luther's 'plain sense' was not fundamentalist literalism -- he was perfectly willing to say that James was 'an epistle of straw' because it seemed to contradict Paul on justification. Luther's hermeneutic was Christological: the Bible should be read through the lens of Christ, and any interpretation that does not 'promote Christ' is suspect.\n\nThe Historical-Critical Method (18th-19th centuries) applied Enlightenment rationality to the Bible, asking: Who actually wrote this? When? What sources did they use? What really happened? This produced the Documentary Hypothesis, the Synoptic Problem, and form criticism. Its great strength is honesty about the text's human origins. Its great weakness is that it can reduce the Bible to a historical artifact, draining it of the theological power that makes people read it in the first place.\n\nReader-response criticism (Hans-Georg Gadamer, Paul Ricoeur) argues that meaning is not located solely in the author's intention or the text's structure but in the encounter between text and reader. A text's meaning is never exhausted by a single reading. This validates multiple interpretive communities reading the same text differently -- not because truth is relative but because texts are richer than any single reading can capture.\n\nLiberation hermeneutics (Gustavo Gutierrez, James Cone) insists that the Bible must be read from the perspective of the oppressed, because that is the perspective from which it was largely written. The Exodus is not an abstract theological metaphor but a concrete story of slaves being liberated. Any reading that comforts the powerful while ignoring the suffering of the poor is a distortion.",
      advanced:
        "The current hermeneutical landscape is deeply fractured. Evangelical hermeneutics (grammatical-historical method) claims to let the text speak for itself but operates with unexamined assumptions: that the Bible is a unified message, that apparent contradictions are resolvable, and that the original author's intention is the meaning. Post-structural hermeneutics (Derrida, applied to biblical studies by Stephen Moore and Yvonne Sherwood) questions whether 'the author's intention' is a coherent concept and whether texts have stable meanings at all.\n\nKevin Vanhoozer ('Is There a Meaning in This Text?') attempts a middle position using speech-act theory: the biblical text does things (promises, commands, narrates, warns) and the meaning is the communicative action, not just the propositional content. This allows for authorial intention without naive literalism.\n\nThe most practically important hermeneutical question today: how do communities decide which biblical commands are culturally conditioned and which are universal? The same communities that dismiss Levitical purity laws as culturally bound often treat Levitical sexual ethics as timeless. The same interpreters who read Paul's household codes (wives submit) as culturally limited read Paul's justification theology as universal. There is no purely objective method for making this distinction -- it always involves theological and ethical commitments that precede the act of reading. Honest hermeneutics acknowledges this rather than pretending to pure objectivity."
    },
    honestAnalysis:
      "No one reads the Bible without a method, and no method is neutral. The choice of hermeneutic determines what you find before you start reading. The most honest approach is to be aware of your method, to listen to readings from traditions other than your own, and to hold your interpretations with appropriate humility.",
  },

  {
    id: "c11-02",
    slug: "genre-recognition",
    domainId: "d11",
    name: "Genre Recognition in Biblical Literature",
    summary:
      "The Bible contains poetry, law, narrative, prophecy, apocalyptic, parable, epistle, and wisdom -- each with its own rules. Reading poetry as law or apocalyptic as prediction creates bad theology.",
    lensTags: ["academic", "protestant", "catholic"],
    relatedConceptSlugs: ["hermeneutical-frameworks", "wisdom-literature"],
    relatedTextRefs: ["Revelation 1:1", "Psalm 137:9", "Genesis 1"],
    layers: {
      accessible:
        "The biggest interpretive mistake people make with the Bible is treating every passage the same way. The Bible is not a single book but a library of 66 books (or 73, or 81, depending on your tradition) spanning over a thousand years, written in multiple genres. Reading a psalm the same way you read a law code, or reading Revelation the same way you read a letter from Paul, will produce terrible interpretations. Psalm 137:9 says 'Happy is the one who seizes your infants and dashes them against the rocks.' If you read this as a command, it is horrifying. If you recognize it as a raw lament from a traumatized exile -- a cry of pain, not a prescription -- it becomes one of the most honest prayers in Scripture. Genre is not a technicality. It determines meaning.",
      intermediate:
        "Major biblical genres and their reading rules:\n\nNarrative (Genesis, Samuel, Kings, Acts): tells what happened but does not always endorse what characters do. When David commits adultery and murder, the text narrates it; it does not approve it. Narrative morality is complex.\n\nLaw (Exodus 20-23, Leviticus, Deuteronomy): embedded in narrative context. Laws were given for specific communities in specific circumstances. Some are universal principles (do not murder), some are case law for an agrarian society (what to do if your ox gores someone), and some are purity regulations for the Temple system that no longer exists. Sorting these categories requires theological judgment.\n\nProphecy (Isaiah, Jeremiah, Amos): primarily forth-telling (speaking God's message to the present), not fore-telling (predicting the future). Prophets addressed specific political and social crises. Reading them as coded predictions of events 2,500 years later (common in popular prophecy books) ignores their actual message.\n\nApocalyptic (Daniel 7-12, Revelation): uses symbolic, visionary imagery to address present suffering with cosmic hope. The 'beast' in Revelation is not a prediction of a future world leader but an encoded critique of Roman imperial power. Reading apocalyptic as a literal timeline of future events is a genre mistake.\n\nWisdom (Proverbs, Ecclesiastes, Job): general observations about how life usually works, not absolute promises. 'Train up a child in the way he should go, and when he is old he will not depart from it' (Proverbs 22:6) is a wise observation, not a divine guarantee. Ecclesiastes deliberately contradicts Proverbs -- the Bible contains internal debate.",
      advanced:
        "Genre theory in biblical studies has been significantly advanced by the work of John Collins (defining apocalyptic genre), Tremper Longman III (wisdom literature), and Robert Alter (narrative art). Alter's 'The Art of Biblical Narrative' demonstrated that biblical prose is not naive or primitive but uses sophisticated literary techniques: type-scenes (recurring patterns like the 'meeting at a well'), key-word repetition (Leitwort), and deliberate ambiguity.\n\nThe most significant genre debate currently concerns Genesis 1-11. Is it history, myth, theology, or something else? The options: (1) literal history (young earth creationism), (2) 'myth' in the scholarly sense (a true story about the human condition expressed in non-historical form), (3) polemic (an anti-Babylonian creation story -- 'our God created differently from Marduk'), (4) liturgy (Genesis 1 structured as a seven-day Temple inauguration). These are not mutually exclusive -- a text can function in multiple generic modes simultaneously.\n\nThe parables of Jesus represent a distinctive genre that has been consistently misread. Adolf Julicher (1888) established that parables are not allegories (where every detail symbolizes something) but comparisons that make one central point. Yet Mark 4:10-12 has Jesus say he teaches in parables so that outsiders will NOT understand -- which contradicts the idea that parables clarify. C.H. Dodd and Joachim Jeremias demonstrated that parables originally addressed specific situations in Jesus' ministry and were later allegorized by the early church (compare Mark's version of the Sower parable with its allegorical interpretation). The most productive recent approach (Amy-Jill Levine, 'Short Stories by Jesus') reads parables as provocations that challenge every audience, not as comfortable morality tales."
    },
  },

  {
    id: "c11-03",
    slug: "reader-response-hermeneutics",
    domainId: "d11",
    name: "Reader-Response and the Role of the Interpreter",
    summary:
      "What if meaning does not live in the text alone but is created in the encounter between text and reader? This question transforms how you approach every verse.",
    lensTags: ["academic", "postmodern"],
    relatedConceptSlugs: ["hermeneutical-frameworks", "reader-response-hermeneutics"],
    relatedTextRefs: ["Luke 10:25-37"],
    layers: {
      accessible:
        "When you read 'Love your neighbor as yourself,' what does it mean? The answer depends on who you are. A wealthy person reads it differently than a homeless person. A Palestinian Christian reads it differently than an American evangelical. A woman reads it differently than a man. Reader-response hermeneutics takes this seriously: meaning is not just 'in' the text waiting to be extracted -- it is created in the encounter between the text and the reader. Every reading is an interpretation. Every interpreter brings their own experiences, questions, prejudices, and hopes. There is no 'view from nowhere.'",
      intermediate:
        "Reader-response theory emerged in literary studies (Stanley Fish, Wolfgang Iser) and was applied to biblical interpretation by scholars like Fernando Segovia and R.S. Sugirtharajah. The key insight: the historical-critical method claimed to read the Bible 'objectively,' but it was shaped by the social location of its practitioners (overwhelmingly white, male, European, Protestant academics). Their readings reflected their assumptions as surely as anyone else's -- they just had the institutional power to call their reading 'scientific' and everyone else's 'subjective.'\n\nThis does not mean 'anything goes.' Reader-response hermeneutics distinguishes between readings that are responsible to the text (engaging its language, context, and claims seriously) and readings that are irresponsible (ignoring the text to project whatever meaning is convenient). The goal is not to eliminate the reader's perspective but to make it conscious -- to read with awareness of what you bring to the text.\n\nLiberation hermeneutics (reading from the perspective of the poor), feminist hermeneutics (reading with attention to gender), postcolonial hermeneutics (reading against imperial assumptions), and queer hermeneutics (reading with attention to sexuality and gender identity) are all reader-response approaches that have produced genuinely new insights by asking questions the dominant tradition never thought to ask.",
      advanced:
        "The deepest challenge of reader-response hermeneutics is theological: if all reading is interpretation, then which interpretation is authoritative? The Catholic answer: the Magisterium (the teaching authority of the church) guarantees correct interpretation. The Protestant answer: the Holy Spirit guides the faithful reader. The postmodern answer: no interpretation is final; we are always in dialogue. Hans-Georg Gadamer's concept of 'Wirkungsgeschichte' (history of effects) suggests that a text's meaning is not fixed at the moment of writing but unfolds through its reception history. The meaning of Romans 13 ('submit to the governing authorities') looks very different after it was used to justify slavery, apartheid, and Nazi complicity.\n\nPaul Ricoeur's hermeneutical philosophy provides a productive middle ground: interpretation involves both explanation (analyzing the text's structure, context, and original meaning) and understanding (appropriating the text's meaning for one's own situation). Neither alone is sufficient. The scholar who explains without understanding produces dead knowledge. The devotional reader who understands without explaining risks projecting wishes onto the text.\n\nFor the reader: recognizing that you are always interpreting is not relativism -- it is intellectual honesty. The question is not whether you have a perspective but whether you are conscious of it and willing to let the text challenge it."
    },
  },

  {
    id: "c11-04",
    slug: "allegory-vs-literal",
    domainId: "d11",
    name: "Allegory vs. Literal: The Oldest Debate in Biblical Interpretation",
    summary:
      "Should you read the Bible literally or symbolically? The early church was bitterly divided on this question -- and the answer shaped everything.",
    lensTags: ["academic", "catholic", "protestant"],
    relatedConceptSlugs: ["hermeneutical-frameworks", "genre-recognition"],
    relatedTextRefs: ["Galatians 4:24", "Genesis 1-3", "Revelation 1:1"],
    layers: {
      accessible:
        "Two cities -- Alexandria and Antioch -- represented two approaches to reading the Bible in early Christianity. Alexandria (Clement, Origen) favored allegorical reading: every text has a deeper spiritual meaning beyond the surface. When Genesis says God 'walked in the garden,' God doesn't have legs -- the 'walking' means God's presence moving through creation. When the Song of Songs describes erotic love, it really means the love between Christ and the church. Antioch (John Chrysostom, Theodore of Mopsuestia) favored literal-historical reading: start with what the text actually says in its original context before looking for deeper meanings. The Song of Songs is a love poem. Genesis is a creation account. Respect the text's plain sense before spiritualizing it.",
      intermediate:
        "Origen developed a three-level reading system: literal (the surface meaning), moral (what it teaches about how to live), and spiritual/allegorical (the deeper mystical meaning). He believed every text had all three levels, though sometimes the literal level was deliberately absurd to force the reader to look deeper. Augustine adopted a similar approach with a crucial addition: the 'rule of charity' -- if your interpretation does not promote love of God and love of neighbor, you have misread the text.\n\nThe medieval church formalized this into the 'four senses of Scripture': literal (what happened), allegorical (what to believe), moral/tropological (how to act), and anagogical (where you are headed, i.e., heaven). The jingle: 'The letter teaches facts, the allegory what to believe, the moral what to do, the anagogy where to aim.'\n\nThe Reformation reasserted the primacy of the literal sense. Luther insisted on the 'plain sense' of Scripture against what he saw as Catholic allegorizing that could make the text say anything the church wanted. Calvin followed suit. This emphasis on literal reading eventually produced modern biblical literalism -- though neither Luther nor Calvin would recognize what American fundamentalism has done with the principle.\n\nThe irony: 'literal reading' has never meant 'taking every word at face value.' Even the most literal readers recognize poetry (Psalms), parable (Jesus' stories), and apocalyptic imagery (Revelation) as genres that require non-literal interpretation. The question is not 'literal or symbolic?' but 'what kind of text is this, and how does that genre work?'",
      advanced:
        "Henri de Lubac's monumental 'Medieval Exegesis' (4 volumes) recovered the richness of the pre-modern interpretive tradition and challenged the post-Enlightenment assumption that only historical-critical reading is 'real' scholarship. Hans Frei ('The Eclipse of Biblical Narrative') argued that the rise of historical criticism in the 18th century caused the church to lose the ability to read Scripture as a unified narrative -- reducing it to a collection of historical propositions to be verified or debunked.\n\nThe 'theological interpretation of Scripture' movement (Kevin Vanhoozer, Stephen Fowl, Ellen Davis) represents a contemporary attempt to recover pre-critical interpretive practices without abandoning critical tools. The argument: historical criticism tells you what the text meant to its original audience, but the church needs to know what the text means for the community of faith today. Both questions are legitimate, and neither alone is sufficient."
    },
  },

  {
    id: "c11-05",
    slug: "liberation-hermeneutics",
    domainId: "d11",
    name: "Liberation Hermeneutics: Reading from the Bottom",
    summary:
      "What if the Bible looks different when you read it from the perspective of the poor, the colonized, the enslaved, or the oppressed?",
    lensTags: ["academic", "liberation", "pastoral"],
    relatedConceptSlugs: ["hermeneutical-frameworks", "reader-response", "prophetic-tradition"],
    relatedTextRefs: ["Luke 4:18-19", "Exodus 3:7-8", "James 5:1-6"],
    layers: {
      accessible:
        "For most of church history, the Bible was read by people in power: clergy, scholars, kings, and landowners. Liberation theology, emerging in Latin America in the 1960s-70s, asked: what if we read the Bible from the perspective of the poor? The answer was shocking: the Bible suddenly looked like a different book. The Exodus was not just ancient history but a paradigm for God liberating oppressed people today. Mary's Magnificat ('He has brought down the powerful from their thrones and lifted up the lowly,' Luke 1:52) was not pious poetry but a revolutionary manifesto. Jesus' first sermon ('He has sent me to proclaim freedom for the prisoners and recovery of sight for the blind, to set the oppressed free,' Luke 4:18) was not spiritual metaphor but a political program.",
      intermediate:
        "Gustavo Gutierrez ('A Theology of Liberation,' 1971) laid the foundation: God has a 'preferential option for the poor' -- not because poor people are morally superior, but because God consistently sides with the vulnerable against the powerful throughout Scripture. Jon Sobrino, Leonardo Boff, and Ignacio Ellacuria developed this in different directions. Six Jesuits at the University of Central America, including Ellacuria, were assassinated by the Salvadoran military in 1989 for their theological work -- demonstrating that liberation theology was not abstract.\n\nFeminist hermeneutics (Elisabeth Schussler Fiorenza, Phyllis Trible, Renita Weems) applied the same lens to gender: reading the Bible with attention to women's experiences reveals both the patriarchal assumptions of the text and moments of resistance and liberation within it. Postcolonial hermeneutics (R.S. Sugirtharajah, Musa Dube) reads the Bible from colonized peoples' perspectives, noting that the Bible has been used both to justify colonialism ('the conquest of Canaan') and to resist it ('Let my people go').\n\nBlack theology (James Cone, 'A Black Theology of Liberation') argued that the God of the Bible is a God who takes sides -- specifically, God sides with Black people against white supremacy. Cone's claim was not that God loves Black people more but that a God who liberates slaves in Exodus and identifies with the crucified in Jesus cannot be neutral about racial oppression. This made many white Christians uncomfortable, which Cone took as evidence that he was reading the text correctly.",
      advanced:
        "The methodological contribution of liberation hermeneutics is the 'hermeneutical circle': practice (engagement with reality) shapes interpretation, and interpretation shapes practice. You do not first study the Bible and then act. You act (work with the poor, confront injustice), then read the Bible in light of that experience, then act again informed by the text. The Bible is not a problem to be solved but a conversation partner for an ongoing struggle.\n\nCritiques of liberation hermeneutics include: it can reduce the Bible to a political manifesto, it can romanticize poverty, and it risks imposing modern political categories onto ancient texts. These critiques have force. But the counter-argument is equally strong: all reading is done from a social location, and pretending otherwise simply allows the reading of the privileged to pass as 'objective' while calling the reading of the oppressed 'biased.' The question is never 'Do you have a perspective?' but 'Whose perspective does your reading serve?'"
    },
  },
];
