import type { Concept } from "./types";

export const domain12Concepts: Concept[] = [
  {
    id: "c12-01",
    slug: "eastern-orthodoxy",
    domainId: "d12",
    name: "Eastern Orthodoxy",
    summary:
      "The oldest continuously practicing form of Christianity, centered on divine liturgy, theosis (becoming like God), icons, and the seven ecumenical councils. It thinks in images where the West thinks in arguments.",
    lensTags: ["orthodox", "academic"],
    relatedConceptSlugs: ["council-of-nicaea", "eucharistic-traditions", "liturgical-calendar"],
    relatedTextRefs: ["2 Peter 1:4", "John 17:21", "Romans 8:29"],
    layers: {
      accessible:
        "Eastern Orthodox Christianity (Greek, Russian, Romanian, Serbian, and other national churches) claims to be the unchanged, original form of Christianity. While the West went through the Reformation and Counter-Reformation, Orthodoxy insists it has maintained the faith of the first seven ecumenical councils (325-787 CE) without addition or subtraction. Its worship centers on the Divine Liturgy -- an elaborate, beautiful, multi-sensory experience of icons, incense, chanting, and the Eucharist that has remained largely unchanged for over a millennium. Its central theological concept is theosis (divinization): salvation is not primarily about being forgiven or going to heaven but about becoming like God. As Athanasius said: 'God became man so that man might become God.' This is not blasphemy -- it means participation in God's nature (2 Peter 1:4), not replacement of God.",
      intermediate:
        "The Great Schism of 1054 between Rome and Constantinople was the culmination of centuries of growing differences. The immediate issues: the filioque clause (Rome added 'and the Son' to the Nicene Creed's statement about the Spirit's procession, without conciliar approval), papal authority (Rome claimed universal jurisdiction; Constantinople insisted on a collegial model of church governance), and liturgical differences (leavened vs. unleavened bread, clerical celibacy requirements). The deeper issue was ecclesiological: Rome developed a monarchical papacy; the East maintained conciliar governance with the Ecumenical Patriarch as 'first among equals.'\n\nOrthodox theology emphasizes mystery over definition. Where Western theology (following Augustine and Aquinas) tends toward systematic, rational explanation, Orthodox theology (following the Cappadocians, Maximus the Confessor, Gregory Palamas) insists that God is ultimately beyond human categories. This is 'apophatic theology' -- knowing God by what God is not. Palamas distinguished between God's essence (unknowable) and God's energies (experienced) -- a distinction the West never fully adopted.\n\nIcons are not decorations but theological statements. The Seventh Ecumenical Council (787) declared that refusing to venerate icons is a Christological heresy -- because if Christ truly became human, then the invisible God has become visible and can be depicted. Iconoclasm (destroying icons) denies the Incarnation. The icon is a window to heaven, not an idol.",
      advanced:
        "Orthodox theology's most distinctive contribution is its soteriology of theosis, which avoids the Western preoccupation with guilt, punishment, and forensic justification. The Orthodox reading of the Fall is less about inherited guilt (Augustine's reading) and more about inherited mortality and corruption. Death, not guilt, is the fundamental human problem, and Christ conquers death through resurrection. The Paschal homily of John Chrysostom, read at every Orthodox Easter vigil, captures this: 'Christ is risen, and not one dead remains in the grave.'\n\nThe Palamite distinction between essence and energies has enormous implications. If we experience God's energies (grace, love, beauty) directly and not merely metaphorically, then mystical experience is genuine knowledge of God -- not subjective feeling. This grounds Orthodox spirituality (hesychasm, the Jesus Prayer, neptic watchfulness) in a robust theological epistemology. The West's typical suspicion of mysticism as 'subjective' reflects an epistemology Orthodoxy rejects.\n\nContemporary Orthodox theology is experiencing a renewal through the 'neo-patristic synthesis' (Georges Florovsky, Vladimir Lossky, Alexander Schmemann, John Meyendorff, John Zizioulas). Zizioulas's 'Being as Communion' applies trinitarian theology to personhood: to be a person is to be in relationship. The Trinity is not a mathematical puzzle but the revelation that ultimate reality is relational, not individual. This has proved influential well beyond Orthodox circles."
    },
  },

  {
    id: "c12-02",
    slug: "reformed-tradition",
    domainId: "d12",
    name: "Reformed/Calvinist Tradition",
    summary:
      "The theological tradition shaped by John Calvin, emphasizing God's sovereignty, predestination, covenant theology, and the transformation of all culture under God's lordship.",
    lensTags: ["protestant", "reformed", "academic"],
    relatedConceptSlugs: ["reformation", "atonement-theories"],
    relatedTextRefs: ["Romans 9:10-21", "Ephesians 1:4-5", "John 6:44"],
    layers: {
      accessible:
        "The Reformed tradition begins with John Calvin (1509-1564), who created a comprehensive theological system centered on God's absolute sovereignty. The most controversial doctrine: double predestination -- before the foundation of the world, God chose (elected) some people for salvation and passed over others, and nothing humans do can change this. This sounds harsh, but Calvin's point was pastoral: your salvation is entirely in God's hands, so you cannot earn it, lose it, or worry about it. The five points of Calvinism (TULIP) summarize the tradition: Total depravity (humans cannot save themselves), Unconditional election (God chooses freely), Limited atonement (Christ died specifically for the elect), Irresistible grace (God's call cannot be refused), Perseverance of the saints (the elect cannot lose their salvation). Not all Reformed Christians hold all five points.",
      intermediate:
        "Calvin's influence extends far beyond soteriology. His covenant theology sees all of Scripture as one continuous covenant story (covenant of works with Adam, covenant of grace through Christ), providing a framework for relating Old and New Testaments. His theology of culture ('all of life is lived coram Deo -- before the face of God') motivated Reformed Christians to engage education, politics, economics, and arts as vocations, not distractions from spiritual life. This cultural mandate has been credited (by Max Weber in 'The Protestant Ethic and the Spirit of Capitalism') with shaping Western capitalism, democratic governance, and the work ethic.\n\nThe Reformed tradition is broader than 'Calvinist.' It includes: Continental Reformed (Dutch: Kuyper, Bavinck), Scottish Presbyterian (John Knox), English Puritan (Jonathan Edwards, widely considered America's greatest theologian), South African Reformed (both the theology that justified apartheid AND the theology that opposed it -- the Belhar Confession), and contemporary Neo-Calvinism (Tim Keller, the New Calvinism movement).\n\nKey internal debates: Should the church transform culture (Kuyper's 'sphere sovereignty') or remain a distinct counter-culture (Two Kingdoms theology)? Is the covenant of works with Adam properly biblical or a later construction? Does limited atonement actually follow from the other four points? Many Reformed theologians hold four-point Calvinism, replacing limited atonement with hypothetical universalism (Christ's death is sufficient for all but efficient only for the elect).",
      advanced:
        "The most important contemporary Reformed theologian may be Jurgen Moltmann (though he is technically Reformed-Lutheran). His 'Theology of Hope' (1964) and 'The Crucified God' (1972) reframed Reformed theology around eschatology (the future determines the present, not the past) and the cross (God's own suffering with the world). Moltmann's social trinitarianism -- the Trinity as a community of persons-in-relation rather than a single sovereign monarch -- challenges classical Reformed emphasis on divine sovereignty and has been criticized by more traditional Reformed thinkers as undermining God's aseity (self-existence).\n\nKarl Barth, the 20th century's most influential Reformed theologian, revised the tradition dramatically. Barth rejected natural theology (knowledge of God through nature or reason), double predestination in its classical form (he argued Christ is both the elect and the reprobate, collapsing double predestination into Christology), and the analogy of being (analogia entis) between God and creation. Barth's 'Church Dogmatics' (over 9,000 pages, unfinished) remains the most ambitious systematic theology of the modern era.\n\nThe Reformed tradition's greatest ongoing tension is between its emphasis on God's sovereignty (which tends toward determinism and can undermine human agency) and its emphasis on human responsibility (covenant faithfulness, cultural engagement). The best Reformed theology holds both -- but practically, congregations tend to lean one way or the other."
    },
  },

  {
    id: "c12-03",
    slug: "orthodox-theology",
    domainId: "d12",
    name: "Eastern Orthodoxy: The Road Not Taken",
    summary:
      "Most Western Christians know almost nothing about Orthodoxy -- the tradition that claims to be the unchanged Christianity of the first millennium.",
    lensTags: ["orthodox", "academic"],
    relatedConceptSlugs: ["council-of-nicaea", "christology", "eucharist-meanings"],
    relatedTextRefs: ["John 17:21", "2 Peter 1:4"],
    layers: {
      accessible:
        "When the Roman Empire split into East and West, Christianity split with it. The Western church (centered in Rome) became Roman Catholicism. The Eastern church (centered in Constantinople, now Istanbul) became Eastern Orthodoxy. The formal split happened in 1054, but the traditions had been growing apart for centuries. Most Western Christians -- Catholic or Protestant -- know almost nothing about Orthodoxy, yet it represents a radically different approach to almost every major theological question. Where the West focuses on law and guilt (original sin, atonement, justification), the East focuses on transformation and participation in God (theosis/deification). Where the West defines doctrines precisely, the East preserves mystery through apophatic (negative) theology: saying what God is NOT rather than what God IS.",
      intermediate:
        "Key Orthodox distinctives that differ from Western Christianity:\n\nTheosis (deification): The goal of the Christian life is not just forgiveness but participation in the divine nature (2 Peter 1:4). Athanasius: 'God became human so that humans might become God.' This does not mean becoming God in essence but sharing in God's energies (grace, love, beauty, life). The entire trajectory of Orthodox spirituality points toward transformation into Christlikeness -- not merely moral improvement but ontological change.\n\nApophatic theology: God is ultimately beyond all human concepts and language. You can say 'God is not finite,' 'God is not material,' 'God is not limited' -- but you cannot finally say what God IS. This keeps theology humble and protects the mystery. Gregory of Nyssa: the closer you get to God, the more you realize how far beyond comprehension God is.\n\nIconography: Icons are not decorations but 'windows into heaven.' The theology of icons (developed through the iconoclastic controversies of the 8th-9th centuries) insists that because God became visible in Christ (the Incarnation), the visible can mediate the invisible. To venerate an icon is not to worship the wood and paint but to honor the reality it represents.\n\nThe Divine Liturgy: Orthodox worship has not fundamentally changed in 1,500 years. The Liturgy of St. John Chrysostom (4th century) is still the standard Sunday service. This continuity is intentional: the liturgy is meant to be participation in the eternal worship of heaven, not a human production updated for contemporary tastes.",
      advanced:
        "The most significant Orthodox contribution to contemporary theology is the recovery of patristic thought (the theology of the first eight centuries). Figures like Vladimir Lossky ('The Mystical Theology of the Eastern Church'), Georges Florovsky ('Ways of Russian Theology'), and John Meyendorff ('Byzantine Theology') demonstrated that the Eastern Fathers (Gregory of Nazianzus, Basil of Caesarea, Maximus the Confessor, Gregory Palamas) had developed sophisticated theological frameworks that were simply unknown in the West.\n\nThe Essence-Energies distinction (Gregory Palamas, 14th century) is perhaps the most important and most misunderstood Orthodox concept. God's essence (what God is in Godself) is absolutely unknowable and inaccessible. But God's energies (God's self-communication in grace, beauty, creation, and salvation) are genuinely God -- not something God creates but God's own life shared with creation. This preserves both God's transcendence (we can never know God exhaustively) and God's immanence (we can genuinely participate in God's life). Western theology has no exact equivalent, which is why the conversation between East and West remains so fruitful and so difficult.\n\nFor the contemporary Western reader, Orthodoxy offers several correctives: theology as doxology (the purpose of doctrine is worship, not information); salvation as transformation (not merely legal acquittal); the church as communion (not an institution or a collection of individuals); and tradition as a living conversation with the past (not a dead deposit to be preserved unchanged)."
    },
  },

  {
    id: "c12-04",
    slug: "baptist-tradition",
    domainId: "d12",
    name: "The Baptist Tradition: Soul Freedom and Its Consequences",
    summary:
      "Baptists are the largest Protestant group in America. Their core principle -- that every person must choose their own faith freely -- has shaped American religion and politics more than any other idea.",
    lensTags: ["academic", "protestant"],
    relatedConceptSlugs: ["reformation", "baptism-meanings"],
    relatedTextRefs: ["Romans 10:9-10", "Acts 2:38", "Matthew 28:19"],
    layers: {
      accessible:
        "Baptists emerged in the early 1600s from English Separatism -- groups that believed the Church of England was too corrupted by state control to reform from within. Their defining commitments: believer's baptism (only people who have personally chosen to follow Christ are baptized -- no infant baptism), soul competency (every person is capable of relating directly to God without priestly mediation), church autonomy (each local congregation governs itself -- no pope, no bishops, no denominational hierarchy), and religious liberty (the government has no business in matters of faith). This last principle is the Baptist gift to American democracy: the separation of church and state was championed most forcefully by Baptists (Roger Williams, John Leland) who had been persecuted by state churches.",
      intermediate:
        "The Baptist family is enormous and internally diverse. Southern Baptists (the largest Protestant denomination in America, ~13 million members) tend toward conservative theology and politics. American Baptists tend toward moderate-progressive positions. National Baptist Convention and Progressive National Baptist Convention are historically Black denominations with deep roots in the civil rights movement (Martin Luther King Jr. was a Baptist minister). Independent Baptists range from moderate to fundamentalist.\n\nThe theological fault line within Baptist life is the tension between two founding principles: soul freedom (every person interprets Scripture for themselves) and biblical authority (the Bible is the final authority). These principles can conflict: what happens when one person's soul-free interpretation contradicts another's? Southern Baptists resolved this in the 'Conservative Resurgence' (1979-2000) by centralizing theological authority around biblical inerrancy -- which many Baptist historians argue betrayed the tradition's commitment to local autonomy and individual conscience.\n\nBaptist worship ranges from formal (some American Baptist churches use liturgy) to informal (many independent Baptist churches are spontaneous and energetic). The emphasis on personal decision ('accepting Jesus as your Lord and Savior') makes evangelism central. The altar call -- inviting people to 'come forward' to make a public commitment -- is a Baptist invention that became standard across evangelical Christianity.",
      advanced:
        "Bill Leonard ('Baptist Ways: A History') and Walter Shurden ('The Baptist Identity: Four Fragile Freedoms') provide the best historical treatments. Shurden identifies four Baptist freedoms: Bible freedom (the right to interpret Scripture without creedal constraint), soul freedom (the individual's uncoerced relationship with God), church freedom (local congregation autonomy), and religious freedom (separation of church and state).\n\nThe irony of Baptist history is that a tradition founded on freedom and dissent has repeatedly produced authoritarian structures. The Southern Baptist Convention's conservative leaders achieved precisely the kind of centralized theological control that early Baptists opposed in the Church of England. This pattern -- freedom movements calcifying into new orthodoxies -- is visible across denominations, but in Baptist life it is especially poignant because the entire tradition was built on the rejection of such authority."
    },
  },

  {
    id: "c12-05",
    slug: "pentecostalism",
    domainId: "d12",
    name: "Pentecostalism: Christianity's Fastest-Growing Movement",
    summary:
      "From a tiny mission in Los Angeles in 1906 to 650 million people worldwide. Pentecostalism is reshaping global Christianity -- and most Western intellectuals have barely noticed.",
    lensTags: ["academic", "charismatic"],
    relatedConceptSlugs: ["baptist-tradition", "reformation", "sacred-music"],
    relatedTextRefs: ["Acts 2:1-13", "1 Corinthians 12:4-11", "Mark 16:17-18"],
    layers: {
      accessible:
        "Pentecostalism began on April 9, 1906, at 214 Bonnie Brae Street in Los Angeles, when participants in a prayer meeting led by William Seymour (a Black preacher, son of former slaves) began speaking in tongues. The Azusa Street Revival that followed (1906-1915) drew people of all races and social classes at a time when America was rigidly segregated. Participants believed they were experiencing a 'new Pentecost' -- a fresh outpouring of the Holy Spirit like the one described in Acts 2. Today, Pentecostalism (including Charismatic movements within Catholic, Orthodox, and mainline Protestant churches) claims roughly 650 million adherents worldwide -- about a quarter of all Christians. It is the fastest-growing branch of Christianity in Africa, Latin America, and Asia.",
      intermediate:
        "Core Pentecostal distinctives: 'Baptism in the Holy Spirit' as a second experience after conversion, typically evidenced by speaking in tongues (glossolalia). The continuation of all spiritual gifts (healing, prophecy, miracles, tongues, interpretation of tongues) -- these did not cease with the apostolic age. Lively, participatory worship with expectation of direct divine encounter. Emphasis on personal holiness and the imminent return of Christ.\n\nPentecostalism's growth in the Global South is the most significant development in modern Christianity. In Brazil, roughly 25% of the population is Pentecostal. In Nigeria, Ghana, South Korea, and the Philippines, Pentecostal churches are growing exponentially. The prosperity gospel (the teaching that God rewards faith with financial blessing) has become dominant in many Pentecostal churches, especially in Africa and Latin America. Critics see this as theological manipulation of the poor. Defenders argue it offers hope and agency to marginalized people.\n\nAcademically, Pentecostalism was long dismissed as emotionalism for the uneducated. This has changed dramatically. Amos Yong ('The Spirit Poured Out on All Flesh') and Frank Macchia ('Baptized in the Spirit') have developed sophisticated Pentecostal theologies. The Pentecostal emphasis on experience, embodiment, and the Spirit has influenced theological conversations far beyond Pentecostal circles.",
      advanced:
        "Harvey Cox ('Fire from Heaven') and Allan Anderson ('An Introduction to Pentecostalism') provide the essential global perspectives. Anderson argues that Pentecostalism should be understood not as a single movement but as a family of movements united by the emphasis on the Spirit's power and presence. Its adaptability to local cultures (African indigenous Pentecostalism looks very different from American megachurch Pentecostalism) is the key to its growth.\n\nThe theological significance of Pentecostalism for the broader church is the recovery of pneumatology (theology of the Holy Spirit). Western Christianity (both Catholic and Protestant) has been accused of neglecting the Spirit in favor of Christology and ecclesiology. Pentecostalism's insistence that the Spirit is active, present, and powerful today corrects this imbalance. Whether the specific manifestations (tongues, prophecy, healing) are genuine is debated, but the underlying claim -- that God is not finished acting in the world -- is one that most Christians would affirm in theory, even if Pentecostal practice makes them uncomfortable."
    },
  },
];
