import type { Concept } from "./types";

export const domain13Concepts: Concept[] = [
  {
    id: "c13-01",
    slug: "theodicy",
    domainId: "d13",
    name: "Theodicy -- Why Does God Allow Suffering?",
    summary:
      "The hardest question in theology. The tradition has answers. None of them are completely satisfying. That's honest.",
    lensTags: ["academic", "protestant", "catholic", "orthodox", "pastoral"],
    relatedConceptSlugs: ["wisdom-literature", "grief-lament", "atonement-theories"],
    relatedTextRefs: ["Job 38", "Psalm 22", "Romans 8:28"],
    layers: {
      accessible:
        "If God is all-good and all-powerful, why do innocent people suffer? This is the problem of theodicy (from the Greek 'theos' + 'dike' -- the justice of God), and it is the hardest question in theology. The honest answer: no one has ever fully solved it. But the tradition has generated several serious responses. The Free Will Defense says God gave humans freedom, and suffering is the cost of that freedom. The Soul-Making Theodicy says suffering develops character and growth. The Cruciform Theodicy says God does not stand apart from suffering but enters into it on the cross. And the Protest Theodicy (Elie Wiesel) says the right response is not to explain suffering but to accuse God and continue the relationship anyway.",
      intermediate:
        "The classical formulation (Epicurus, later refined by David Hume): 'Is God willing to prevent evil, but not able? Then he is not omnipotent. Is he able, but not willing? Then he is malevolent. Is he both able and willing? Then whence evil?' This trilemma has generated the major theodicy traditions.\n\nAugustine's Privation Theory: evil is not a thing in itself but the absence of good, like darkness is the absence of light. Evil exists because creatures with free will can turn away from God. This preserves God's goodness but raises the question of why God would create beings he knew would cause suffering.\n\nIrenaeus/Hick's Soul-Making Theodicy: the world is not a finished paradise but a 'vale of soul-making' where suffering enables growth, compassion, and moral development. The criticism: this fails before the suffering of children and animals, who cannot be meaningfully 'developed' by their pain.\n\nMoltmann's Cruciform Theodicy (The Crucified God, 1972): God does not observe suffering from the outside but enters fully into it in the cross. On the cross, God suffers. The Trinity is broken open by suffering -- the Father experiences the death of the Son. This does not explain why suffering exists but transforms the question from 'where is God in suffering?' to 'God is in the suffering.'\n\nWiesel's Protest Theodicy: in 'Night,' Wiesel describes watching a child being hanged in Auschwitz and hearing someone ask 'Where is God now?' The answer: 'There He is -- hanging on that gallows.' Wiesel does not leave the relationship with God. He accuses God. The biblical precedent is Job, who never gets an answer but never stops demanding one.",
      advanced:
        "Contemporary theology has largely moved beyond attempting to 'solve' theodicy and toward a pastoral and existential engagement with it.\n\nD.Z. Phillips ('The Problem of Evil and the Problem of God') argues that theodicy itself is the problem -- the attempt to justify suffering is morally obscene because it implies that suffering serves a purpose, which devalues the person who suffers. Phillips draws on Simone Weil: 'The love of God is not consolation, it is light.'\n\nWilliam Rowe's 'evidential argument from evil' distinguishes between logical and evidential problems. The logical problem (is evil logically incompatible with God's existence?) was arguably solved by Plantinga's Free Will Defense. The evidential problem (does the sheer amount and intensity of suffering make God's existence unlikely?) remains powerful.\n\nFor pastoral engagement: Romans 8:28 ('all things work together for good') is the most misused verse in grief situations. In context, Paul is not saying 'your suffering has a purpose' but making a cosmic eschatological claim about God's ultimate redemption of creation. Telling a grieving person that their loss 'happened for a reason' is pastoral malpractice. The ministry of presence -- being with someone in their pain without trying to explain it -- is consistently what pastoral care research identifies as most helpful.\n\nJob remains the most honest theological text on suffering. God's answer from the whirlwind (chapters 38-41) is not an explanation but a tour of creation's wildness and mystery. The implicit message: the universe is vastly more complex than your categories of justice and reward. This is not an answer. It may be the only honest response."
    },
    honestAnalysis:
      "No theodicy is fully satisfying. The intellectual problem has not been solved, and attempts to explain particular instances of suffering to the people experiencing them consistently cause more harm than good. The most honest Christian response combines intellectual honesty about the mystery with pastoral presence in the suffering.",
  },

  {
    id: "c13-02",
    slug: "grief-lament",
    domainId: "d13",
    name: "Grief, Lament, and the Psalms",
    summary:
      "The biblical tradition does not shy away from grief but runs straight into it. The Psalms of Lament are the Bible's gift to people in pain -- a permission slip to scream at God.",
    lensTags: ["pastoral", "protestant", "catholic", "jewish"],
    relatedConceptSlugs: ["theodicy", "wisdom-literature"],
    relatedTextRefs: ["Psalm 22", "Psalm 88", "Lamentations 3", "Job 3"],
    layers: {
      accessible:
        "One-third of the Psalms are laments -- songs of complaint, grief, anger, and even accusation directed at God. Psalm 22 opens with 'My God, my God, why have you forsaken me?' -- the same words Jesus cried from the cross. Psalm 88 is the darkest text in the Bible: it begins in despair and ends in despair with no resolution. Lamentations describes the destruction of Jerusalem in agonizing detail. These are not failures of faith. They are faith at its most honest. The biblical tradition insists that bringing your pain, anger, and confusion to God IS prayer. The opposite of praise is not lament -- the opposite of praise is silence. People who lament are still in relationship with God. People who go silent have given up.",
      intermediate:
        "Walter Brueggemann's framework for the Psalms identifies three movements: orientation (life is ordered, God is good -- Psalm 1, 119), disorientation (life has collapsed, where is God? -- Psalm 22, 88, 137), and new orientation (God has acted, life is restored but different -- Psalm 30, 40, 116). The crucial insight: you cannot skip from orientation to new orientation. The disorientation Psalms are not optional. They are the passage through which genuine transformation happens.\n\nThe church's historic failure has been to suppress lament. Most hymn books contain few lament songs. Most worship services have no space for grief, anger, or complaint. The result: people in pain feel excluded from worship, or worse, believe their suffering means they lack faith. The Psalms of Lament model a faith that is robust enough to include protest.\n\nJewish practice preserves lament better than most Christian traditions. The book of Lamentations is read annually on Tisha B'Av (the anniversary of the Temple's destruction). Sitting shiva (seven days of mourning after a death) creates structured space for grief. The Kaddish prayer, recited daily for a year after a death, is not a prayer about death at all -- it is a praise of God. This juxtaposition of grief and praise is not denial but an insistence that both are true simultaneously.",
      advanced:
        "Nicholas Wolterstorff's 'Lament for a Son' (written after his 25-year-old son's death in a climbing accident) and C.S. Lewis's 'A Grief Observed' (written after his wife's death) are the two most important modern Christian grief texts. Both refuse comfort too quickly. Wolterstorff: 'Every lament is a love-song.' Lewis: 'Talk to me about the truth of religion and I'll listen gladly. Talk to me about the duty of religion and I'll listen submissively. But don't come talking to me about the consolations of religion or I shall suspect that you don't understand.'\n\nPastorally, the ministry of presence (being with someone in pain without trying to fix, explain, or theologize it) is consistently identified in empirical pastoral care research as the most helpful response to grief. The instinct to quote Romans 8:28 ('all things work together for good') to a grieving person is pastoral malpractice -- not because the verse is false but because it is deployed as a premature resolution of a pain that needs time, space, and witness.\n\nThe theological recovery of lament has practical implications for worship design. Soong-Chan Rah ('Prophetic Lament') argues that the American church's preference for triumphalism (praise, victory, blessing) over lament reflects cultural privilege, not biblical theology. Communities that are suffering -- Black churches during Jim Crow, Korean churches under Japanese occupation, Palestinian Christians under occupation -- have never lost the lament tradition. The prosperity gospel represents the most extreme suppression of lament: if suffering indicates lack of faith, then lament is faithlessness. This is the exact opposite of the Psalter's theology."
    },
  },

  {
    id: "c13-03",
    slug: "faith-and-mental-health",
    domainId: "d13",
    name: "Faith, Mental Health, and Spiritual Struggle",
    summary:
      "Depression is not a faith failure. Anxiety is not a sin. The intersection of theology and mental health requires both pastoral sensitivity and clinical honesty.",
    lensTags: ["pastoral", "ecumenical"],
    relatedConceptSlugs: ["theodicy", "grief-lament", "centering-prayer"],
    relatedTextRefs: ["1 Kings 19:1-8", "Psalm 42", "2 Corinthians 12:7-10"],
    layers: {
      accessible:
        "Elijah, after his greatest victory (defeating the prophets of Baal), ran away, collapsed under a tree, and asked God to let him die (1 Kings 19). David wrote 'my tears have been my food day and night' (Psalm 42). Jesus sweat blood in Gethsemane and cried out in abandonment on the cross. The Bible is full of people in psychological and spiritual crisis -- and God's response is never 'just have more faith.' God sends Elijah food and sleep (the basics of self-care), then meets him not in the dramatic wind, earthquake, or fire but in a 'still, small voice.' The biblical tradition takes mental suffering seriously as a human experience, not as evidence of spiritual failure.",
      intermediate:
        "The relationship between faith and mental health has been complicated by two equally dangerous errors. The first: the claim that depression, anxiety, or other mental health conditions are caused by sin, lack of faith, or demonic influence, and can be cured by prayer alone. This has caused incalculable harm, leading people to refuse medication, avoid therapy, and blame themselves for conditions that have neurochemical and genetic components. The second error: the reduction of all spiritual struggle to clinical categories, as if every dark night of the soul is really just undiagnosed depression. Both errors collapse a complex reality into a single dimension.\n\nA healthier framework: mental health conditions are real medical issues requiring professional treatment (therapy, medication when appropriate). And spiritual struggles are real spiritual issues requiring pastoral care, community, and spiritual practice. These can coexist. A person can have both a clinical anxiety disorder AND a genuine spiritual struggle with trusting God -- and treating only one while ignoring the other leaves them half-healed.\n\nThe 'dark night of the soul' (John of the Cross) is a specific spiritual experience of God's apparent absence that occurs as part of contemplative growth. It is NOT depression, though it can feel similar. The dark night has a purpose (purification of spiritual attachments) and a trajectory (deeper intimacy with God). Clinical depression has no inherent spiritual purpose and requires medical treatment. Confusing the two harms people in both situations.",
      advanced:
        "Contemporary pastoral theology draws on attachment theory (John Bowlby, applied to God-image by Ana-Maria Rizzuto) to understand how early relational experiences shape people's images of God. A person raised by a critical, distant, or unpredictable parent may unconsciously experience God as critical, distant, or unpredictable -- regardless of what they believe theologically. This means that telling someone 'God loves you unconditionally' may not penetrate if their attachment system has been shaped by conditional love. Spiritual formation is partly the rewiring of these deep emotional patterns, which is why community, embodied practice, and consistent pastoral presence matter more than correct doctrine.\n\nThe clinical research on religion and mental health (Kenneth Pargament, 'Spiritually Integrated Psychotherapy') identifies both positive and negative forms of religious coping. Positive religious coping includes seeking spiritual support, finding meaning, and connecting with community. Negative religious coping includes feeling punished by God, doubting God's power or love, and experiencing interpersonal religious conflict. The distinction is not between 'having faith' and 'not having faith' but between how faith is deployed in crisis.\n\nPractical implications for churches: train pastors in mental health first aid; normalize help-seeking (therapy is not a faith failure); create worship spaces that include lament; stop using toxic phrases ('God never gives you more than you can handle' -- this is a misquotation of 1 Corinthians 10:13, which is about temptation, not suffering); maintain referral relationships with licensed therapists; and recognize that spiritual formation and clinical treatment are complementary, not competing, forms of care."
    },
    honestAnalysis:
      "The church has historically done more harm than good in the mental health space. The turn toward integration of faith and clinical practice is promising but uneven. Churches that tell people to pray instead of seeking therapy are causing harm. Therapists who dismiss spiritual experience as pathology are missing a crucial dimension of human life. Both need each other.",
  },

  {
    id: "c13-04",
    slug: "deconstruction",
    domainId: "d13",
    name: "Deconstruction: When Your Faith Falls Apart",
    summary:
      "Millions of people are 'deconstructing' their faith -- questioning beliefs they were raised with. The tradition has a name for this. It is not new.",
    lensTags: ["pastoral", "contemplative"],
    relatedConceptSlugs: ["dark-night-of-soul", "theodicy", "faith-mental-health"],
    relatedTextRefs: ["Psalm 22:1", "Job 23:8-9", "Mark 9:24"],
    layers: {
      accessible:
        "Deconstruction is the trendy term for something the Christian tradition has always known: faith grows through crisis. You believe what you were taught (first naivete). You encounter something that makes that belief impossible to maintain -- suffering, hypocrisy, new information, moral failure of leaders (the crisis). You either construct a new, more mature faith on the other side (second naivete), or you leave entirely. The term 'deconstruction' comes from philosophy (Jacques Derrida) but has been adopted by ex-evangelicals and progressive Christians to describe the process of questioning inherited beliefs. Churches panic about deconstruction. But the Psalms are full of it. Job is one long deconstruction. Jesus deconstructed the Pharisees' theology in real time. The question is not whether deconstruction happens -- it is whether there is support for people going through it.",
      intermediate:
        "Paul Ricoeur's framework is the most useful: first naivete (uncritical acceptance of inherited beliefs) -> critical distance (questioning, doubt, analysis) -> second naivete (a re-chosen faith that has passed through the fire of questioning and come out deeper). The problem in many churches: they only have space for first naivete. Doubt is treated as sin. Questions are treated as rebellion. So when people inevitably reach the critical distance phase, they have no support and often leave entirely -- when what they actually needed was a community that could hold them through the transition.\n\nJames Fowler's 'Stages of Faith' maps this process developmentally: Stage 3 (Synthetic-Conventional) faith relies on the authority of the community. Stage 4 (Individuative-Reflective) faith questions that authority and constructs personal conviction. Stage 5 (Conjunctive) faith reintegrates what was lost in Stage 4 -- including mystery, paradox, and symbol. Most churches operate at Stage 3 and interpret Stage 4 as falling away rather than growing up.\n\nThe 'deconstruction' wave in American evangelicalism (2015-present) has specific triggers: the sexual abuse crisis (exposed in the Southern Baptist Convention, Catholic Church, and independent churches), white evangelical alignment with Trump (which for many younger believers contradicted Jesus' teaching), purity culture trauma (the psychological damage of abstinence-only sexual ethics), and access to information (biblical scholarship, church history, and critical thinking are now available to anyone with a phone). These are not attacks on faith. They are the removal of protective barriers that kept uncomfortable truths at bay.",
      advanced:
        "The pastoral challenge of deconstruction is that it is simultaneously necessary (growth requires questioning) and dangerous (questioning without support can produce cynicism, despair, or rootlessness). Richard Rohr's concept of 'order-disorder-reorder' maps onto Ricoeur's framework: you need first-order faith to have something to deconstruct, and you need the deconstruction to reach a reordered faith that is genuinely yours.\n\nPeter Enns ('The Sin of Certainty,' 'How the Bible Actually Works') and Rachel Held Evans ('Faith Unraveled,' 'Searching for Sunday') have been the most visible voices accompanying people through deconstruction. Their approach: doubt is not the opposite of faith but an element of mature faith. The opposite of faith is not doubt but certainty -- the refusal to hold your beliefs open to correction.\n\nThe institutional response varies. Some churches have created 'questioning-friendly' spaces. Others have doubled down on certainty, excommunicating or shaming doubters. The historical irony is that the Reformation itself was a massive deconstruction -- Luther questioning inherited Catholic beliefs. Those who celebrate Luther while condemning contemporary deconstruction are celebrating the same process in the past that they reject in the present."
    },
  },

  {
    id: "c13-05",
    slug: "money-and-faith",
    domainId: "d13",
    name: "Money, Wealth, and the Jesus Problem",
    summary:
      "Jesus talked about money more than heaven and hell combined. What he said was clear. What Christians do about it is complicated.",
    lensTags: ["pastoral", "academic"],
    relatedConceptSlugs: ["prophetic-tradition", "liberation-hermeneutics"],
    relatedTextRefs: ["Luke 6:20-26", "Matthew 19:24", "Luke 16:19-31", "Acts 2:44-45"],
    layers: {
      accessible:
        "Jesus said 'Blessed are the poor' (Luke's version -- not 'poor in spirit,' which is Matthew's softened version). He told a rich man to sell everything and give to the poor. He said it is easier for a camel to go through the eye of a needle than for a rich person to enter the kingdom of God. He told a parable about a rich man who went to hell while a beggar went to Abraham's side. The early church in Acts 'had everything in common; they sold property and possessions and shared with anyone who had need.' This is all very clear. It is also very inconvenient for Christians who are wealthy -- which includes, by global standards, most American Christians. The history of Christian engagement with money is largely a history of explaining why Jesus didn't really mean what he clearly said.",
      intermediate:
        "The softening mechanisms are fascinating to trace. Matthew's 'poor in spirit' (5:3) spiritualizes Luke's blunt 'poor' (6:20). Clement of Alexandria (2nd century) wrote 'Who Is the Rich Man Who Shall Be Saved?' arguing that Jesus meant inner detachment from wealth, not literal poverty. The 'eye of the needle' has been explained as a small gate in Jerusalem's wall (no archaeological evidence for this -- it was invented to make the saying less radical). The prosperity gospel (Kenneth Hagin, Joel Osteen, Creflo Dollar) inverts Jesus' teaching entirely: God WANTS you to be rich, and wealth is a sign of God's blessing.\n\nThe monastic tradition took Jesus literally: vows of poverty, communal ownership, simple living. Francis of Assisi stripped naked in the public square, renounced his father's wealth, and spent his life among lepers and beggars. Dorothy Day founded the Catholic Worker movement on the premise that Christians should live among the poor and share their resources. These are minority traditions within Christianity, but they are the traditions that take Jesus' words at face value.\n\nJohn Wesley developed a practical framework: 'Earn all you can. Save all you can. Give all you can.' Wesley himself earned the equivalent of millions from his writings and gave away roughly 98% of his income, living on a fraction. The Wesleyan model acknowledges economic participation while demanding radical generosity -- a middle path between prosperity gospel and vow-of-poverty asceticism.",
      advanced:
        "Walter Pilgrim ('Good News to the Poor: Wealth and Poverty in Luke-Acts') demonstrates that Luke's Gospel has a consistent and radical economic ethic: the kingdom of God involves the concrete redistribution of material resources from rich to poor. This is not spiritualized. It is economic. The Magnificat, the Beatitudes, the parable of Lazarus and the rich man, Zacchaeus giving away half his possessions, the Jerusalem community sharing everything -- Luke presents this as normative Christianity, not an optional extra.\n\nSiri Srinivas and Joerg Rieger ('No Religion but Social Religion: Liberating Wesleyan Theology') recover Wesley's radical economic practice and argue that it has been domesticated by modern Methodism. The same domestication has happened to Franciscan poverty, monastic simplicity, and every other attempt to take Jesus' words about money seriously. The gravitational pull of wealth within Christian institutions has consistently overwhelmed the centrifugal force of Jesus' teaching.\n\nThe honest assessment: mainstream Christianity has never figured out what to do with Jesus' teaching on money. It is too clear to ignore and too demanding to follow. The result is an ongoing negotiation between the text and the reader's material circumstances -- a negotiation that, for wealthy Christians, usually ends with the reader winning."
    },
  },
];
