import type { Concept } from "./types";

export const domain2Concepts: Concept[] = [
  {
    id: "c2-01",
    slug: "synoptic-problem",
    domainId: "d2",
    name: "The Synoptic Problem",
    summary:
      "Why do Matthew, Mark, and Luke tell the same stories in the same order with the same words -- and sometimes don't?",
    lensTags: ["academic"],
    relatedConceptSlugs: ["q-source", "synoptic-problem", "gospel-of-thomas"],
    relatedTextRefs: ["Mark 1:1", "Matthew 1:1", "Luke 1:1"],
    layers: {
      accessible:
        "Matthew, Mark, and Luke are called the 'Synoptic' Gospels because they can be 'seen together' -- they share many of the same stories, often in the same order, sometimes with identical wording. But they also differ in significant ways. The 'Synoptic Problem' is the scholarly question of how to explain these agreements and disagreements. The most widely accepted solution is that Mark wrote first, and Matthew and Luke each independently used Mark as a source, plus a shared source of Jesus' sayings that scholars call 'Q' (from the German 'Quelle,' meaning 'source'). Each Gospel also has unique material found nowhere else.",
      intermediate:
        "The Two-Source Hypothesis (Markan Priority + Q) is the dominant academic model. The evidence for Mark writing first: (1) Mark is shortest -- almost all of Mark appears in Matthew and/or Luke, but much of Matthew and Luke is not in Mark. It's easier to explain additions than deletions. (2) Matthew and Luke improve Mark's rougher Greek. (3) Where Matthew and Luke diverge from each other, at least one usually follows Mark. (4) The 'Markan order' -- when Matthew departs from Mark's sequence, Luke follows Mark, and vice versa. They never agree against Mark in sequence.\n\nQ is a hypothetical document -- no copy has ever been found. It's reconstructed from the ~235 verses that Matthew and Luke share but that are absent from Mark. Q contains mostly sayings (Beatitudes, Lord's Prayer, parables) with minimal narrative. Some scholars (notably Mark Goodacre) argue Q never existed and Luke used Matthew directly (the Farrer Hypothesis). The International Q Project published a critical edition of Q in 2000.\n\nThe Gospel of Thomas, discovered at Nag Hammadi in 1945, revived Q interest because it too is a sayings collection with no narrative frame -- demonstrating that such a genre existed in early Christianity.\n\nEach Gospel's distinctive theology: Mark -- urgency, suffering, the Messianic Secret (Jesus tells people not to reveal his identity). Matthew -- Jesus as the new Moses, fulfillment of prophecy, five major discourses, Jewish-Christian audience. Luke -- concern for the poor, women, Samaritans, and outsiders; narrative artistry; paired with Acts as a two-volume work.",
      advanced:
        "The Synoptic Problem has no consensus solution, only a dominant hypothesis with acknowledged weaknesses. Key challenges to the Two-Source Hypothesis: the 'Minor Agreements' -- roughly 700 instances where Matthew and Luke agree against Mark in small details (word changes, omissions, additions). Under the Two-Source Hypothesis, these should not exist because Matthew and Luke independently used Mark. Various explanations have been proposed: coincidental editing, textual corruption of Mark, or a 'Deutero-Mark' that both used.\n\nThe Farrer Hypothesis (Austin Farrer, 1955; revived by Mark Goodacre) eliminates Q entirely by proposing that Luke used both Mark and Matthew. This is more parsimonious (no hypothetical document) but requires explaining why Luke would have dismantled Matthew's Sermon on the Mount and scattered its material across his Gospel. Proponents argue this is exactly what a skilled author would do to integrate sources into his own narrative structure.\n\nThe Griesbach Hypothesis (Two-Gospel Hypothesis, revived by William Farmer) proposes Matthew first, Luke used Matthew, Mark conflated both. This was the dominant view before the 19th century but is now a minority position. Its main appeal: it eliminates Q and makes Mark a skilful epitomizer.\n\nRecent developments: Watson's 'The Fourfold Gospel' (2016) argues that the Gospel genre itself was a Markan invention -- Mark created the narrative Gospel form, and Matthew and Luke both worked within and against that form. The question is not just 'who copied whom' but 'what kind of literature is a Gospel and how did that genre develop?'"
    },
  },

  {
    id: "c2-02",
    slug: "q-source",
    domainId: "d2",
    name: "Q Source",
    summary:
      "The lost sayings document that Matthew and Luke both used -- if it existed.",
    lensTags: ["academic"],
    relatedConceptSlugs: ["synoptic-problem", "gospel-of-thomas"],
    relatedTextRefs: ["Matthew 5:3", "Luke 6:20"],
    layers: {
      accessible:
        "Q (from the German 'Quelle' meaning 'source') is a hypothetical document of Jesus' sayings that scholars believe Matthew and Luke both used when writing their Gospels. No copy of Q has ever been found -- it's reconstructed from roughly 235 verses that appear in both Matthew and Luke but not in Mark. Q would have been primarily a collection of Jesus' teachings: the Beatitudes, the Lord's Prayer, parables, and wisdom sayings. The discovery of the Gospel of Thomas -- another sayings collection with no narrative -- showed that this kind of document actually existed in early Christianity.",
      intermediate:
        "The International Q Project (IQP), based primarily at Claremont, published 'The Critical Edition of Q' in 2000. This reconstruction attempts to determine the original wording of Q where Matthew and Luke differ. For example, the Beatitudes -- Matthew has 'Blessed are the poor in spirit' (5:3) while Luke has 'Blessed are you poor' (6:20). Most Q scholars think Luke preserves the more original wording (shorter, more direct, second person) and Matthew spiritualized it.\n\nQ scholarship has proposed layers within Q: Q1 (wisdom sayings, optimistic), Q2 (prophetic announcements of judgment, more apocalyptic), and Q3 (narrative framing, temptation story). The Q community is hypothesized to have been a group of Jesus followers who preserved his teachings without developing a passion narrative -- suggesting that not all early Christians centered their faith on the cross.\n\nThe main argument against Q: Occam's Razor. If Luke used Matthew directly (Farrer Hypothesis), no Q is needed. The main argument for Q: Luke's treatment of the material. If Luke had Matthew in front of him, why would he systematically dismantle the Sermon on the Mount, scatter material across his Gospel, and sometimes preserve what appears to be a more original version?",
      advanced:
        "The Q debate has implications beyond source criticism. If Q existed, it represents a form of Christianity that preserved Jesus' teachings without a passion narrative -- a 'Jesus movement' focused on ethical teaching and wisdom rather than death and resurrection. This aligns with the Gospel of Thomas and challenges the assumption that kerygmatic Christianity (focused on cross and resurrection, as in Paul) was universal from the start.\n\nJohn Kloppenborg's stratigraphic analysis of Q identifies three compositional layers: (1) a sapiential collection emphasizing radical ethics and trust in God (Q1), (2) a chriae collection with prophetic announcements of judgment against 'this generation' (Q2), and (3) a narrative opening including the temptation story (Q3). This developmental model suggests Q evolved from a wisdom document into a more apocalyptic one -- possibly reflecting the Q community's experience of rejection.\n\nCritics (especially Goodacre, 'The Case Against Q,' 2002) argue that Q scholarship has become unfalsifiable -- any difficulty is explained by adding another layer to Q, and the absence of any physical evidence is explained by the document's absorption into Matthew and Luke. The debate remains genuinely open in scholarship, with significant scholars on both sides."
    },
  },

  {
    id: "c2-03",
    slug: "pauline-authorship",
    domainId: "d2",
    name: "Pauline Authorship Debates",
    summary:
      "Seven letters are definitely Paul's. Six more claim to be but probably aren't. Why it matters.",
    lensTags: ["academic", "protestant"],
    relatedConceptSlugs: ["canon-formation", "pauline-authorship"],
    relatedTextRefs: ["Romans 1:1", "1 Timothy 1:1"],
    layers: {
      accessible:
        "Paul wrote letters to early Christian communities, and 13 letters in the New Testament bear his name. But scholars have determined that only 7 were definitely written by Paul himself: Romans, 1 Corinthians, 2 Corinthians, Galatians, Philippians, 1 Thessalonians, and Philemon. The other 6 (Ephesians, Colossians, 2 Thessalonians, 1 Timothy, 2 Timothy, Titus) are disputed -- they may have been written by followers of Paul after his death, a common practice in the ancient world called pseudepigraphy. This matters because the undisputed and disputed letters say different things about women in leadership, church structure, and the nature of salvation.",
      intermediate:
        "The evidence for pseudepigraphy in the Pastoral Epistles (1-2 Timothy, Titus) is particularly strong. Vocabulary: over 300 words in the Pastorals appear nowhere else in Paul's undisputed letters, including many that are common in 2nd-century Greek. Theology: the Pastorals assume a hierarchical church structure (bishops, elders, deacons) that doesn't match the charismatic, Spirit-driven communities in Paul's genuine letters. They also prohibit women from teaching (1 Timothy 2:12), whereas the undisputed Paul names women as co-workers, deacons, and apostles (Junia in Romans 16:7, Phoebe the deacon in Romans 16:1, Prisca as co-worker).\n\nEphesians and Colossians are more debated. Ephesians reads like a theological essay rather than a letter to a specific community (some early manuscripts omit 'in Ephesus' from 1:1). Its Christology is more 'cosmic' than Paul's undisputed letters. Colossians is closer to Paul's style but contains the hymn in 1:15-20 that many scholars think pre-dates the letter.\n\nPseudepigraphy was not considered dishonest in antiquity. Writing in the name of your teacher was a way of extending their authority and legacy. The question is not 'who forged these?' but 'what theological developments do they represent in the generations after Paul?'",
      advanced:
        "The authorship debates have profound implications for how we read Paul. The 'radical Paul' of the undisputed letters -- egalitarian, charismatic, apocalyptic, expecting Christ's imminent return -- is substantially different from the 'domesticated Paul' of the Pastorals -- hierarchical, concerned with respectability, accommodating to Roman social norms.\n\nThis difference is evident on women's roles. Undisputed Paul: 'There is no longer male and female; for all of you are one in Christ Jesus' (Galatians 3:28). Disputed Paul: 'I permit no woman to teach or to have authority over a man; she is to keep silent' (1 Timothy 2:12). If both are equally 'Paul,' the contradiction is insoluble. If the Pastorals represent a later generation using Paul's name to legitimate a more conservative church order, the development is historically explicable.\n\nThe New Perspective on Paul (E.P. Sanders, James Dunn, N.T. Wright) has further complicated matters by arguing that even the undisputed Paul has been misread through a Reformation lens. 'Works of the law' in Paul may refer not to human merit-earning but to Jewish ethnic identity markers (circumcision, food laws, sabbath). This reframes the Protestant-Catholic debate and suggests that Paul's primary concern was Gentile inclusion, not individual salvation mechanics.\n\nFor the reader: the question is not whether the Pastorals are 'in the Bible' (they are) but what happens when we recognize that 'Paul' in the NT is actually multiple voices spanning perhaps 50 years of development. The canon preserved a debate within the Pauline tradition, not a single authoritative voice."
    },
  },

  {
    id: "c2-04",
    slug: "canon-formation",
    domainId: "d2",
    name: "Canon Formation: How We Got the Bible",
    summary:
      "Who decided what counts as God's word -- and why? The Bible is a curated collection, not a complete one. What was excluded tells you as much as what was included.",
    lensTags: ["academic", "protestant", "catholic", "orthodox"],
    relatedConceptSlugs: ["gospel-of-thomas", "nag-hammadi", "council-of-nicaea"],
    relatedTextRefs: ["2 Peter 3:15-16", "Luke 1:1-4", "Revelation 22:18-19"],
    layers: {
      accessible:
        "The Bible did not fall from heaven as a finished book. It was assembled over centuries by human beings who made choices about what to include and what to exclude -- and those choices were not neutral.\n\nFor the first 300 years of Christianity, there was no Bible as we know it. Different communities used different texts. A church in Rome might read the Shepherd of Hermas as Scripture. A church in Syria might use the Gospel of Thomas. A church in Egypt might treasure the Didache as much as any letter of Paul's. All of these communities considered themselves faithful followers of Jesus. None of them had a 'Bible' with a table of contents.\n\nThe 27-book New Testament we have today was not formally listed until 367 CE, when Bishop Athanasius of Alexandria published his Easter letter naming exactly these books -- and ordering the destruction of all others. Not their removal from the reading list. Their destruction. The same year, monks near Nag Hammadi in Egypt buried their copies of excluded texts in sealed jars to save them from being burned.\n\nThis is the question most people never ask: who decided what is 'God's word,' what criteria did they use, and what did the excluded texts threaten?",
      intermediate:
        "The criteria for inclusion were never formally defined, but three principles generally operated: apostolic origin (was it written by an apostle or their associate?), widespread use (did multiple regions accept it?), and theological consistency (did it conform to what church leaders already believed?). That third criterion is the one that matters most -- and it is circular. The texts that confirmed the emerging institutional theology were declared Scripture. The texts that challenged it were declared heretical. 'Orthodoxy' is simply the theology of whoever won the power struggle.\n\nConsider what was excluded and why. The Gospel of Thomas presents a Jesus who says the kingdom of God is already within you, no priest or institution required. Excluded. The Didache shows a Christianity focused on Jesus's ethical teaching with no theology of the cross. Excluded. The Shepherd of Hermas was so popular it was included in the Codex Sinaiticus (one of the oldest complete Bibles) -- but was eventually cut because its theology was too 'low,' too focused on practical morality rather than institutional authority.\n\nMeanwhile, what was included? Books that supported the emerging power structure. Texts that centered salvation on the institution's sacraments. Letters (like the Pastoral Epistles, which most scholars agree Paul did not write) that told women to be silent, established hierarchical church governance, and domesticated the radical egalitarianism of Jesus and the early Paul.\n\nThe Old Testament canon is even more revealing. Protestants accept 39 books. Catholics accept 46. Orthodox churches accept more. The Ethiopian church includes 1 Enoch and Jubilees. Luther wanted to remove James, Jude, Hebrews, and Revelation from the New Testament because they contradicted his theology. The 'word of God' has a different table of contents depending on who you ask.",
      advanced:
        "Recent scholarship (Lee Martin McDonald, Harry Gamble, John Barton) has reframed the question from 'when was the canon closed?' to 'what power dynamics drove the closing?' Barton demonstrates that 'Scripture' (text treated as authoritative) preceded 'canon' (closed, official list) by centuries. The move from open Scripture to closed canon was a move from theological exploration to institutional control. An open collection invites conversation. A closed canon says: this is the final word. Stop asking questions.\n\nThe political motivations are visible at every stage. Athanasius's 367 letter coincides with his campaign against 'heretical' communities that threatened his authority. The Muratorian Fragment (c. 170-200 CE), the earliest surviving canonical list, explicitly justifies its choices in terms of institutional authority, not spiritual discernment. Eusebius of Caesarea (c. 324 CE) categorized texts as 'recognized,' 'disputed,' or 'rejected' -- and his 'rejected' category included texts that communities had read as Scripture for generations.\n\nThe most honest way to understand the Bible is as a curated anthology. It was assembled by editors with theological commitments, institutional loyalties, and political pressures. This does not mean it is worthless -- anthologies can be extraordinary. But it means the Bible is not a complete record of early Christian thought. It is the record that survived the editorial process. The texts that were burned, buried, or forgotten represent voices that were silenced, not voices that had nothing to say.\n\nWhat was stolen: the reader's right to encounter the full diversity of early Christian thought and make their own judgments. The canon formation process did not preserve the best texts. It preserved the texts that served the institution that was doing the preserving. Recognizing this does not destroy the Bible's value -- it restores the reader's authority to engage with it honestly."
    },
    honestAnalysis:
      "The Bible is not a complete collection of divinely selected texts. It is a curated anthology assembled by institutional authorities who included what supported their theology and destroyed what threatened it. The excluded texts -- Thomas, the Didache, the Shepherd of Hermas, dozens of others -- were not excluded because they were false. They were excluded because they did not need the institution to function. A faith that does not require a hierarchy is the one thing a hierarchy cannot tolerate.",
  },

  {
    id: "c2-05",
    slug: "historical-jesus",
    domainId: "d2",
    name: "The Historical Jesus: What Can We Actually Know?",
    summary:
      "The quest for the 'historical Jesus' tries to separate what Jesus actually said and did from what the early church said about him.",
    lensTags: ["academic", "protestant"],
    relatedConceptSlugs: ["synoptic-problem", "q-source", "gospel-of-thomas"],
    relatedTextRefs: ["Mark 1:14-15", "Luke 6:20-26", "Matthew 5:1-12"],
    layers: {
      accessible:
        "Here is the problem: everything we know about Jesus was written by people who already believed he was the risen Messiah. The earliest gospel (Mark) was written around 70 CE, roughly 40 years after Jesus died. That is 40 years of oral tradition, theological development, and community needs shaping the stories. So scholars ask: can we get behind the texts to the actual historical person? The short answer is: somewhat, but with humility. Most historians agree on a core portrait: Jesus was a Jewish teacher from Galilee who announced the coming 'kingdom of God,' attracted followers, had a reputation as a healer, clashed with religious authorities, was crucified by Rome under Pontius Pilate around 30 CE, and his followers claimed he was risen from the dead. Beyond that, almost everything is debated.",
      intermediate:
        "The 'Quest for the Historical Jesus' has gone through three phases. The First Quest (19th century, Albert Schweitzer) tried to reconstruct a historical biography of Jesus. Schweitzer demolished this effort in 1906, showing that every 'historical Jesus' looked suspiciously like the scholar who found him. The New Quest (1950s-70s, Ernst Kasemann, Gunther Bornkamm) focused on the continuity between the historical Jesus and the kerygma (proclaimed Christ). The Third Quest (1980s-present, E.P. Sanders, John Meier, N.T. Wright, Bart Ehrman) emphasizes Jesus' Jewishness and his place within Second Temple Judaism.\n\nScholars use several 'criteria of authenticity' to assess whether a particular saying or deed likely goes back to Jesus: The Criterion of Embarrassment (things the early church would not have invented because they are awkward -- e.g., Jesus' baptism by John, implying Jesus needed purification). The Criterion of Multiple Attestation (things found in independent sources -- Mark, Q, Thomas, Paul). The Criterion of Dissimilarity (things that do not match either typical Judaism or typical early Christianity). The Criterion of Coherence (things that fit with material already established as authentic).\n\nThe major debate concerns what kind of Jew Jesus was. E.P. Sanders sees him as an eschatological prophet announcing the end of the world. John Dominic Crossan sees a wisdom teacher and social revolutionary. N.T. Wright sees him as Israel's Messiah inaugurating God's kingdom. Amy-Jill Levine emphasizes that Jesus' teachings are intelligible within Judaism without recourse to a unique 'Christian' framework. The Jesus Seminar (Robert Funk, John Dominic Crossan) controversially voted with colored beads on the authenticity of each saying, concluding that only about 18% of the words attributed to Jesus in the Gospels were likely spoken by him.",
      advanced:
        "The epistemological challenges of historical Jesus research are formidable. Dale Allison Jr. ('The Historical Christ and the Theological Jesus') argues that we can know the 'gist' of Jesus' teaching (recurring patterns and themes) but cannot with confidence assign individual sayings to the historical Jesus. The 'memory approach' (Chris Keith, Anthony Le Donne, Rafael Rodriguez) has shifted the conversation from 'authentic vs. inauthentic' sayings to how communities remembered and refracted Jesus through their social circumstances.\n\nOne of the most important insights of the Third Quest is that Jesus cannot be understood apart from first-century Judaism. The anachronistic habit of reading Jesus against Judaism (as if he were a critic of his own religion) produces a distorted portrait. Jesus was a Jew, teaching Jews, about Jewish hopes, using Jewish scripture. His 'newness' was not the rejection of Judaism but a particular interpretation of it.\n\nThe 'Criteria of Authenticity' have come under heavy criticism. The Criterion of Dissimilarity, if strictly applied, produces a Jesus who is neither Jewish nor Christian -- a historical impossibility. Multiple attestation assumes we can identify 'independent' sources, which is itself debatable. The trend in current scholarship is away from criteria-based approaches and toward holistic reconstruction: what total portrait of Jesus best explains the evidence?"
    },
  },

  {
    id: "c2-06",
    slug: "revelation-apocalyptic",
    domainId: "d2",
    name: "Revelation: Not What You Think It Is",
    summary:
      "The Book of Revelation is not a prediction of the future. It is a coded resistance letter to Christians living under Roman imperial oppression.",
    lensTags: ["academic", "protestant", "catholic"],
    relatedConceptSlugs: ["eschatology", "canon-formation"],
    relatedTextRefs: ["Revelation 13", "Revelation 17-18", "Daniel 7"],
    layers: {
      accessible:
        "Most people read Revelation as a roadmap for the end of the world: rapture, Antichrist, Armageddon, second coming. This reading is popular but historically wrong. Revelation is an example of 'apocalyptic literature' -- a genre common in Judaism from 200 BCE to 200 CE. Apocalyptic writing uses symbolic imagery (beasts, numbers, cosmic battles) to address present political crises in coded language. The 'beast' of Revelation 13 is not a future world leader -- it is the Roman Empire. The number 666 is not a mystery: in Hebrew numerology (gematria), it spells 'Nero Caesar.' The 'whore of Babylon' is Rome, the city built on seven hills (17:9). Revelation was written to Christians being persecuted by Rome, telling them: Rome looks powerful, but God will prevail. Hold on.",
      intermediate:
        "Revelation belongs to a specific literary genre (apocalypse) with identifiable conventions: heavenly journeys, symbolic numbers, cosmic dualism (good vs. evil), animal imagery, and a narrative arc from present suffering to future divine vindication. Other Jewish apocalypses include Daniel 7-12, 1 Enoch, 4 Ezra, and 2 Baruch. Reading Revelation without knowing the genre is like reading political satire literally.\n\nThe author identifies himself as 'John' (1:1), but this is almost certainly not the apostle John or the author of the Fourth Gospel. The Greek style is dramatically different -- Revelation's Greek is rough and 'Hebraized,' while the Gospel of John is polished. The early church was divided on the book's authorship and canonicity. The Eastern church excluded it from its lectionary for centuries.\n\nKey symbols decoded: The 'Lamb who was slain' (Jesus) conquers not through violence but through sacrificial death -- subverting Roman imperial power theology. The 'mark of the beast' parodies Roman imperial coinage that bore the emperor's image and claims to divinity. The 'millennium' (20:1-6) has generated three major interpretive frameworks: premillennialism (Christ returns before a literal 1,000-year reign), postmillennialism (the church progressively establishes God's kingdom before Christ returns), and amillennialism (the 1,000 years is symbolic of the church age). All three have ancient pedigrees; none is obviously 'correct.'\n\nThe 'rapture' theology popularized by the Left Behind novels derives from John Nelson Darby (1830s), not from the text itself. 1 Thessalonians 4:17 ('caught up to meet the Lord in the air') uses the Greek word apantesis, a technical term for citizens going out to greet an arriving king and then accompanying him back into the city -- not escaping from the city. The rapture concept is a 19th-century innovation.",
      advanced:
        "The political theology of Revelation has been recovered by scholars like Richard Bauckham ('The Theology of the Book of Revelation'), Elisabeth Schussler Fiorenza ('Revelation: Vision of a Just World'), and Brian Blount ('Can I Get a Witness?'). Revelation is fundamentally a critique of empire: economic exploitation (chapter 18's lament over Babylon's luxury trade includes 'bodies and souls of men' -- the slave trade), military violence, and the idolatrous claim of the state to ultimate loyalty.\n\nThe 'New Jerusalem' of chapters 21-22 is notable for what it does NOT contain: no temple (21:22), because God's presence permeates everything. The city descends from heaven to earth -- the goal is not escape from the material world but the renewal of the material world. This 'earthy' eschatology stands in contrast to popular Christian theology that emphasizes 'going to heaven when you die.'\n\nFor communities under oppression, Revelation has been a text of resistance and hope. Enslaved African Americans, Latin American liberation communities, and South Korean minjung theologians have read Revelation as affirming that empires fall and God sides with the oppressed. The danger of apocalyptic literature is that it can also be used to demonize enemies and justify violence -- which is why responsible interpretation requires understanding the genre's function: not to identify specific enemies but to affirm that no empire, no matter how powerful, has the last word."
    },
  },

  {
    id: "c2-07",
    slug: "paul-vs-jesus",
    domainId: "d2",
    name: "Paul vs. Jesus: Did Paul Invent Christianity?",
    summary:
      "Paul never met Jesus. He wrote before the Gospels existed. His theology looks nothing like Jesus' teaching. The uncomfortable possibility: institutional Christianity reflects Paul's religion more than Jesus's.",
    lensTags: ["academic", "protestant"],
    relatedConceptSlugs: ["pauline-authorship", "historical-jesus", "synoptic-problem"],
    relatedTextRefs: ["Galatians 2:15-21", "Romans 3:21-26", "Mark 1:15"],
    layers: {
      accessible:
        "Jesus taught about the kingdom of God. He told parables about seeds and banquets, about a father welcoming home a lost son, about a Samaritan stopping to help a stranger. He said the kingdom is here, among you, within you. He said love your enemies. He said the last will be first.\n\nPaul taught about justification by faith through the death and resurrection of Christ. He wrote dense theological arguments about law and grace, flesh and spirit, the cosmic significance of the cross. He built a theological system centered on believing the right things about Jesus's death.\n\nThese do not sound like the same religion. And the uncomfortable truth is that the Christianity most people practice today -- focused on correct belief, substitutionary atonement, the cross as the center of faith, salvation as a transaction -- looks far more like Paul's theology than Jesus's teaching.\n\nPaul never met Jesus. He never heard a parable. He never walked with Jesus through Galilee. He never sat at the table when Jesus ate with sinners. His entire knowledge of Jesus came from a visionary experience on the road to Damascus and brief encounters with people who had known Jesus. And yet his theology -- not Jesus's actual teaching -- became the foundation of the institutional church. The religion got remade by someone who never met the founder.",
      intermediate:
        "The facts are uncomfortable. Paul's letters (49-62 CE) are the earliest Christian documents. They predate every Gospel by 15-30 years. Paul explicitly claims he did not receive his gospel from any human (Galatians 1:11-12). He met Jesus's actual disciples only briefly (Galatians 1:18-19) and publicly confronted them when they disagreed with him (Galatians 2:11-14). He rarely quotes Jesus directly -- in all his letters, he cites Jesus's actual words only three or four times.\n\nConsider what Paul adds that Jesus never taught: justification by faith (a legal metaphor -- God declares you righteous), the body of Christ (the church as a mystical organism), the sharp contrast between flesh and spirit, and the cross as cosmic atonement -- the idea that Jesus's death was a sacrifice that satisfied God's justice. Jesus never described his death this way. He talked about the kingdom of God. Paul talks about the cross.\n\nNow consider what Paul ignores that Jesus emphasized: the kingdom of God as a present reality (Paul mentions it but does not develop it), love of enemies (Paul's ethics are practical but lack Jesus's radical edge), care for the poor as the center of faith (Paul collects money for Jerusalem but does not frame poverty as the core theological issue Jesus made it), and Jesus's relentless critique of religious hypocrisy (Paul builds exactly the kind of theological system Jesus spent his ministry subverting).\n\nOf the 13 letters attributed to Paul, only 7 are genuinely his. The other 6 (including 1-2 Timothy and Titus) were written by later followers using Paul's name. These pseudepigraphal letters are even further from Jesus: they tell women to be silent, establish rigid church hierarchy, and domesticate the egalitarianism of both Jesus and the real Paul. The institutional church was built not just on Paul's theology but on a later, more conservative version of Paul's theology that Paul himself might not have recognized.",
      advanced:
        "The New Perspective on Paul (Sanders, Dunn, Wright) has reframed the question by showing that Paul was not opposing 'works-righteousness' (the Lutheran reading) but arguing about who belongs in the covenant community. If this is correct, Paul and Jesus share a deeper concern: both are arguing that God's people are being reconstituted, that the boundaries are being redrawn, that insiders are becoming outsiders and outsiders are becoming insiders. The deep structure -- God doing something that changes who belongs -- is shared.\n\nThe 'apocalyptic Paul' school (Martyn, de Boer, Gaventa) pushes further: Paul is a Jewish apocalypticist who believes Jesus's death and resurrection ended the old cosmic order. This is not a self-help program. It is a claim about the structure of reality. On this reading, Paul is closer to Jesus's apocalyptic proclamation of the kingdom than the domesticated Paul of the Pastoral Epistles.\n\nBut even these sympathetic readings cannot fully resolve the tension. Jesus's religion is embodied, relational, and rooted in concrete acts of love: feeding people, healing people, eating with outcasts, forgiving enemies to their faces. Paul's religion is theological, systematic, and rooted in correct belief about a cosmic event. Jesus says: do this. Paul says: believe this. The institutional church followed Paul, because institutions can administer beliefs (creeds, catechisms, theological tests) far more easily than they can administer the Sermon on the Mount.\n\nWhat was stolen: a faith centered on how you live rather than what you believe. Jesus's teaching is about practice -- feeding the hungry, welcoming the stranger, forgiving without limit, loving enemies. Paul's theology is about doctrine -- justification, atonement, the mechanics of salvation. The church built itself on doctrine because doctrine can be controlled, tested, and enforced. Practice is harder to institutionalize. You cannot build a bureaucracy on 'love your enemies.' You can build one on 'believe the right things about the cross.' And so the religion of Jesus became the religion about Jesus -- and the man who never met him became its primary architect.\n\nWhat love actually looks like: recovering Jesus's original emphasis. Not abandoning Paul -- his letters contain genuine insight and beauty. But centering the faith where Jesus centered it: on how you treat the person in front of you. On feeding the hungry, welcoming the stranger, forgiving without limit, loving the people who hate you. These are things you can start doing today, with no theology degree, no institutional permission, no creed to sign. That is the faith Jesus taught. It was never lost. It was just buried under the theology built on top of it."
    },
    honestAnalysis:
      "The religion most Christians practice looks more like Paul's theology than Jesus's teaching. This is not because Paul was dishonest. It is because his framework was useful to institutions in a way Jesus's teaching was not. But Jesus's original emphasis -- on practice over belief, on love over doctrine, on how you live rather than what you affirm -- is still there, underneath it all. Recovering it does not require leaving the church. It requires returning to the teacher the church claims to follow.",
  },

  {
    id: "c2-08",
    slug: "gospel-of-john",
    domainId: "d2",
    name: "The Gospel of John: The Odd One Out",
    summary:
      "John's Gospel looks nothing like the other three. Different chronology, different style, different theology. It may be the most theological and the least historical.",
    lensTags: ["academic", "contemplative"],
    relatedConceptSlugs: ["synoptic-problem", "historical-jesus", "christology"],
    relatedTextRefs: ["John 1:1-18", "John 14:6", "John 20:28"],
    layers: {
      accessible:
        "Matthew, Mark, and Luke tell roughly the same story in roughly the same way (that is why they are called the 'Synoptic' Gospels -- they 'see together'). Then there is John, and it is a different world. In the Synoptics, Jesus teaches in short parables and sayings. In John, Jesus delivers long philosophical speeches about himself ('I am the bread of life,' 'I am the light of the world'). In the Synoptics, the cleansing of the Temple happens in the last week. In John, it happens at the beginning. In the Synoptics, Jesus never clearly claims to be God. In John, he says 'Before Abraham was, I am' and 'I and the Father are one.' The Synoptics are more Jewish and more earthy. John is more cosmic and more mystical. Scholars generally consider the Synoptics more historically reliable for the events of Jesus' life, while John represents a deeply theological meditation on what Jesus means.",
      intermediate:
        "The Fourth Gospel was likely written around 90-100 CE by the 'Johannine community' -- a group of Christians whose theological development is visible across the Gospel, the three Epistles of John, and (debatably) Revelation. The author identifies himself as 'the beloved disciple' (John 21:20-24), a figure unique to this Gospel who may be a real individual or a symbolic representative of the community's founder.\n\nJohn's Christology is the highest in the New Testament. The prologue (1:1-18) identifies Jesus with the pre-existent Logos (Word) who was 'with God' and 'was God' before creation. The seven 'I am' statements (bread of life, light of the world, gate, good shepherd, resurrection and life, way/truth/life, true vine) use the divine name formula (ego eimi, echoing Exodus 3:14). Thomas's confession 'My Lord and my God' (20:28) is the most explicit christological statement in any Gospel.\n\nJohn also has a developed dualism (light/darkness, above/below, spirit/flesh) that some scholars connect to Gnostic thought, though the Gospel ultimately rejects Gnosticism by insisting that 'the Word became flesh' (1:14). The Johannine community may have been in dialogue with early Gnostic movements.\n\nThe 'signs' (semeia) in John -- water to wine, healing the official's son, healing at Bethesda, feeding 5,000, walking on water, healing the blind man, raising Lazarus -- serve as symbolic demonstrations of Jesus' identity, not just miracles. Each sign points to a deeper theological claim: Jesus replaces Jewish institutions (water purification, Temple, manna, Sabbath, light, death itself).",
      advanced:
        "The relationship between John and the Synoptics remains debated. Some scholars (C.H. Dodd, 'Historical Tradition in the Fourth Gospel') argue that John preserves independent historical traditions (some of which may be more accurate than the Synoptics -- the chronology of the crucifixion, for example). Others see John as theologically rewriting Synoptic material for a later community.\n\nJ. Louis Martyn's 'History and Theology in the Fourth Gospel' proposed that John's Gospel operates on two levels simultaneously: the narrative level (Jesus' ministry) and the community level (the Johannine community's expulsion from the synagogue, reflected in passages like 9:22 and 16:2). The 'Jews' (hoi Ioudaioi) in John represent not the Jewish people as a whole but the specific synagogue authorities in conflict with the Johannine community. This two-level reading has been enormously influential and helps address the troubling anti-Jewish potential of the Gospel.\n\nThe Fourth Gospel's reception history is complex. Gnostics embraced it (the Valentinian Heracleon wrote the first commentary on John). The mainstream church initially hesitated, then adopted it as the most theologically sophisticated portrait of Christ. In modern theology, Rudolf Bultmann's commentary on John remains a landmark, reading it through an existentialist lens as an encounter with the 'word' that demands decision. More recently, scholars like Adele Reinhartz, Mary Coloe, and Jean Zumstein have brought literary, feminist, and narratological approaches that reveal the Gospel's sophistication as a literary and theological work."
    },
  },
];
