import type { Concept } from "./types";

export const domain4Concepts: Concept[] = [
  {
    id: "c4-01",
    slug: "biblical-hebrew",
    domainId: "d4",
    name: "Biblical Hebrew: The Language Behind the Old Testament",
    summary:
      "The ancient Semitic language of the Hebrew Bible, with its root-based system, verbal aspect, and layers of meaning that no English translation can fully capture.",
    lensTags: ["academic", "protestant", "catholic", "jewish"],
    relatedConceptSlugs: ["septuagint", "textual-criticism"],
    relatedTextRefs: ["Genesis 1:1", "Psalm 23", "Isaiah 7:14"],
    layers: {
      accessible:
        "Biblical Hebrew is a Semitic language -- related to Arabic and Aramaic -- that works nothing like English. It reads right to left. It has no vowels in its original written form (vowel marks were added centuries later by the Masoretes). And its meaning system is built on three-letter roots: the root K-T-B means 'write,' and different vowel patterns and prefixes create 'writer,' 'book,' 'writing,' 'desk,' all from the same root. This means Hebrew words carry webs of association that English translations flatten. The word 'ruach' means wind, breath, AND spirit -- all at once. When Genesis says God's 'ruach' moved over the waters, it is simultaneously wind, breath, and spirit. No English word captures all three.",
      intermediate:
        "Hebrew verbal system does not work on tense (past/present/future) the way English does. Instead, it operates on aspect -- whether an action is complete (perfect) or incomplete (imperfect). This creates deliberate ambiguity. In Exodus 3:14, when God says 'ehyeh asher ehyeh,' the standard translation 'I AM WHO I AM' freezes what is actually an imperfect verb. It could equally be 'I will be what I will be' or 'I am becoming what I am becoming.' God's self-revelation is grammatically open-ended.\n\nHebrew poetry works through parallelism rather than rhyme. Psalm 19: 'The heavens declare the glory of God / the sky proclaims his handiwork.' The second line does not repeat but advances the first -- Robert Alter calls this 'heightening.' This is why Hebrew poetry must be read in couplets, not single lines.\n\nThe Hebrew word 'hesed' (often translated 'lovingkindness' or 'mercy') actually means covenantal loyalty -- the fierce, committed love that persists even when the other party breaks the agreement. It appears 248 times in the Hebrew Bible and is arguably its most important theological word. No single English translation works.",
      advanced:
        "The Masoretic Text (MT), standardized between the 7th-10th centuries CE by the Masoretes of Tiberias, introduced the nikudot (vowel pointing system) to a consonantal text that had been read without vowels for over a millennium. This means every vowel in the Hebrew Bible represents an interpretive tradition, not a neutral transcription. The consonants YHWH could theoretically be vocalized differently than 'Yahweh' -- indeed, the Masoretes deliberately mispointed it with the vowels of 'Adonai' to prevent pronunciation.\n\nThe Dead Sea Scrolls (250 BCE - 70 CE) revealed that the MT was not the only Hebrew text tradition. The Scrolls contain texts closer to the Septuagint (LXX) than the MT, suggesting multiple Hebrew textual families existed simultaneously. Jeremiah in the Scrolls is about 15% shorter than the MT Jeremiah -- this is not scribal error but a different edition of the book.\n\nKey interpretive issues in Hebrew: (1) 'Almah' in Isaiah 7:14 means 'young woman,' not 'virgin' (which would be 'betulah'). The LXX translated it as 'parthenos' (virgin), which Matthew then quoted. This is a translation creating a theological claim. (2) 'Nephesh' is consistently mistranslated as 'soul' when it actually means 'living being' or 'throat/appetite' -- there is no body-soul dualism in Hebrew anthropology. (3) 'Olam' means 'age' or 'long duration,' not 'eternity' in the philosophical sense -- this matters for every passage about 'everlasting' punishment."
    },
    honestAnalysis:
      "Most Christians read the Old Testament only in translation and miss the linguistic texture entirely. The persistent confusion between Hebrew concepts and Greek philosophical categories (nephesh/soul, olam/eternity, sheol/hell) has shaped centuries of theology in directions the original authors did not intend.",
  },

  {
    id: "c4-02",
    slug: "koine-greek",
    domainId: "d4",
    name: "Koine Greek: The Language of the New Testament",
    summary:
      "The common Greek of the Roman Empire in which every New Testament book was written -- not classical Attic Greek but the everyday language of commerce, letters, and ordinary people.",
    lensTags: ["academic", "protestant", "catholic", "orthodox"],
    relatedConceptSlugs: ["textual-criticism", "pauline-authorship"],
    relatedTextRefs: ["John 1:1", "Romans 3:23", "Philippians 2:5-11"],
    layers: {
      accessible:
        "Every book of the New Testament was written in Koine Greek -- 'koine' meaning 'common.' This was not the elegant literary Greek of Plato and Homer but the everyday language spoken across the Roman Empire after Alexander the Great spread Greek culture. Think of it as the difference between Shakespeare's English and a modern newspaper. This matters because the New Testament authors were not writing high literature (with a few exceptions like Hebrews). Paul's letters sound like passionate, sometimes rambling letters from someone who thinks faster than he writes. Mark's Gospel uses 'and immediately' over 40 times -- it reads like an excited oral storytelling. When translations make the Bible sound formal and elevated, they are adding a register the original did not have.",
      intermediate:
        "Greek has features that create theological precision impossible in English. The definite article: John 1:1 says 'the Word was with THE God (ton theon), and the Word was God (theos, no article).' This distinction is why scholars debate whether John means 'the Word was God' (identity) or 'the Word was divine' (quality). The article makes a theological difference.\n\nGreek verb tenses encode aspect, not just time. The aorist tense presents an action as a single complete event. The present tense presents it as ongoing. When Paul says 'all have sinned' (Romans 3:23), the aorist 'hemarton' treats sin as a completed fact of the human condition. When John says 'the one who practices sin' (1 John 3:9), the present participle implies ongoing, habitual action. This distinction matters for whether individual sins or a life orientation is meant.\n\nThe word 'agape' (love) is often claimed to be a uniquely Christian invention for divine love. This is a myth. Agape appears in secular Greek before Christianity. What the New Testament authors did was fill an existing word with new theological content -- particularly the idea that divine love is self-giving and directed toward the undeserving.",
      advanced:
        "The Greek text of the New Testament exists in roughly 5,800 manuscripts, no two of which are identical. Textual criticism -- the discipline of reconstructing the most likely original text -- is one of the most rigorous fields in biblical scholarship. The major critical editions (Nestle-Aland, now in its 28th edition, and the United Bible Societies text, 5th edition) represent scholarly consensus but involve thousands of judgment calls.\n\nSignificant textual variants: The ending of Mark (16:9-20) is almost certainly a later addition -- the earliest manuscripts end abruptly at 16:8 with the women fleeing the tomb in fear. The Pericope Adulterae (John 7:53-8:11, the woman caught in adultery) does not appear in the earliest manuscripts and floats to different locations in various manuscripts. The Comma Johanneum (1 John 5:7-8, the only explicit Trinitarian formula) is a medieval Latin addition absent from all Greek manuscripts before the 16th century.\n\nParticiples in Greek carry enormous theological weight. Philippians 2:6 -- 'who, being (hyparchon, present participle) in the form of God, did not consider equality with God something to be grasped (harpagmon).' The participial construction 'being in the form' implies continuous state, not a past condition. And 'harpagmon' is a hapax legomenon (appears only once in the NT), making its precise meaning debated: does it mean Christ did not grasp at equality he did not have, or did not cling to equality he already possessed? The entire Christological framework shifts depending on which reading you adopt."
    },
  },

  {
    id: "c4-03",
    slug: "textual-criticism",
    domainId: "d4",
    name: "Textual Criticism: Reconstructing the Original Text",
    summary:
      "The scholarly discipline of comparing thousands of ancient manuscripts to determine what the biblical authors most likely originally wrote.",
    lensTags: ["academic"],
    relatedConceptSlugs: ["biblical-hebrew", "koine-greek", "dead-sea-scrolls"],
    relatedTextRefs: ["Mark 16:9-20", "John 7:53-8:11", "1 John 5:7-8"],
    layers: {
      accessible:
        "We do not have any original manuscripts of any biblical book. What we have are copies of copies of copies, made by hand over centuries before the printing press. Textual criticism is the discipline of comparing these thousands of copies to figure out what the original most likely said. Most differences between manuscripts are trivial (spelling errors, word order changes). But some are significant: the ending of Mark's Gospel, the story of the woman caught in adultery in John, and the only explicit Trinitarian formula in 1 John are all passages that probably were not in the original texts. This does not mean the Bible is unreliable -- it means we can be honest about its transmission history, which actually makes it more trustworthy, not less.",
      intermediate:
        "Textual critics use several principles to evaluate variants. 'Lectio difficilior potior' (the harder reading is more likely original) assumes scribes tended to smooth out difficulties rather than create them. 'Lectio brevior potior' (the shorter reading is more likely original) assumes scribes added clarifications rather than deleted text. External evidence (age and geographical spread of manuscripts) is weighed alongside internal evidence (what the author was likely to have written).\n\nFor the New Testament: ~5,800 Greek manuscripts, ~10,000 Latin manuscripts, plus Syriac, Coptic, and other versions. The earliest substantial papyrus (P52) dates to around 125 CE, within decades of John's composition. The great uncial codices (Sinaiticus, Vaticanus, Alexandrinus) date to the 4th-5th centuries.\n\nFor the Hebrew Bible: the Masoretic Text tradition dominates, but the Dead Sea Scrolls (dating 250 BCE - 70 CE) revealed that the Masoretic Text was one of several textual families. The Samaritan Pentateuch and the Septuagint (Greek translation) sometimes preserve readings older than the MT.",
      advanced:
        "Bart Ehrman ('The Orthodox Corruption of Scripture,' 1993) demonstrated that some textual variants were theologically motivated -- scribes altered texts to support orthodox Christology against adoptionist, docetic, or separationist heresies. Examples: Luke 3:22 in some manuscripts has the voice at Jesus' baptism say 'You are my Son, today I have begotten you' (adoptionist reading) rather than 'You are my beloved Son, in whom I am well pleased' (orthodox reading). The 'orthodox' reading won in the manuscript tradition.\n\nThe Coherence-Based Genealogical Method (CBGM), developed by the Institut fur Neutestamentliche Textforschung in Munster, uses computational analysis to map textual relationships beyond simple family trees. It has been applied to the Catholic Epistles in the NA28 edition, resulting in several changes from NA27. This method represents the most significant methodological advance in NT textual criticism in decades.\n\nFor the OT: Emanuel Tov's work on the Dead Sea Scrolls established that the textual situation is far more complex than a single 'original' text. Some biblical books may never have had a single authoritative form -- Jeremiah existed in at least two editions (a shorter proto-LXX form and a longer proto-MT form), suggesting editorial expansion rather than a fixed original."
    },
    honestAnalysis:
      "Textual criticism is the most empirically grounded of all biblical disciplines. Its findings are rarely comfortable for those who hold a doctrine of biblical inerrancy, but they are also rarely as dramatic as skeptics suggest. The vast majority of the biblical text is well-established. The significant variants, while theologically interesting, do not undermine any central Christian doctrine.",
  },

  {
    id: "c4-04",
    slug: "aramaic-of-jesus",
    domainId: "d4",
    name: "The Aramaic of Jesus: His Actual Words",
    summary:
      "Jesus spoke Aramaic. The Gospels are in Greek. Every word attributed to Jesus is already a translation. What gets lost?",
    lensTags: ["academic", "contemplative"],
    relatedConceptSlugs: ["koine-greek", "biblical-hebrew", "historical-jesus"],
    relatedTextRefs: ["Mark 5:41", "Mark 7:34", "Mark 15:34", "Matthew 6:9-13"],
    layers: {
      accessible:
        "Jesus grew up in rural Galilee speaking Aramaic, a Semitic language related to Hebrew. He may also have known some Greek (the common language of commerce) and Hebrew (the language of scripture). But his daily language, his teaching language, was Aramaic. The Gospels, however, are written entirely in Greek. This means every saying attributed to Jesus is already a translation. The original words are lost -- except for a handful of Aramaic phrases the Gospel writers preserved: 'Talitha koum' ('Little girl, get up,' Mark 5:41), 'Ephphatha' ('Be opened,' Mark 7:34), 'Eloi, Eloi, lema sabachthani' ('My God, my God, why have you forsaken me,' Mark 15:34), and 'Abba' ('Father,' Mark 14:36). These survived because they were so memorable or powerful that the Greek-speaking church kept them untranslated.",
      intermediate:
        "Aramaic back-translation -- attempting to reconstruct what Jesus might have said in Aramaic from the Greek text -- has produced important insights. The Lord's Prayer in Aramaic (as reconstructed by scholars like Joachim Jeremias and Maurice Casey) reveals wordplays and resonances invisible in Greek or English. The Aramaic 'Abba' is not baby-talk ('Daddy,' as sometimes claimed) but an intimate, familial form of address -- closer to 'Dear Father' or 'Papa.' Its use for God was unusual (not unknown) in Jewish prayer and reflects Jesus' distinctive sense of intimacy with God.\n\nAramaic was a language with fewer abstract terms than Greek. Concepts that Greek could distinguish precisely (soul/spirit/mind) blur together in Aramaic. This means some of the theological precision of the Gospels may be a Greek-language development rather than something Jesus himself articulated. For example, the difference between 'eternal life' (Greek: zoe aionios) and 'life of the coming age' (which is what the underlying Aramaic idiom means) is significant: the first sounds like living forever, the second sounds like participating in God's restored world.\n\nThe Aramaic Targums (Jewish Aramaic paraphrases of Hebrew scripture, used in synagogue worship) provide crucial context for Jesus' teaching. When Jesus says 'the kingdom of God,' his Aramaic-speaking audience would have heard this against the Targum tradition where 'the kingdom of the LORD' means God's active rule becoming visible in the world -- not a place you go when you die but a reality that breaks into the present.\n\nMaurice Casey ('Aramaic Sources of Mark's Gospel,' 'An Aramaic Approach to Q') has done the most sustained scholarly work on Aramaic back-translation, arguing that the earliest Gospel traditions were transmitted in Aramaic before being translated into Greek. Some apparent contradictions between Gospels can be explained as different Greek translations of the same Aramaic original.",
      advanced:
        "The question of Jesus' languages is important for Christology and hermeneutics. If Jesus' ipsissima verba (actual words) are irrecoverable behind the Greek translation, then the foundation of the Gospels is not verbatim transcript but interpreted memory. This does not invalidate the Gospels but it does mean that the theological creativity of the evangelists is part of the picture from the very beginning.\n\nNeil Douglas-Klotz ('Prayers of the Cosmos') has attempted a devotional reconstruction of Jesus' teachings from Aramaic, emphasizing the multivalent, body-centered character of Semitic languages. While his scholarship has been criticized by specialists as over-reaching, his basic insight -- that Aramaic words carry physical, emotional, and spiritual registers simultaneously in ways Greek and English do not -- is sound.\n\nThe Peshitta (Syriac/Aramaic New Testament) preserves a Christian Aramaic tradition, though it is a translation from Greek rather than an original Aramaic text. Some scholars (George Lamsa) have argued that the Peshitta preserves the original Aramaic of Jesus; this view is rejected by mainstream scholarship but the Peshitta remains valuable for understanding how Aramaic-speaking Christians heard and interpreted the gospel message."
    },
  },

  {
    id: "c4-05",
    slug: "translation-politics",
    domainId: "d4",
    name: "Translation as Theology: How Translators Shape Belief",
    summary:
      "Every translation is a theological decision. The words translators choose determine what you believe the Bible says.",
    lensTags: ["academic", "protestant", "catholic"],
    relatedConceptSlugs: ["koine-greek", "biblical-hebrew", "textual-criticism"],
    relatedTextRefs: ["Isaiah 7:14", "Romans 3:25", "1 Timothy 2:12"],
    layers: {
      accessible:
        "Translation is never neutral. Every time a translator chooses one English word for a Hebrew or Greek word, they are making a theological decision. The Hebrew word almah in Isaiah 7:14 means 'young woman.' The Greek Septuagint translated it as parthenos ('virgin'). Matthew 1:23 quotes the Greek version. English Bibles that translate almah as 'virgin' in the Old Testament are importing a Christian reading back into the Hebrew text. Bibles that translate it as 'young woman' are more accurate to the Hebrew but seem to undermine the doctrine of the virgin birth. Either way, the translator has made a theological choice.\n\nOther examples: the Greek word ekklesia can be translated 'church' (implying an institution) or 'assembly' (implying a gathering of people). The Greek word episkopos can be 'bishop' (implying hierarchy) or 'overseer' (implying function). The Greek dikaiosyne can be 'righteousness' (moral quality) or 'justice' (social action). Each choice nudges the reader toward a different theology without the reader even knowing a choice was made.",
      intermediate:
        "The King James Version (1611) was a political project. King James I commissioned it partly to counter the Geneva Bible, which had marginal notes suggesting that kings who disobeyed God could be resisted -- a dangerous idea for an absolute monarch. The KJV translators were instructed to use 'church' instead of 'congregation' (preserving ecclesiastical authority) and to follow the Bishops' Bible rather than the more accurate Geneva Bible.\n\nGender translation is a current flashpoint. The Greek word adelphoi literally means 'brothers' but was used to address mixed-gender groups. Should it be translated 'brothers' (formal equivalence, potentially excluding women) or 'brothers and sisters' (dynamic equivalence, potentially adding words not in the text)? The ESV chose 'brothers'; the NRSV and NIV 2011 chose 'brothers and sisters.' Romans 16:7 mentions 'Junia' (a woman's name) as 'outstanding among the apostles.' Some translations changed 'Junia' to 'Junias' (a hypothetical male name not attested in any ancient text) to avoid the implication that a woman was an apostle.\n\n'Formal equivalence' (word-for-word, like ESV or NASB) preserves the foreign-ness of the text but can be misleading when idioms do not translate directly. 'Dynamic equivalence' (thought-for-thought, like NIV or NLT) prioritizes the meaning but requires the translator to decide what the text means before translating it. 'Paraphrase' (like The Message) prioritizes readability but introduces the most interpretive freedom. No translation philosophy is neutral.",
      advanced:
        "The politics of Bible translation have been analyzed by scholars including David Daniell ('The Bible in English'), Alister McGrath ('In the Beginning'), and Bruce Metzger ('The Bible in Translation'). Willis Barnstone ('The Poetics of Translation') argues that Christian translation of the Old Testament has systematically de-Judaized the text -- translating proper names from their Hebrew forms (Yeshua becomes Jesus, Miriam becomes Mary, Yochanan becomes John) in a way that obscures the Jewishness of the characters.\n\nThe choice of base text is itself theological. The KJV New Testament was based on the Textus Receptus (a late Byzantine text with many additions). Modern translations use the critical text (Nestle-Aland/UBS), which is based on earlier manuscripts and is shorter. The ending of Mark (16:9-20) and the story of the woman caught in adultery (John 7:53-8:11) are not in the earliest manuscripts and are likely later additions -- but they are beloved texts that many readers do not want to lose.\n\nUltimately, the most honest thing any English Bible could do is include extensive footnotes showing where the translator made a choice, what the alternatives were, and why. The fact that most popular Bibles minimize or omit such notes means that readers receive a finished product that conceals the interpretive decisions that produced it. Reading the Bible in translation without understanding translation is like reading a novel without knowing it was originally written in another language."
    },
  },

  {
    id: "c4-06",
    slug: "hebrew-wordplay",
    domainId: "d4",
    name: "Hebrew Wordplay: What You Miss Without the Original",
    summary:
      "Hebrew is built on three-letter roots that create webs of meaning. English translations strip away an entire dimension of the text.",
    lensTags: ["academic", "contemplative"],
    relatedConceptSlugs: ["biblical-hebrew", "creation-accounts", "psalms-as-practice"],
    relatedTextRefs: ["Genesis 2:7", "Genesis 3:1", "Isaiah 5:7", "Amos 8:1-2"],
    layers: {
      accessible:
        "Hebrew is a language built on wordplay, and the Bible is full of it -- but you would never know from English translations. In Genesis 2:7, God forms the adam (human) from the adamah (ground). Human and humus. In Genesis 3:1, the serpent is arum (cunning) while the humans were previously arummim (naked) -- same root, linking cunning to nakedness. In Isaiah 5:7, God expected mishpat (justice) but found mispach (bloodshed), tsedeqah (righteousness) but heard tse'aqah (a cry of the oppressed). The wordplay makes the point: justice and bloodshed sound almost the same -- the difference is subtle and devastating. These are not decorations. They are how the Hebrew text makes meaning. And they all vanish in translation.",
      intermediate:
        "Hebrew words are built on three-letter roots (sometimes two or four), and related words share roots. The root SH-L-M gives us shalom (peace/wholeness), shalem (complete), shillum (payment/recompense), Yerushalaim (Jerusalem, 'city of peace'), and the name Shlomo (Solomon). When you see 'Solomon' in English, you do not hear 'peace-king ruling the peace-city' -- but a Hebrew reader does. The root Q-D-SH gives qadosh (holy), qiddush (sanctification), qadesh (sacred prostitute). Holiness and 'set-apart-ness' overlap with the sacred in all its forms, including those that make modern readers uncomfortable.\n\nProphetic wordplay is often built on similar-sounding words (paronomasia). In Amos 8:1-2, God shows Amos a basket of qayits (summer fruit) and declares the qets (end) has come for Israel. The words sound almost identical: summer fruit and 'the end.' In Jeremiah 1:11-12, God shows Jeremiah a branch of shaqed (almond tree) and says 'I am shoqed (watching) over my word.' These puns carry theological weight: the prophet hears one word and receives another. Revelation comes through language itself.\n\nHebrew poetry does not rhyme or use meter in the way English poetry does. Its primary device is parallelism: saying something twice in different words. 'The heavens declare the glory of God / the skies proclaim the work of his hands' (Psalm 19:1). The second line does not simply repeat the first -- it extends, specifies, or contrasts it. Robert Alter calls this 'a system of heightening or intensification.' Understanding parallelism is essential for reading the Psalms, Proverbs, and the prophets correctly.",
      advanced:
        "James Kugel's 'The Idea of Biblical Poetry' challenged the long-standing assumption (dating to Robert Lowth's 1753 lectures) that Hebrew poetry operates on a principle of 'synonymous parallelism' where the second line merely restates the first. Kugel argued that the relationship between parallel lines is always progressive: 'A is so, and what is more, B.' The second line intensifies, specifies, extends, or complicates the first.\n\nRobert Alter's 'The Art of Biblical Narrative' and 'The Art of Biblical Poetry' (and his complete Bible translation, 2018) are the gold standard for literary analysis of Hebrew. Alter demonstrates that the 'repetition with variation' technique in Hebrew narrative (where a story is told, then retold with slight changes) is a precise literary instrument: the variations ARE the meaning.\n\nThe phenomenon of ketiv/qere (written/read) in the Masoretic Text preserves ancient debates about pronunciation and meaning. In some cases, the written consonants suggest one word while the marginal notation instructs reading another. This dual text preserves interpretive plurality within the manuscript tradition itself -- a feature completely invisible in translation."
    },
  },
];
