import type { Concept } from "./types";

export const domain6Concepts: Concept[] = [
  {
    id: "c6-01",
    slug: "atonement-theories",
    domainId: "d6",
    name: "Atonement Theories",
    summary:
      "Why did Jesus die? The church has never agreed on a single answer. Here are the major proposals.",
    lensTags: ["academic", "protestant", "catholic", "orthodox"],
    relatedConceptSlugs: ["atonement-theories", "christology", "eschatology"],
    relatedTextRefs: ["Romans 3:25", "1 John 2:2", "Colossians 2:15"],
    layers: {
      accessible:
        "If you ask 'why did Jesus die?', different Christian traditions give genuinely different answers. This is one of the biggest open questions in Christian theology, and no single theory has ever been declared the official answer. The major proposals: (1) Christus Victor -- Jesus' death defeated the powers of evil, sin, and death (dominant in the early church). (2) Satisfaction -- Jesus' death satisfied God's honor (Anselm, 11th century). (3) Penal Substitution -- Jesus took the punishment we deserved (Reformation, dominant in evangelicalism). (4) Moral Influence -- Jesus' death demonstrates God's love and inspires us to change (Abelard). (5) Scapegoat -- Jesus' death exposes and ends the cycle of sacrificial violence (Girard). These are not minor disagreements -- they produce fundamentally different understandings of God, justice, and what salvation means.",
      intermediate:
        "The historical development matters: Christus Victor (Gustaf Aulen, 1931, actually recovering ancient theology) was dominant for the first millennium. Christ's death is a cosmic battle -- God in Christ defeats the powers that enslave humanity (sin, death, the devil). This is the reading of Colossians 2:15 ('He disarmed the rulers and authorities and put them to open shame, triumphing over them'). Eastern Orthodoxy still holds this as primary.\n\nAnselm's Satisfaction Theory (Cur Deus Homo, 1098) reframed the question in feudal terms: sin offends God's honor, and only a being who is both human (to represent humanity) and divine (to offer infinite compensation) can make adequate satisfaction. This was NOT penal substitution -- Anselm was not talking about punishment but about honor and debt.\n\nPenal Substitution emerged with the Reformation (Calvin more than Luther). God's justice demands punishment for sin; Christ voluntarily absorbs that punishment in our place. This became the dominant evangelical view but has faced severe criticism: it seems to require God to punish an innocent person, it separates the Father (wrathful) from the Son (merciful), and it turns the cross into divine child abuse (the critique of feminist theologians like Joanne Carlson Brown).\n\nAbelard's Moral Influence/Moral Exemplar theory (12th century) sees Christ's death as the supreme demonstration of God's love, which moves us to love in return. Critics say this makes the cross merely inspirational rather than transformative.\n\nGirard's Scapegoat theory (20th century) uses social anthropology: human societies maintain order by projecting violence onto a scapegoat. Jesus accepts the role of scapegoat but, by being innocent and the death being witnessed, exposes and breaks the mechanism forever.",
      advanced:
        "Contemporary atonement theology increasingly moves toward multi-model approaches (Joel Green, Mark Baker, 'Recovering the Scandal of the Cross'). The argument: the NT itself uses multiple metaphors (victory, sacrifice, ransom, reconciliation, justification, redemption) without privileging one. Forcing a single theory onto these metaphors distorts the text.\n\nThe participatory model (gaining traction across traditions): atonement is not primarily about a transaction between God and Jesus on our behalf, but about humanity being incorporated into Christ's death and resurrection. Romans 6:3-4 ('baptized into his death') and Galatians 2:20 ('I have been crucified with Christ') point to participation, not spectation. Eastern Orthodox theosis (deification) is a version of this.\n\nThe Girardian reading has been particularly influential in recent decades (James Alison, 'The Joy of Being Wrong'). If the cross exposes the scapegoat mechanism, then Christianity is not a religion of sacrifice but the end of sacrifice -- the unveiling of the violence hidden in all human social order. This reading has powerful implications for social justice, nonviolence, and the critique of systems that sacrifice the vulnerable for the benefit of the powerful.\n\nFor the reader: the fact that Christianity has never agreed on a single atonement theory is not a failure -- it reflects the genuine mystery at the center of the faith. Each theory illuminates something. Each theory, when absolutized, distorts something. The question 'why did Jesus die?' may be less important than the question 'what does Jesus' death and resurrection make possible?'"
    },
    honestAnalysis:
      "No single atonement theory has been declared dogma by any ecumenical council. Penal Substitution, while dominant in evangelicalism, was not the view of the first millennium of Christianity and is rejected by most Orthodox and many Catholic theologians. The diversity of theories is a genuine feature of the tradition, not a problem to be solved.",
  },

  {
    id: "c6-02",
    slug: "christology",
    domainId: "d6",
    name: "Christology: Who Is Jesus?",
    summary:
      "The theological study of Christ's identity -- fully God, fully human, both, neither, something else? The answer has split churches and shaped civilizations.",
    lensTags: ["academic", "catholic", "orthodox", "protestant"],
    relatedConceptSlugs: ["council-of-nicaea", "atonement-theories"],
    relatedTextRefs: ["John 1:1-14", "Philippians 2:5-11", "Colossians 1:15-20"],
    layers: {
      accessible:
        "The central question of Christian theology: who is Jesus? The New Testament makes claims that are, on their face, impossible. Jesus is fully divine (John 1: 'the Word was God'). Jesus is fully human (he gets tired, hungry, angry, and dies). He is not half of each, not God wearing a human costume, not a human promoted to divinity. He is, somehow, both at the same time. The Council of Chalcedon (451 CE) produced the definitive formula: two natures (divine and human), one person, 'without confusion, without change, without division, without separation.' This formula does not explain HOW this works -- it draws boundaries around what you cannot say while leaving the mystery intact.",
      intermediate:
        "The path to Chalcedon was littered with rejected alternatives. Adoptionism said Jesus was a human adopted as God's son (at baptism or resurrection). Docetism said Jesus only appeared human -- his body was an illusion. Arianism said Jesus was divine but created, not eternal. Apollinarianism said Jesus had a human body but a divine mind (no human soul). Nestorianism was accused of dividing Christ into two persons (one divine, one human). Eutychianism merged the two natures into one mixed nature.\n\nEach heresy was rejected because it undermined salvation. If Jesus is not truly God, he cannot save. If Jesus is not truly human, he cannot represent humanity. If his two natures are confused, the divine swallows the human and we lose contact with God-in-flesh. If they are separated, we have two persons and no unity.\n\nThe Christological debates reveal how theology works: the church did not start with a doctrine and find proof texts. It started with the experience of Jesus (worship, encounter, transformation) and worked backward to articulate what must be true for that experience to make sense. Doctrine is reflection on practice, not the other way around.",
      advanced:
        "Contemporary Christology has moved in several directions. Karl Rahner's 'Christology from below' starts with the historical Jesus and asks how a human life could be the definitive self-expression of God. Wolfhart Pannenberg grounds Christology in the resurrection as a historical event that retroactively reveals Jesus' identity. Jon Sobrino and liberation Christology insist that the Christ of Chalcedon must be reconnected to the Jesus of the Gospels who sided with the poor.\n\nThe 'quest for the historical Jesus' (Schweitzer, Bultmann, the Jesus Seminar, N.T. Wright) has demonstrated that every generation constructs a Jesus in its own image. The liberal Jesus (a moral teacher), the existentialist Jesus (a call to authentic existence), the revolutionary Jesus (a political liberator), and the apocalyptic Jesus (an end-times prophet) all highlight real aspects of the gospel portrait while suppressing others.\n\nThe most productive current Christological work (Sarah Coakley, Kathryn Tanner) reconnects Christology to pneumatology (the Spirit) and practice (prayer). Coakley argues that contemplative prayer is the condition for doing Christology properly -- because the Trinity is not an abstract doctrine but a reality experienced in prayer: we pray to the Father, through the Son, in the Spirit. The doctrine of the Trinity is a map of the prayer experience, not a mathematical puzzle."
    },
  },

  {
    id: "c6-03",
    slug: "eschatology",
    domainId: "d6",
    name: "Eschatology: Last Things and the End of the World",
    summary:
      "What happens when we die? What happens at the end of history? Heaven, hell, resurrection, rapture, millennium -- the tradition has multiple competing answers.",
    lensTags: ["academic", "protestant", "catholic", "orthodox"],
    relatedConceptSlugs: ["christology", "atonement-theories", "theodicy"],
    relatedTextRefs: ["Revelation 20-21", "1 Thessalonians 4:13-18", "1 Corinthians 15"],
    layers: {
      accessible:
        "Eschatology means 'the study of last things' -- death, judgment, heaven, hell, the return of Christ, and the renewal of creation. Christians agree on surprisingly little of this. Catholics teach purgatory (a purification after death before heaven); Protestants reject it. Some traditions teach soul sleep (the dead are unconscious until resurrection); others teach immediate conscious presence with God. The 'rapture' (believers snatched up before a period of tribulation) is a 19th-century invention popularized by John Nelson Darby and the Scofield Reference Bible -- it is not taught by Catholic, Orthodox, or most mainline Protestant traditions. The most consistent biblical image is not 'souls going to heaven' but bodily resurrection and the renewal of creation (Revelation 21: a new heaven AND a new earth, not escape from earth to heaven).",
      intermediate:
        "Three major millennial positions divide Christians:\n\nPremillennialism: Christ returns BEFORE a literal thousand-year reign on earth. This divides into historic premillennialism (the church goes through tribulation) and dispensational premillennialism (the church is raptured before tribulation). The Left Behind series popularized dispensationalism, but it represents a minority position in church history.\n\nPostmillennialism: The gospel gradually transforms the world until Christ returns to a world already substantially Christianized. Popular in 19th-century America (manifest destiny) but declined after two world wars made optimism about human progress difficult.\n\nAmillennialism: The thousand years in Revelation 20 is symbolic, not literal. Christ's reign is happening now through the church. This is the position of Augustine, most Catholics, most Orthodox, and many Reformed Protestants.\n\nThe New Testament contains at least two eschatological timelines in tension. Paul in 1 Thessalonians 4 expects Christ's return within his lifetime. 2 Peter 3 explains the delay ('with the Lord one day is as a thousand years'). This tension between imminent expectation and delayed return has never been fully resolved.\n\nThe doctrine of hell is the most contested eschatological topic. Eternal conscious torment (the traditional view), annihilationism (the unsaved cease to exist), and universal reconciliation (all are eventually saved) all have biblical and theological arguments. C.S. Lewis, Rob Bell, Hans Urs von Balthasar, and David Bentley Hart represent a spectrum from cautious hope to confident universalism.",
      advanced:
        "Jurgen Moltmann's 'Theology of Hope' (1964) reframed eschatology as the central Christian doctrine, not a peripheral one. If God's future determines the present (rather than the past determining the future), then hope is not optimism but an active reaching toward the promised transformation of creation. This inverts the conservative eschatological tendency to read current events as 'signs of the end' and instead asks: what does God's promised future demand of us now?\n\nN.T. Wright's 'Surprised by Hope' has been influential in recovering bodily resurrection (against Platonic soul-escape) as the core Christian hope. Wright argues that the popular picture -- souls going to heaven when they die -- is actually Greek philosophy (Plato's immortal soul) dressed in Christian clothing. The biblical hope is resurrection: God will remake the material world, including human bodies. This has ethical implications: if creation matters to God permanently, then caring for bodies, justice, and the environment is not a distraction from 'spiritual' concerns but central to the gospel.\n\nThe universalism debate has been revived by David Bentley Hart ('That All Shall Be Saved'), who argues that eternal conscious torment is logically incompatible with divine omnipotence, omniscience, and goodness. If God wills the salvation of all (1 Timothy 2:4) and God's will is irresistible, then all must eventually be saved. The traditional counter-argument appeals to human freedom: God will not override free refusal. But Hart contends that no finite will can hold out infinitely against infinite love, and that 'eternal punishment' (Matthew 25:46) uses 'aionios,' which means 'age-long,' not necessarily 'everlasting.'"
    },
    honestAnalysis:
      "Eschatology is where confident theological claims are most obviously projection. Every generation has been certain it was the last. Every attempt to construct a detailed timeline from biblical texts has failed. The most honest eschatological stance may be: 'We know less than we think, and the biblical images point to a hope deeper than our ability to systematize it.'",
  },

  {
    id: "c6-04",
    slug: "trinity",
    domainId: "d6",
    name: "The Trinity: God Is Three and God Is One",
    summary:
      "Christianity's most distinctive and most confusing doctrine. The word 'Trinity' is not in the Bible. The concept took 300 years to formulate.",
    lensTags: ["academic", "catholic", "orthodox", "protestant"],
    relatedConceptSlugs: ["christology", "council-of-nicaea", "atonement-theories"],
    relatedTextRefs: ["Matthew 28:19", "John 1:1", "2 Corinthians 13:14"],
    layers: {
      accessible:
        "The Trinity is the claim that God is one being who exists as three persons: Father, Son, and Holy Spirit. Each is fully God. None is the other. There is only one God. This sounds like a contradiction, and for 2,000 years people have been trying to explain it without falling into heresy. Every popular analogy fails: God is not like water/ice/steam (that is modalism -- one thing appearing in three forms). God is not like a three-leaf clover (that implies three parts making a whole). God is not like three roles played by one actor (modalism again). The honest answer is that the Trinity is a mystery -- a term theologians use when they mean 'this is the best language we have, and it is not enough.' The Trinity was not revealed in a single Bible verse. It emerged gradually as the early church tried to make sense of their experience: worshiping one God, while also worshiping Jesus, while also experiencing the Spirit as divine.",
      intermediate:
        "The development of Trinitarian doctrine: The New Testament does not teach the Trinity explicitly. It contains the raw materials: Jesus is called Lord and God (John 20:28), the Spirit is personal and divine (Acts 5:3-4), and Father-Son-Spirit appear together in formulae (Matthew 28:19, 2 Corinthians 13:14). But the philosophical synthesis -- one ousia (being/substance) in three hypostaseis (persons/subsistences) -- took three centuries.\n\nThe key stages: (1) Early Jewish Christians had to reconcile monotheism with the worship of Jesus. Larry Hurtado ('Lord Jesus Christ') argues that devotion to Jesus as divine emerged remarkably early -- within the first two decades. (2) The Logos theology of the 2nd century (Justin Martyr, drawing on John 1:1 and Middle Platonism) identified Jesus with the divine Logos -- rational/creative principle. (3) The Arian controversy (early 4th century): Arius argued that the Son was the first and greatest creature but not truly God ('there was a time when he was not'). The Council of Nicaea (325) declared the Son homoousios (same substance) with the Father. (4) The Cappadocian Fathers (Basil of Caesarea, Gregory of Nazianzus, Gregory of Nyssa) finalized the formula: one ousia, three hypostaseis -- distinguishing 'what God is' (substance) from 'who God is' (persons).\n\nThe Filioque controversy: the West added 'and the Son' to the Creed's statement about the Spirit's procession. This was not just a political power play -- it reflects genuinely different Trinitarian theologies. The West (following Augustine) starts from the unity of God and then distinguishes the persons. The East (following the Cappadocians) starts from the three persons and then affirms their unity. Same destination, different starting points -- which is why they can agree on the Trinity while disagreeing on the Filioque.",
      advanced:
        "Contemporary Trinitarian theology has experienced a remarkable revival. Karl Rahner's 'Rule' ('the economic Trinity IS the immanent Trinity and vice versa') insists that the God who acts in salvation history (economic) is the God who exists in eternity (immanent) -- there is no hidden God behind the God we meet in Jesus and the Spirit. Jurgen Moltmann ('The Trinity and the Kingdom') develops a social Trinity: the divine persons exist in relationships of mutual love, and this serves as a model for human community.\n\nThe Orthodox tradition, through John Zizioulas ('Being as Communion'), argues that personhood -- not substance -- is the ultimate category of reality. God is not first a 'thing' that happens to be personal; God is first personal, and Being flows from personhood. This has radical implications: if the ultimate reality is communion, then isolation is not just unfortunate but ontologically deficient.\n\nFeminist Trinitarian theology (Elizabeth Johnson, 'She Who Is') questions whether Father-Son language is essential to the doctrine or culturally conditioned. If the point of the Trinity is relationship-in-difference, then gendered language is not the substance of the doctrine but one historically conditioned expression of it. This remains controversial across traditions.\n\nThe deepest theological point of the Trinity may be this: if God is internally relational, then relationship is not something God does but something God IS. Love is not a divine attribute among others -- it is the divine nature. 'God is love' (1 John 4:8) is not sentimental; it is ontological."
    },
  },

  {
    id: "c6-05",
    slug: "original-sin",
    domainId: "d6",
    name: "Original Sin: Did Augustine Get It Wrong?",
    summary:
      "Augustine taught that all humans inherit Adam's guilt. The Eastern church never agreed. The debate shapes how you understand human nature, salvation, and God.",
    lensTags: ["academic", "catholic", "orthodox", "protestant"],
    relatedConceptSlugs: ["atonement-theories", "trinity", "christology"],
    relatedTextRefs: ["Romans 5:12-21", "Genesis 3", "Psalm 51:5"],
    layers: {
      accessible:
        "Original sin is the idea that when Adam and Eve disobeyed God in the Garden of Eden, their sin was passed down to every human being born afterward. In the Western tradition (Catholic and Protestant), this means everyone is born guilty and inclined toward evil. You did not choose to be a sinner -- you were born one. This doctrine was largely shaped by Augustine of Hippo (354-430 CE), who based it on a Latin mistranslation of Romans 5:12. The Greek says 'death spread to all, because all sinned.' The Latin Vulgate translated this as 'death spread to all, in whom [i.e., in Adam] all sinned' -- making it sound like everyone sinned IN Adam. The Eastern church, reading the Greek correctly, developed a different doctrine: humans inherit mortality and a tendency toward sin, but not guilt for Adam's sin. You are born into a broken world, not born guilty.",
      intermediate:
        "The theological stakes are enormous. If original sin means inherited guilt, then: unbaptized infants may be condemned (Augustine reluctantly accepted this), human nature is fundamentally corrupt, and salvation requires an external rescue (grace that overwrites your broken nature). If original sin means inherited mortality and tendency (the Eastern view), then: infants are innocent, human nature is damaged but not destroyed, and salvation is a healing process (theosis) rather than a legal acquittal.\n\nAugustine developed his doctrine partly in response to Pelagius, a British monk who taught that humans can choose to live sinlessly without special grace. Augustine saw this as dangerously naive -- it denies the depth of human bondage to sin and makes salvation a human achievement rather than a divine gift. The Council of Carthage (418) and the Council of Orange (529) affirmed Augustine's position against Pelagius.\n\nBut Augustine's position has problems. The Eastern Fathers -- John Chrysostom, Gregory of Nyssa, Maximus the Confessor -- never taught inherited guilt. They taught that Adam's sin introduced death and corruption into the world, and that in a world of death, humans inevitably sin (because mortality creates fear, which creates selfishness, which creates sin). This is a very different picture: sin is a disease to be healed, not a crime to be punished. You are a victim before you are a perpetrator.\n\nThe Reformers intensified Augustine. Calvin taught 'total depravity' -- not that humans are as bad as possible, but that every aspect of human nature (reason, will, affections) is distorted by sin. Luther's 'bondage of the will' argued that human free will in spiritual matters is an illusion. Both built on Augustine's pessimistic anthropology.",
      advanced:
        "The scholarly reassessment of original sin is one of the most active areas in contemporary theology. Key developments:\n\nEvolutionary science poses a fundamental challenge: if there was no historical Adam and Eve, if death existed long before humans, and if 'selfishness' is a feature of natural selection, then the traditional narrative (perfect creation, fall, corruption) does not correspond to what actually happened. Theologians like Daryl Domning ('Original Selfishness') and Patricia Williams ('Doing Without Adam and Eve') have proposed evolutionary accounts of original sin: the human tendency toward self-centeredness is our evolutionary inheritance, and 'original sin' names this reality without requiring a historical fall.\n\nRoman Catholic theology has made significant adjustments. Karl Rahner reinterpreted original sin as the universal human situation of being born into a world already distorted by accumulated sin -- a 'situation of un-freedom' that precedes individual choice. The Catechism of the Catholic Church now speaks of original sin as 'a deprivation of original holiness and justice' rather than literal inherited guilt.\n\nThe Orthodox alternative (articulated by John Romanides, 'The Ancestral Sin') has gained increasing attention in the West. Romanides argues that the Western doctrine of original sin, rooted in a mistranslation and distorted by Augustine's personal psychology (his guilt over his sexual past), produced a Christianity focused on juridical categories (guilt, punishment, satisfaction) rather than therapeutic ones (sickness, healing, transformation). This is not just an academic disagreement -- it shapes pastoral practice. A pastor who believes people are fundamentally guilty treats them differently than one who believes they are fundamentally wounded."
    },
  },

  {
    id: "c6-06",
    slug: "hell-universalism",
    domainId: "d6",
    name: "Hell and Universalism: Does Everyone Get Saved?",
    summary:
      "The Bible's language about judgment is more ambiguous than you think. The early church was divided. The debate is not settled.",
    lensTags: ["academic", "protestant", "orthodox"],
    relatedConceptSlugs: ["atonement-theories", "eschatology", "original-sin"],
    relatedTextRefs: ["1 Corinthians 15:22", "Romans 11:32", "Matthew 25:46", "Revelation 21:25"],
    layers: {
      accessible:
        "Three main views have existed throughout Christian history: (1) Eternal conscious torment -- the majority view in Western Christianity, that those who reject God suffer forever. (2) Annihilationism -- the unsaved are destroyed rather than tormented eternally. (3) Universal reconciliation (apokatastasis) -- ultimately, all beings will be reconciled to God, and hell is purifying rather than permanent. Universalism is not a modern liberal invention. Origen of Alexandria (3rd century), Gregory of Nyssa (4th century, one of the theologians who formulated the Trinity), and other respected early Fathers taught it. The key question is the Greek word aionios, translated 'eternal' in most Bibles. It actually means 'of the age' or 'age-long' -- pertaining to an age, not necessarily endless. If aionios punishment means punishment lasting an age (not forever), the entire traditional doctrine shifts.",
      intermediate:
        "The biblical evidence is genuinely ambiguous. Verses supporting eternal punishment: Matthew 25:46 ('eternal punishment' vs. 'eternal life' -- if one is temporary, the other should be too), Mark 9:48 ('where the worm does not die and the fire is not quenched'), Revelation 20:10 ('tormented day and night forever and ever').\n\nVerses supporting universalism: 1 Corinthians 15:22 ('as in Adam all die, so in Christ all will be made alive'), Romans 11:32 ('God has imprisoned all in disobedience so that he may be merciful to all'), Colossians 1:19-20 ('through him God was pleased to reconcile to himself all things'), Philippians 2:10-11 ('every knee shall bow... every tongue confess that Jesus Christ is Lord'), 1 Timothy 2:4 ('God desires all people to be saved').\n\nThe word 'hell' in English translations conflates three different biblical concepts: Sheol (Hebrew: the shadowy underworld of all the dead, not a place of punishment), Hades (Greek: equivalent to Sheol), and Gehenna (Greek, from Hebrew ge-hinnom: the Valley of Hinnom outside Jerusalem, a garbage dump with perpetual fires, used by Jesus as a metaphor for judgment). Jesus' references to 'Gehenna' are typically addressed to religious leaders and concern temporal judgment on Jerusalem (which was destroyed by Rome in 70 CE), not the post-mortem fate of individuals.\n\nThe 'hell' of Dante's Inferno, Left Behind, and popular Christianity is a medieval construction that combines Gehenna, Greco-Roman Hades mythology, and Apocalyptic imagery into a coherent system that no single biblical text actually presents.\n\nHistorical universalists: Clement of Alexandria, Origen, Gregory of Nyssa, Gregory of Nazianzus (tentatively), Isaac of Nineveh, Julian of Norwich ('all shall be well'), George MacDonald (C.S. Lewis's primary theological influence), Karl Barth (strongly implied but never definitively stated).",
      advanced:
        "The debate has been reinvigorated by David Bentley Hart's 'That All Shall Be Saved' (2019), which makes a philosophical and theological case that eternal torment is logically incompatible with a God who is goodness itself. Hart's argument: if God is the infinite Good and the source of all being, and if any rational creature's deepest desire is for the Good (a classical metaphysical claim), then eternal rejection of God would require a creature to be permanently in a state that contradicts its own nature -- which would mean God created beings capable of eternal self-destruction, which contradicts divine goodness.\n\nThe opposing case (defended by Jerry Walls, 'Hell: The Logic of Damnation') rests on libertarian free will: God respects human freedom so completely that God allows creatures to say 'no' permanently. C.S. Lewis's 'The Great Divorce' dramatizes this: the doors of hell are locked from the inside.\n\nThe Orthodox tradition is the most internally diverse on this question. The Fifth Ecumenical Council (553) condemned certain propositions attributed to Origen, including the pre-existence of souls, but whether it condemned universalism itself is debated. The anathemas may target a specific Origenist system rather than the hope of universal salvation as such. Many Orthodox theologians (Kallistos Ware, Hilarion Alfeyev) distinguish between the dogmatic assertion 'all will be saved' (which the church has not defined) and the theological hope 'we may dare to hope that all will be saved' (which is permissible).\n\nThe pastoral implications are the real stakes. If hell is eternal and most people go there, then Christianity is a lifeboat religion -- the primary mission is rescue from damnation. If salvation is ultimately universal, then the Christian life is not about escaping punishment but about participating now in the reconciliation that God is accomplishing in all things."
    },
  },

  {
    id: "c6-07",
    slug: "problem-of-evil",
    domainId: "d6",
    name: "The Problem of Evil: Christianity's Hardest Question",
    summary:
      "If God is all-powerful and all-good, why does suffering exist? Every answer fails somewhere. The tradition preserves the question more than it answers it.",
    lensTags: ["academic", "pastoral", "contemplative"],
    relatedConceptSlugs: ["theodicy", "atonement-theories", "original-sin"],
    relatedTextRefs: ["Job 38-42", "Romans 8:18-25", "Habakkuk 1:2-4"],
    layers: {
      accessible:
        "The problem of evil is the oldest and strongest objection to belief in God. It goes like this: if God is all-powerful (can prevent suffering), and all-good (wants to prevent suffering), then suffering should not exist. But suffering exists. So either God is not all-powerful, or not all-good, or does not exist. The standard Christian responses are: Free will (God gave humans freedom, and we misuse it). Soul-making (suffering develops character). Greater good (God allows evil to bring about a greater good we cannot see). Punishment for sin. Spiritual warfare (evil forces oppose God). Mystery (we cannot understand God's reasons). Each answer works for some kinds of suffering and fails for others. Free will explains human cruelty but not earthquakes. Soul-making works for mild suffering but is obscene when applied to a child dying of cancer. The Book of Job -- the Bible's most sustained engagement with the question -- never actually answers it. God appears in a whirlwind and essentially says: you are not big enough to understand.",
      intermediate:
        "Philosophers distinguish between the 'logical problem of evil' (is it logically possible for God and evil to coexist?) and the 'evidential problem of evil' (is the amount and distribution of evil evidence against God?). Alvin Plantinga's 'Free Will Defense' is widely considered to have resolved the logical problem: it is logically possible that a world with free beings who sometimes choose evil is more valuable than a world of robots who cannot choose. The evidential problem remains formidable.\n\nWilliam Rowe's 'evidential argument' uses specific instances of apparently pointless suffering (a fawn dying in agony in a forest fire with no observer) to argue that at least some evil has no possible greater good. The response (skeptical theism) argues that our inability to see a reason does not mean there is no reason -- but critics note that this makes God permanently unfalsifiable.\n\nThe distinction between 'natural evil' (earthquakes, diseases, birth defects) and 'moral evil' (murder, rape, torture) matters because different theodicies address different kinds. Free will explains moral evil. For natural evil, options include: it is a consequence of a good natural order (tectonic plates cause earthquakes but also make life possible), it results from a cosmic fall (the whole creation is damaged by sin), or it is the necessary condition for a physical world (a world where fire warms but never burns would not be a coherent physical world).\n\nThe Book of Job subverts every theodicy. Job's friends offer the standard explanations (you must have sinned, suffering is discipline, God is testing you). God appears and rejects ALL the friends' explanations. But God also does not offer an alternative explanation. God simply reveals the overwhelming complexity of reality -- a cosmos too vast for human categories of 'fair' and 'unfair' to contain. This is not an answer. It is a reframing.",
      advanced:
        "The most important recent work on theodicy shifts the question from explanation to response. Marilyn McCord Adams ('Horrendous Evils and the Goodness of God') argues that horrendous evils -- those so destructive that they threaten to undo the goodness of a person's entire life -- cannot be explained by greater-good arguments. Instead, she proposes that God's response to horrendous evil is to participate in it (the cross), to transform it from within (resurrection), and to integrate it into a relationship with the divine Good so intimate that the sufferer would eventually not wish the suffering away.\n\nJurgen Moltmann ('The Crucified God') locates God within suffering rather than outside it. The cross means that God does not observe suffering from a distance but enters it fully. The theological consequence is that atheism's strongest argument (suffering disproves a good God) is actually anticipated by Christianity's central symbol: a God who suffers.\n\nDavid Bentley Hart ('The Doors of the Sea') rejects all theodicies that make evil instrumentally necessary for some greater good. Evil is never good. It is never necessary. It is an intrusion into a creation that God did not design for suffering. The proper Christian response is not to explain evil but to oppose it, trusting that God's final word is redemption, not explanation. Hart's position is deeply Orthodox: evil is not a theological puzzle to be solved but a sickness to be healed."
    },
  },
];
