import type { Concept } from "./types";

export const domain8Concepts: Concept[] = [
  {
    id: "c8-01",
    slug: "liturgical-calendar",
    domainId: "d8",
    name: "The Liturgical Calendar",
    summary:
      "The annual cycle of seasons and feasts that structures Christian worship -- Advent, Christmas, Epiphany, Lent, Easter, Pentecost, and Ordinary Time.",
    lensTags: ["catholic", "orthodox", "anglican", "lutheran"],
    relatedConceptSlugs: ["eucharistic-traditions", "eucharist-meanings"],
    relatedTextRefs: ["Luke 2:1-20", "Matthew 28:1-10", "Acts 2:1-13"],
    layers: {
      accessible:
        "The liturgical calendar organizes the entire Christian year around the life of Jesus. It begins not on January 1 but on the first Sunday of Advent (four weeks before Christmas), creating a yearly rhythm: Advent (waiting and hope), Christmas (incarnation), Epiphany (Christ revealed to the world), Lent (40 days of repentance before Easter), Holy Week (the final week of Jesus' life), Easter (resurrection -- the climax of the entire year), and Pentecost (the Holy Spirit given to the church). The long stretch after Pentecost is called 'Ordinary Time' -- not because it is boring but from the word 'ordinal' (counted time). Liturgical colors mark each season: purple for Advent and Lent (penitence), white for Christmas and Easter (celebration), red for Pentecost and martyrs, green for Ordinary Time (growth).",
      intermediate:
        "The calendar embeds a theology of time. Against the modern view of time as neutral and linear, the liturgical calendar says: time has texture. Some days carry more weight than others. The Easter Triduum (Holy Thursday, Good Friday, Holy Saturday) is not three days but one continuous liturgical event -- the church's great three days.\n\nThe dating of Easter is itself a theological argument. The Council of Nicaea (325) determined that Easter would be celebrated on the first Sunday after the first full moon after the spring equinox -- deliberately distancing it from Passover's dating while maintaining the spring connection. Eastern and Western churches calculate this differently (Gregorian vs. Julian calendar), which is why Orthodox and Catholic/Protestant Easter dates rarely coincide.\n\nThe lectionary (cycle of Scripture readings assigned to each Sunday) ensures that congregations hear a broad range of Scripture over time. The Revised Common Lectionary uses a three-year cycle (Years A, B, C corresponding to Matthew, Mark, Luke) with John woven throughout. This means a church following the lectionary will hear approximately 70% of the Bible read aloud over three years -- far more than churches that rely on pastor-selected texts.\n\nOrdinary Time is theologically significant despite its name. It represents the long work of discipleship between the great feasts -- the daily, undramatic commitment that constitutes most of the Christian life. The liturgical calendar resists the idea that every Sunday must be a mountaintop experience.",
      advanced:
        "The development of the liturgical calendar reveals how the church negotiated with existing cultural calendars. Christmas on December 25 was almost certainly placed to coincide with the Roman Sol Invictus festival and the winter solstice -- not because Jesus was born on that date (Luke's description of shepherds in fields suggests spring or summer) but as a theological claim: the true Light enters the world at the darkest point of the year. This is not 'pagan corruption' but deliberate theological inculturation.\n\nThe most significant recent liturgical development was Vatican II's 'Sacrosanctum Concilium' (1963), which reformed the Roman Catholic liturgical calendar and encouraged vernacular worship. The post-Vatican II calendar simplified the saint cycle and restored the prominence of the Sunday celebration. This inspired the creation of the Revised Common Lectionary (1992), which has been adopted by Catholics, mainline Protestants, and Anglicans, creating more liturgical convergence than at any point since the Reformation.\n\nThe Eastern Orthodox calendar preserves features lost in the West: the Great Fast (Lent) begins on Clean Monday, not Ash Wednesday. The Paschal Vigil remains the central liturgical event of the year, running from Saturday night into Sunday morning with baptisms, extended Scripture readings, and the dramatic lighting of candles from the Paschal fire. The Orthodox experience of Easter (Pascha) as a communal, embodied, multi-sensory event -- rather than an idea about resurrection -- represents the original Christian liturgical instinct."
    },
  },

  {
    id: "c8-02",
    slug: "eucharistic-traditions",
    domainId: "d8",
    name: "Eucharistic Traditions Across Christianity",
    summary:
      "How different Christian traditions understand and practice communion -- from Roman Catholic transubstantiation to Quaker silence, and everything in between.",
    lensTags: ["catholic", "orthodox", "protestant", "academic"],
    relatedConceptSlugs: ["liturgical-calendar", "council-of-nicaea"],
    relatedTextRefs: ["Matthew 26:26-28", "1 Corinthians 11:23-26", "John 6:53-56"],
    layers: {
      accessible:
        "The Eucharist (also called Communion, the Lord's Supper, or the Mass) is the most widely practiced Christian ritual, but Christians disagree radically about what happens during it. Roman Catholics teach transubstantiation: the bread and wine literally become the body and blood of Christ while retaining the appearance of bread and wine. Eastern Orthodox affirm a 'real presence' but refuse to explain the mechanism, calling it a mystery. Lutherans teach 'in, with, and under' -- Christ is truly present in the elements without the bread ceasing to be bread. Reformed/Calvinist tradition teaches a 'spiritual presence' -- Christ is truly present to the believer through the Holy Spirit, but not physically in the bread. Baptists and most evangelicals view it as a memorial -- a symbolic act of remembrance, not a sacrament that conveys grace. Quakers practice no communion at all, believing every meal is sacramental.",
      intermediate:
        "The earliest Christian Eucharistic prayers (the Didache, c. 50-100 CE) are strikingly simple and focused on thanksgiving -- 'eucharist' literally means 'thanksgiving.' The elaborate sacramental theology developed over centuries.\n\nThe Fourth Lateran Council (1215) officially defined transubstantiation using Aristotelian philosophy: the 'substance' (what a thing fundamentally is) changes from bread to Christ's body, while the 'accidents' (what it looks like, tastes like, feels like) remain bread. Thomas Aquinas refined this in the Summa Theologica. The Reformers rejected the Aristotelian metaphysical framework but disagreed among themselves about the alternative.\n\nThe Luther-Zwingli debate at the Marburg Colloquy (1529) encapsulates the Protestant disagreement. Luther pointed to 'This IS my body' and insisted on literal presence. Zwingli pointed to 'Do this in REMEMBRANCE of me' and insisted on symbolic memorial. They agreed on 14 of 15 articles but could not agree on the Eucharist. This single disagreement prevented Protestant unity and still does.\n\nCalvin attempted a middle position: Christ is truly present in the Eucharist, but the believer ascends to Christ through the Spirit rather than Christ descending into the bread. Calvin's 'spiritual real presence' view has influenced many Reformed and Presbyterian churches.",
      advanced:
        "Contemporary Eucharistic theology has moved in several directions. Edward Schillebeeckx proposed 'transignification' -- the meaning of the bread changes, which is more fundamental than a substance change. Louis-Marie Chauvet argues that sacramental theology needs to move beyond metaphysics entirely toward a phenomenology of gift and symbol.\n\nThe ecumenical convergence document 'Baptism, Eucharist and Ministry' (BEM, 1982, also called the Lima Document) achieved remarkable agreement: the Eucharist is thanksgiving, memorial (anamnesis), invocation of the Spirit (epiclesis), communion of the faithful, and meal of the Kingdom. Most traditions could affirm this framework even while disagreeing about the mechanism of presence.\n\nLiturgical scholarship has recovered the eschatological dimension of the Eucharist that was largely lost in Western debates about presence. The early church understood the Eucharist as a foretaste of the messianic banquet -- not primarily a remembrance of the past (cross) but an anticipation of the future (kingdom feast). The Maranatha ('Come, Lord') prayer in the Didache and 1 Corinthians 16:22 was originally a Eucharistic prayer calling for Christ's eschatological return, not a general prayer request.\n\nThe social-ethical dimension: the early church's Eucharistic practice was inseparable from economic sharing (1 Corinthians 11, where Paul criticizes the rich for eating while the poor go hungry). The Eucharist was originally a full meal, not a token sip and wafer. William Cavanaugh ('Torture and Eucharist') argues that the Eucharist is inherently political -- it forms an alternative body politic that challenges every regime that claims sovereignty over human bodies."
    },
  },

  {
    id: "c8-03",
    slug: "eucharist-meanings",
    domainId: "d8",
    name: "The Eucharist: What Happens at the Table?",
    summary:
      "Bread and wine. Body and blood. Every Christian tradition practices communion, but they disagree profoundly about what actually happens -- and the disagreement reveals deep theological fault lines.",
    lensTags: ["catholic", "orthodox", "protestant", "academic"],
    relatedConceptSlugs: ["eucharist-meanings", "council-of-nicaea"],
    relatedTextRefs: ["Luke 22:14-20", "1 Corinthians 11:23-26", "John 6:51-58"],
    layers: {
      accessible:
        "Jesus took bread, said 'this is my body,' took wine, said 'this is my blood,' and told his followers to keep doing this in remembrance of him. Every Christian tradition practices some form of communion. But they disagree about what happens. Catholics teach transubstantiation: the bread and wine literally become Christ's body and blood while keeping the appearance of bread and wine. Orthodox affirm a real change but refuse to define the mechanism (it is a 'mystery'). Lutherans teach that Christ is truly present 'in, with, and under' the bread and wine. Calvinists say Christ is spiritually (but really) present. Many evangelicals and Baptists treat it as purely symbolic -- a memorial meal.",
      intermediate:
        "The word 'transubstantiation' was formally defined at the Fourth Lateran Council (1215) using Aristotelian philosophy: the 'substance' (what a thing truly is) changes while the 'accidents' (what it looks like, tastes like) remain. This philosophical framework was cutting-edge in the 13th century but strikes many modern people as bizarre. Yet the question it addresses is profound: when Jesus says 'this is my body,' is he speaking metaphorically or making an ontological claim?\n\nThe Eastern Orthodox tradition wisely avoids philosophical definitions. They affirm that the bread and wine become Christ's body and blood by the action of the Holy Spirit (the 'epiclesis' -- the invocation of the Spirit during the liturgy). How this happens is a mystery beyond human categories. The Orthodox critique of transubstantiation is that it over-defines a mystery that should be worshipped, not analyzed.\n\nThe Reformation produced four different eucharistic theologies: Luther insisted on real presence ('is' means 'is'), Zwingli treated it as memorial ('is' means 'represents'), Calvin proposed a middle way (spiritual real presence through the Holy Spirit), and the Anabaptists emphasized the communal meal aspect. These disagreements were not minor -- they split the Protestant movement permanently.",
      advanced:
        "Contemporary eucharistic theology has moved beyond the medieval impasse. Louis-Marie Chauvet ('Symbol and Sacrament') uses postmodern philosophy to argue that the opposition between 'real presence' and 'symbolic memorial' is a false dilemma. Symbols are not 'less than' reality -- they are how reality becomes present to us. The eucharist is not Christ 'hidden behind' bread but Christ present AS bread, in the act of sharing, eating, and communion. This resonates with phenomenological approaches (Jean-Luc Marion) that understand the sacraments as 'saturated phenomena' -- events so full of meaning that they exceed our categories.\n\nThe ethical dimension of the eucharist has been recovered by liberation theology. If we eat Christ's body, we are bound to recognize Christ in the bodies of the poor, the hungry, the imprisoned. Augustine said the church IS the body of Christ and the eucharist makes the church. Therefore: receiving communion while ignoring injustice is a contradiction. Paul's warning (1 Corinthians 11:27-29) about eating 'without discerning the body' may refer not to belief in real presence but to failure to see Christ in one's fellow believers, especially the poor."
    },
  },

  {
    id: "c8-04",
    slug: "baptism-meanings",
    domainId: "d8",
    name: "Baptism: Drowning and Rebirth",
    summary:
      "Baptism is not a nice ceremony with a little water. It is a symbolic drowning -- the death of one identity and the emergence of another.",
    lensTags: ["academic", "catholic", "orthodox", "protestant"],
    relatedConceptSlugs: ["eucharist-meanings", "liturgical-calendar"],
    relatedTextRefs: ["Romans 6:3-4", "Mark 1:9-11", "Galatians 3:27"],
    layers: {
      accessible:
        "The Greek word baptizo means to immerse, dip, or plunge -- the same word used for dyeing cloth (plunging it into dye so it changes color completely). Early Christians practiced full immersion. You went down into the water (symbolic death) and came up out of it (symbolic resurrection). Paul says it explicitly: 'We were buried with Christ through baptism into death, so that just as Christ was raised from the dead, we too may walk in newness of life' (Romans 6:4). The tradition added layers: removing old clothes before baptism and putting on new white robes after (stripping the old self, clothing in Christ). Being anointed with oil. Receiving a new name. Facing west to renounce evil, then turning east to affirm faith. Every element dramatizes the same thing: you are dying and being born again.",
      intermediate:
        "The major Christian traditions disagree on almost everything about baptism. Who gets baptized? Catholics, Orthodox, Lutherans, Reformed, and Methodists baptize infants (based on covenant theology -- children of believers are part of the covenant community). Baptists, Pentecostals, and Anabaptists baptize only believers who choose it (based on the pattern in Acts where people believe first, then get baptized). How much water? Immersion (Baptist, Orthodox, some Catholic), pouring/affusion (most Catholic, Lutheran, Reformed), or sprinkling (some Reformed). What does it do? Catholics and Orthodox teach baptismal regeneration (baptism actually confers grace and removes original sin). Lutherans teach that baptism is a means of grace but requires faith. Most Reformed teach that baptism is a sign and seal of grace but does not itself save. Baptists teach it is a public testimony of an already-existing faith.\n\nThe early church took baptism far more seriously than most modern Christians realize. The Didache (1st century) prescribed fasting before baptism. The Apostolic Tradition (3rd century) required a three-year catechumenate (preparation period). Baptism was performed at Easter, connected to Christ's death and resurrection. Candidates were exorcised, anointed, immersed three times (Father, Son, Spirit), given white robes, and immediately received the Eucharist for the first time. It was the most dramatic ritual in early Christianity.",
      advanced:
        "The theology of baptism raises the hardest questions about salvation and exclusion. If baptism is necessary for salvation (as some traditions teach), what about unbaptized infants who die? Augustine said they go to a mild form of hell (limbus infantium). Thomas Aquinas developed the idea of Limbo. The Eastern Orthodox tradition, following Gregory of Nazianzus, holds that God judges unbaptized infants with mercy. In 2007, the Vatican's International Theological Commission issued a document saying Limbo was a 'hypothesis' and expressing hope that unbaptized infants are saved.\n\nKarl Barth launched the most significant modern challenge to infant baptism from within the Reformed tradition, arguing that baptism requires the free response of faith and that infant baptism inevitably leads to a 'nominal Christianity' where everyone is baptized but few are committed. Jurgen Moltmann sided with Barth. The debate continues.\n\nEcumenical convergence on baptism was achieved in the World Council of Churches document 'Baptism, Eucharist and Ministry' (Lima Document, 1982), which acknowledged that both infant and believer's baptism have legitimate theological foundations and called on traditions to recognize each other's baptisms. This was a historic achievement, though implementation remains uneven."
    },
  },

  {
    id: "c8-05",
    slug: "sacred-music",
    domainId: "d8",
    name: "Sacred Music: From Gregorian Chant to Gospel",
    summary:
      "Music is the most powerful and most contested element of Christian worship. Every generation fights about it.",
    lensTags: ["academic", "catholic", "protestant"],
    relatedConceptSlugs: ["liturgical-calendar", "eucharist-meanings"],
    relatedTextRefs: ["Psalm 150", "Colossians 3:16", "Ephesians 5:19"],
    layers: {
      accessible:
        "Christians have been singing since the beginning. Paul told the Colossians to sing 'psalms, hymns, and spiritual songs.' But what that sounds like has changed dramatically over 2,000 years. Gregorian chant (6th-10th centuries) was monophonic (one melodic line, no harmony), unaccompanied, and designed to carry Latin scripture. The Reformation brought congregational singing in local languages -- Martin Luther wrote hymns and said 'the devil doesn't need all the good tunes.' Isaac Watts and Charles Wesley created the English hymn tradition. African American spirituals emerged from slavery as coded resistance and theology of hope. Gospel music brought blues inflections and call-and-response. Contemporary worship music (Hillsong, Bethel) uses pop/rock idioms. Every shift provoked controversy: instruments vs. no instruments, choirs vs. congregations, organs vs. guitars, written vs. spontaneous.",
      intermediate:
        "The theological question behind worship music debates is: what is music FOR in worship? Three views: (1) Music as offering to God (the Catholic/Orthodox view): the quality of the music matters because it is being offered to the divine. This justifies training, complexity, and aesthetic excellence. (2) Music as congregational participation (the Reformed/evangelical view): the purpose is to enable the congregation to sing together. Simplicity and accessibility are virtues. (3) Music as emotional experience (the charismatic/contemporary view): music creates an atmosphere for encountering God. Production quality and emotional intensity are valued.\n\nThe 'worship wars' of the 1990s-2000s were not really about musical style -- they were about ecclesiology (what is the church for?) and cultural identity (whose culture gets to define 'sacred'?). The traditional side argued that abandoning hymns meant abandoning theological depth (hymns like 'And Can It Be' contain more theology than many sermons). The contemporary side argued that forcing people to sing 18th-century music in 21st-century culture was choosing tradition over mission.\n\nAfrican American sacred music deserves special attention. Spirituals like 'Go Down, Moses' and 'Steal Away' functioned simultaneously as worship, coded communication (songs signaling escape routes on the Underground Railroad), and political theology (identifying enslaved people with Israel in Egypt). This tradition produced gospel, soul, and eventually influenced virtually all popular music worldwide. It is arguably America's most important contribution to global culture.",
      advanced:
        "Jeremy Begbie ('Theology, Music, and Time,' 'Resounding Truth') has done the most significant work on the theology of music, arguing that music's temporal nature (it unfolds in time, creates tension and resolution, layers multiple voices simultaneously) provides unique theological insights. Polyphony (multiple independent voices creating harmony) is a better image of the Trinity than any static visual metaphor -- three distinct voices that are simultaneously independent and unified.\n\nThe loss of congregational singing in many contemporary churches (replaced by performance-oriented 'worship teams' that the congregation watches) has been critiqued by Marva Dawn ('Reaching Out Without Dumbing Down') and Lester Ruth as a fundamental shift from participation to consumption -- turning worship from something the congregation does together into something done for them. This mirrors broader cultural patterns of passivity and consumerism."
    },
  },
];
