import type { Concept } from "./types";

export const domain9Concepts: Concept[] = [
  {
    id: "c9-01",
    slug: "second-temple-judaism",
    domainId: "d9",
    name: "Second Temple Judaism",
    summary:
      "The diverse world of Jewish belief and practice (516 BCE - 70 CE) in which Jesus lived, Paul was educated, and Christianity was born. Understanding it transforms how you read the New Testament.",
    lensTags: ["academic", "jewish", "protestant", "catholic"],
    relatedConceptSlugs: ["documentary-hypothesis", "dead-sea-scrolls", "synoptic-problem"],
    relatedTextRefs: ["Daniel 7:13-14", "1 Enoch 37-71", "Matthew 23"],
    layers: {
      accessible:
        "When Jesus walked into the Temple, it was not a single unified religion he encountered. Second Temple Judaism (the period from the rebuilding of the Temple in 516 BCE to its destruction in 70 CE) was wildly diverse. The Pharisees emphasized oral Torah and believed in resurrection. The Sadducees controlled the Temple priesthood and rejected resurrection. The Essenes (likely behind the Dead Sea Scrolls) withdrew from the corrupt Temple entirely. The Zealots wanted armed revolution against Rome. Samaritans worshiped on Mount Gerizim instead of Jerusalem. And apocalyptic visionaries expected God to intervene dramatically to overthrow evil and establish justice. Jesus was a Jew within this world -- his teachings, parables, and conflicts make sense only within it. Christianity did not replace Judaism; it emerged from one stream of Judaism in conversation and conflict with others.",
      intermediate:
        "The 'parting of the ways' between Christianity and Judaism was not a single event but a gradual process spanning roughly 70-135 CE. The destruction of the Temple (70 CE) removed the Sadducees and Temple-centered worship, leaving Pharisaic/Rabbinic Judaism and Jewish-Christianity as the two surviving movements. Both claimed to be the true continuation of Israel's faith.\n\nThe concept of 'messiah' in Second Temple Judaism was far more diverse than Christians usually assume. The Dead Sea Scrolls mention TWO messiahs (a priestly messiah of Aaron and a royal messiah of David). Some texts envision a warrior-king who would defeat Rome. Others envision a heavenly figure (the 'Son of Man' in 1 Enoch). Daniel 7's 'one like a son of man' is not clearly an individual but may represent the people of Israel. When Jesus uses 'Son of Man' in the Gospels, he is entering a contested conversation, not citing a fixed job description.\n\nPaul's theology cannot be understood outside Second Temple Judaism. His concepts of justification, covenant, election, Torah, and the Spirit are all rooted in Jewish theological categories. The 'New Perspective on Paul' (E.P. Sanders, James Dunn, N.T. Wright) has demonstrated that Paul was not critiquing 'works-righteousness' (a later Protestant projection) but arguing about how Gentiles enter the covenant community without adopting Jewish ethnic markers.",
      advanced:
        "The most significant scholarly development for Second Temple studies is the recognition of 'apocalypticism' as a major intellectual movement, not a marginal fringe. Apocalyptic literature (Daniel, 1 Enoch, 4 Ezra, 2 Baruch, Jubilees, Assumption of Moses) reveals a worldview in which cosmic forces of good and evil are locked in battle, history is heading toward a climactic divine intervention, and the present age of suffering will give way to a new age of justice. This is the worldview of Jesus and Paul.\n\nAlbert Schweitzer ('The Quest of the Historical Jesus,' 1906) established that Jesus was an apocalyptic prophet who expected the imminent end of the present age. This was deeply uncomfortable for liberal Protestantism, which had constructed a Jesus who taught timeless ethical principles. Schweitzer's Jesus is alien and strange -- a first-century Jew who expected God to transform the world within his generation.\n\nThe diversity of Second Temple Judaism means that concepts like 'resurrection,' 'messiah,' 'salvation,' and 'kingdom of God' did not have fixed meanings. Different groups defined them differently. When Paul says 'Christ died for our sins,' he is making a theological claim that would have been intelligible within certain streams of Judaism (sacrificial atonement, the suffering righteous one) but bizarre in others. The New Testament is not a free-standing document but a participant in an intra-Jewish debate about God, covenant, and the future of the world."
    },
    honestAnalysis:
      "Christians have historically projected later Christian-Jewish hostility back onto the New Testament period, reading the Pharisees as villains rather than serious theological conversation partners. Understanding Second Temple diversity makes the New Testament more interesting, not less -- but it also makes simple readings much harder to sustain.",
  },

  {
    id: "c9-02",
    slug: "rabbinic-judaism",
    domainId: "d9",
    name: "Rabbinic Judaism and the Talmud",
    summary:
      "The form of Judaism that emerged after the Temple's destruction, organized around Torah study, prayer, and the monumental Talmudic literature that records centuries of legal and ethical debate.",
    lensTags: ["academic", "jewish", "interfaith"],
    relatedConceptSlugs: ["second-temple-judaism", "biblical-hebrew"],
    relatedTextRefs: ["Deuteronomy 6:4-9", "Leviticus 19:18"],
    layers: {
      accessible:
        "When the Romans destroyed the Jerusalem Temple in 70 CE, Judaism faced an existential crisis. The entire sacrificial system, the priesthood, and the central place of worship were gone. Rabbinic Judaism, descended primarily from the Pharisees, responded by transforming Judaism from a Temple religion into a portable faith centered on Torah study, prayer, and ethical practice. The synagogue replaced the Temple. The rabbi replaced the priest. The table replaced the altar. The Talmud -- a vast compilation of legal discussion, ethical debate, stories, and theological reflection -- became the central text of Jewish intellectual life. It exists in two versions: the Jerusalem Talmud (c. 400 CE) and the Babylonian Talmud (c. 500 CE), with the Babylonian becoming authoritative.",
      intermediate:
        "The Talmud is structured around the Mishnah (compiled c. 200 CE by Rabbi Judah ha-Nasi), which organized oral legal traditions into six 'orders' covering agriculture, festivals, marriage/divorce, civil and criminal law, Temple ritual, and purity. The Gemara is the extended commentary on the Mishnah, recording centuries of rabbinic debate. A page of Talmud shows the Mishnah in the center, Gemara around it, and medieval commentaries (Rashi, Tosafot) in the margins -- a visual representation of ongoing conversation across centuries.\n\nThe hermeneutical method is distinctive: contradictions are never resolved by choosing one opinion over another but by finding the conditions under which each is correct. 'Both these and those are the words of the living God' (Eruvin 13b). This means truth is not a single proposition but a conversation. Arguments that lost the vote are still preserved, because a minority opinion today might become the majority tomorrow.\n\nChristians knowing rabbinic literature enriches New Testament reading enormously. Jesus' parables use rabbinic forms. His legal debates with the Pharisees follow rabbinic patterns. 'The sabbath was made for humanity, not humanity for the sabbath' (Mark 2:27) is a recognizably rabbinic argument. Understanding this context transforms Jesus from someone attacking Judaism to someone arguing within it.",
      advanced:
        "The relationship between rabbinic Judaism and early Christianity is best understood as a 'sibling rivalry' rather than parent-child. Daniel Boyarin ('The Jewish Gospels,' 'Border Lines') argues that Judaism and Christianity did not diverge from a common 'original' but co-constituted each other -- each defined itself partly in opposition to the other. The Birkat haMinim (a prayer against heretics added to the Amidah, possibly targeting Jewish Christians) and the Christian anti-Jewish polemic in John's Gospel (which speaks of 'the Jews' as outsiders) represent the same boundary-marking process from both sides.\n\nThe midrashic method of reading Scripture (finding meaning in every detail, connecting distant texts through verbal links, reading gaps and silences as significant) has been recovered by contemporary literary critics as a sophisticated hermeneutic. James Kugel ('The Bible As It Was') demonstrates that much early Christian biblical interpretation used the same methods as rabbinic midrash.\n\nFor interfaith dialogue: the single most productive area is shared engagement with Scripture. Jewish and Christian scholars reading the same text together consistently discover readings that neither tradition sees alone. The 'Scriptural Reasoning' movement (David Ford, Peter Ochs) formalizes this practice. The challenge: centuries of Christian anti-Judaism (leading ultimately to the Shoah) mean that genuine dialogue requires Christians to acknowledge and repent of this history, not just move past it."
    },
  },

  {
    id: "c9-03",
    slug: "jewish-christian-relations",
    domainId: "d9",
    name: "Judaism and Christianity: The Parting of the Ways",
    summary:
      "Christianity began as a Jewish movement. Understanding when, how, and why it separated from Judaism transforms how you read the entire New Testament.",
    lensTags: ["academic", "jewish", "ecumenical"],
    relatedConceptSlugs: ["septuagint", "septuagint"],
    relatedTextRefs: ["Romans 9-11", "Matthew 23", "John 8:44"],
    layers: {
      accessible:
        "Jesus was Jewish. His disciples were Jewish. Paul was a Pharisee. The earliest 'Christians' did not call themselves Christians -- they were Jews who believed Jesus was the Messiah. They attended synagogue, observed Torah, and circumcised their sons. The 'parting of the ways' between Judaism and Christianity was not a single event but a gradual process spanning roughly 70-135 CE. The destruction of the Jerusalem Temple in 70 CE was the catalyst: without the Temple, both Judaism and Christianity had to reinvent themselves. Rabbinic Judaism (focused on Torah study and community) and Christianity (focused on Christ and expanding to Gentiles) developed along increasingly separate paths.",
      intermediate:
        "The separation was messier and more gradual than either tradition has wanted to admit. The 'Birkat haMinim' (a blessing against heretics, added to the synagogue liturgy around 85-90 CE) may have been directed partly at Jewish Christians, but scholars debate this. John's gospel (written around 90-100 CE) reflects a community that has been expelled from the synagogue -- which explains its hostile references to 'the Jews' (a phrase that has fueled centuries of anti-Jewish violence when read out of context).\n\nThe theological separation centered on two issues: (1) the status of Jesus (is he the Messiah? is he divine? both claims were problematic from a Jewish perspective), and (2) the status of Torah (Paul's argument that Gentile believers do not need to observe Torah was, from the Jewish perspective, an abandonment of the covenant). These were not merely academic disagreements -- they were identity-defining questions with life-or-death stakes.\n\nThe history of Christian anti-Judaism is devastating. The church fathers (John Chrysostom's 'Against the Jews' sermons are the most notorious) developed a 'teaching of contempt' that presented Jews as Christ-killers, spiritually blind, and superseded by the church. This theological anti-Judaism provided the soil in which racial antisemitism grew, culminating in the Holocaust. The post-Holocaust Jewish-Christian dialogue has forced Christians to confront this history honestly.",
      advanced:
        "Daniel Boyarin ('The Jewish Gospels,' 'Border Lines') has argued provocatively that the 'parting of the ways' was not a separation of two pre-existing religions but the process by which two religions were created from a shared matrix. 'Judaism' and 'Christianity' as distinct, bounded entities did not exist in the 1st century -- they were constructed through centuries of mutual definition and boundary-drawing. 'Heresy' was the mechanism by which each tradition defined itself by excluding the other.\n\nThis has radical implications for reading the New Testament. When Paul argues against 'works of the law,' he is not attacking Judaism but arguing for a particular position within Judaism about how Gentiles relate to the covenant. When Matthew's Jesus criticizes the Pharisees, this is an intra-Jewish debate, not a Christian attack on Judaism. Reading these texts as Christian-versus-Jewish imposes a later framework on an earlier reality.\n\nThe most important post-Holocaust document is Nostra Aetate (Vatican II, 1965), which declared that Jews are not collectively responsible for Jesus' death and that the covenant with the Jewish people has never been revoked. This was revolutionary -- it overturned nearly 2,000 years of supersessionist theology. Protestant and Orthodox statements have followed, though unevenly. The ongoing theological question: if God's covenant with the Jewish people is irrevocable, what is the relationship between that covenant and the new covenant in Christ? This remains the most challenging question in Christian theology of religions."
    },
  },

  {
    id: "c9-04",
    slug: "islam-and-jesus",
    domainId: "d9",
    name: "Jesus in Islam: The Prophet Christians Misunderstand",
    summary:
      "Jesus (Isa) appears in the Quran more times than Muhammad. He is born of a virgin, performs miracles, and is called the Messiah. But he is not God.",
    lensTags: ["academic", "interfaith"],
    relatedConceptSlugs: ["second-temple-judaism", "christology", "rabbinic-judaism"],
    relatedTextRefs: ["Quran 3:45-55", "Quran 19:16-35", "Quran 4:157-158"],
    layers: {
      accessible:
        "Most Christians are surprised to learn that Jesus is one of the most important figures in Islam. The Quran mentions Jesus (Isa ibn Maryam, 'Jesus son of Mary') by name 25 times -- more than Muhammad. The Quran affirms: Jesus was born of a virgin (Surah 19:16-35). Jesus performed miracles (healing the sick, raising the dead, creating birds from clay). Jesus is called 'the Messiah' (al-Masih) and 'a Word from God.' But Islam denies three things Christians consider essential: that Jesus is the Son of God (God does not have children, Quran 4:171), that Jesus was crucified (God would not allow a prophet to be so humiliated, Quran 4:157), and that Jesus is divine (Jesus is a prophet, one of many, and it is blasphemy to worship anyone other than God). In Islam, Jesus is honored as one of the greatest prophets -- but firmly human.",
      intermediate:
        "The Quranic Jesus is a corrective figure. He corrects Jewish rejection of him as Messiah and Christian 'exaggeration' of him as God. Quran 5:116-117 depicts a scene where God asks Jesus: 'Did you tell the people to take you and your mother as gods?' Jesus replies: 'Glory be to You! It was not for me to say what I had no right to say.' This verse targets what the Quran considers Christian error: elevating Jesus to divinity.\n\nThe crucifixion denial (Quran 4:157: 'they did not kill him, nor did they crucify him, but so it was made to appear to them') has generated extensive commentary. Some Muslim scholars interpret this as a docetic claim (it appeared that Jesus was crucified but was not really). Others say a substitute was crucified in his place. Some modern Muslim scholars accept the historical crucifixion but interpret the verse spiritually: the Jews did not triumph over Jesus because God raised him.\n\nMary (Maryam) receives more attention in the Quran than in the entire New Testament. Surah 19 is named after her. She is the only woman mentioned by name in the Quran. The birth narrative in Surah 19 is more detailed than Luke's: Mary retreats to a remote place, gives birth under a palm tree, and the infant Jesus speaks from the cradle to defend his mother's honor.\n\nFor interfaith dialogue, the shared reverence for Jesus provides common ground while the theological differences remain real and irreducible. Christians and Muslims are closer on Jesus than either is to secular modernity -- and further apart on Jesus than either is on ethics, prayer, or social justice.",
      advanced:
        "Tarif Khalidi's 'The Muslim Jesus' collects sayings attributed to Jesus in Islamic literature beyond the Quran, revealing a rich tradition of Jesus as wisdom teacher and ascetic. In these hadith and stories, Jesus emphasizes poverty, detachment from the world, and inner purity -- he sounds remarkably like the Desert Fathers.\n\nThe Christian-Muslim dialogue on Jesus has been advanced by scholars like Kenneth Cragg ('Jesus and the Muslim'), Oddbjorn Leirvik ('Images of Jesus Christ in Islam'), and Mona Siddiqui ('Christians, Muslims, and Jesus'). The central insight: Christians and Muslims share a deep reverence for Jesus but disagree fundamentally about what kind of authority he has. For Christians, Jesus reveals God's nature. For Muslims, Jesus reveals God's will. The difference is between incarnational theology (God becomes human) and prophetic theology (God sends messengers). This is not a small difference, but it is a difference between two communities that take Jesus seriously, not between faith and unbelief."
    },
  },

  {
    id: "c9-05",
    slug: "kabbalah-and-christianity",
    domainId: "d9",
    name: "Kabbalah: Jewish Mysticism and Its Christian Shadow",
    summary:
      "Kabbalah influenced Renaissance Christianity, shaped the Reformation, and anticipated modern theology -- yet most Christians have never heard of it.",
    lensTags: ["academic", "contemplative", "interfaith"],
    relatedConceptSlugs: ["second-temple-judaism", "trinity", "cloud-of-unknowing"],
    relatedTextRefs: ["Genesis 1:1-3", "Ezekiel 1", "Proverbs 8"],
    layers: {
      accessible:
        "Kabbalah is the Jewish mystical tradition. At its heart is the idea that God is utterly beyond comprehension (Ein Sof, 'Without End') but makes Godself known through ten emanations called sefirot -- qualities like wisdom, understanding, compassion, justice, beauty, and sovereignty. These are not separate gods but aspects of the one God's self-expression, like facets of a diamond. The sefirot form a pattern called the Tree of Life that maps the relationship between the infinite God and the finite world. For Kabbalists, the physical world is not separate from God but the outermost expression of God's creative energy. Everything visible points to something invisible. Everything finite participates in the infinite.",
      intermediate:
        "Kabbalah's influence on Christianity is larger than most people realize. Renaissance scholars like Pico della Mirandola and Johannes Reuchlin developed 'Christian Kabbalah' -- using Kabbalistic concepts to argue for Christian doctrines (the sefirot as a model of the Trinity, for example). This movement influenced Reformation-era biblical scholarship (Reuchlin's Hebrew studies were foundational) and Renaissance art (Michelangelo's Sistine Chapel ceiling shows traces of Kabbalistic cosmology).\n\nThe Kabbalistic concept of tzimtzum (divine contraction) has profoundly influenced modern theology. In the Lurianic Kabbalah of Isaac Luria (16th century), God creates the world by 'contracting' -- withdrawing from a space to make room for something other than God. This addresses the problem: if God is everywhere, how is there room for anything else? God must self-limit to create. Jurgen Moltmann adopted tzimtzum as the theological foundation for creation in 'God in Creation.' Hans Urs von Balthasar drew on it in his theology of Holy Saturday (God's absence as a mode of presence).\n\nTikkun olam ('repair of the world') -- now a popular phrase in progressive Judaism -- originates in Lurianic Kabbalah. The idea is that creation was originally a vessel meant to hold divine light, but the vessel shattered, scattering sparks of divinity throughout the world. Every act of justice, compassion, and holiness 'gathers the sparks' and repairs the broken vessel. This gives cosmic significance to ethical action: when you do good, you are not just helping one person -- you are healing the structure of reality.",
      advanced:
        "Gershom Scholem ('Major Trends in Jewish Mysticism') and Moshe Idel ('Kabbalah: New Perspectives') are the foundational scholars. Scholem demonstrated that Kabbalah was not a marginal curiosity but a central stream of Jewish thought that influenced law, ethics, prayer, and politics. Idel challenged Scholem's historical approach with a phenomenological one, emphasizing the experiential and ecstatic dimensions of Kabbalistic practice.\n\nThe relationship between Kabbalah and apophatic Christian theology (Pseudo-Dionysius, Meister Eckhart, the Cloud of Unknowing) is striking. Both traditions insist that God is beyond all positive description. Both use paradox and negation. Both emphasize that the goal of spiritual life is direct experience of the divine, not merely correct beliefs about the divine. Whether this parallel reflects historical influence or independent discovery of a universal mystical structure remains debated."
    },
  },
];
